// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: saf/saf.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.saf.v1;

@kotlin.jvm.JvmName("-initializecategoryScore")
public inline fun categoryScore(block: com.solra.apis.saf.v1.CategoryScoreKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.CategoryScore =
  com.solra.apis.saf.v1.CategoryScoreKt.Dsl._create(com.solra.apis.saf.v1.Saf.CategoryScore.newBuilder()).apply { block() }._build()
/**
 * ```
 * CategoryScore 类别得分
 * ```
 *
 * Protobuf type `solra.saf.v1.CategoryScore`
 */
public object CategoryScoreKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.saf.v1.Saf.CategoryScore.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.saf.v1.Saf.CategoryScore.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.saf.v1.Saf.CategoryScore = _builder.build()

    /**
     * `.solra.saf.v1.ViolationCategory category = 1 [json_name = "category"];`
     */
    public var category: com.solra.apis.saf.v1.Saf.ViolationCategory
      @kotlin.jvm.JvmName("getCategory")
        get() = _builder.category
      @kotlin.jvm.JvmName("setCategory")
        set(value) {
        _builder.category = value
      }
    public var categoryValue: kotlin.Int
      @kotlin.jvm.JvmName("getCategoryValue")
        get() = _builder.categoryValue
      @kotlin.jvm.JvmName("setCategoryValue")
        set(value) {
        _builder.categoryValue = value
      }
    /**
     * `.solra.saf.v1.ViolationCategory category = 1 [json_name = "category"];`
     */
    public fun clearCategory() {
      _builder.clearCategory()
    }

    /**
     * ```
     * 该类别违规概率 0-1
     * ```
     *
     * `float score = 2 [json_name = "score"];`
     */
    public var score: kotlin.Float
      @kotlin.jvm.JvmName("getScore")
        get() = _builder.score
      @kotlin.jvm.JvmName("setScore")
        set(value) {
        _builder.score = value
      }
    /**
     * ```
     * 该类别违规概率 0-1
     * ```
     *
     * `float score = 2 [json_name = "score"];`
     */
    public fun clearScore() {
      _builder.clearScore()
    }

    /**
     * ```
     * 得分说明
     * ```
     *
     * `string explanation = 3 [json_name = "explanation"];`
     */
    public var explanation: kotlin.String
      @kotlin.jvm.JvmName("getExplanation")
        get() = _builder.explanation
      @kotlin.jvm.JvmName("setExplanation")
        set(value) {
        _builder.explanation = value
      }
    /**
     * ```
     * 得分说明
     * ```
     *
     * `string explanation = 3 [json_name = "explanation"];`
     */
    public fun clearExplanation() {
      _builder.clearExplanation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.saf.v1.Saf.CategoryScore.copy(block: `com.solra.apis.saf.v1`.CategoryScoreKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.CategoryScore =
  `com.solra.apis.saf.v1`.CategoryScoreKt.Dsl._create(this.toBuilder()).apply { block() }._build()

