// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/saf/v1/saf.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.saf.v1;

@kotlin.jvm.JvmName("-initializefilterContentResponse")
public inline fun filterContentResponse(block: com.solra.apis.saf.v1.FilterContentResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.FilterContentResponse =
  com.solra.apis.saf.v1.FilterContentResponseKt.Dsl._create(com.solra.apis.saf.v1.Saf.FilterContentResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.saf.v1.FilterContentResponse`
 */
public object FilterContentResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.saf.v1.Saf.FilterContentResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.saf.v1.Saf.FilterContentResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.saf.v1.Saf.FilterContentResponse = _builder.build()

    /**
     * ```
     * 是否通过过滤
     * ```
     *
     * `bool passed = 1 [json_name = "passed"];`
     */
    public var passed: kotlin.Boolean
      @kotlin.jvm.JvmName("getPassed")
        get() = _builder.passed
      @kotlin.jvm.JvmName("setPassed")
        set(value) {
        _builder.passed = value
      }
    /**
     * ```
     * 是否通过过滤
     * ```
     *
     * `bool passed = 1 [json_name = "passed"];`
     */
    public fun clearPassed() {
      _builder.clearPassed()
    }

    /**
     * ```
     * 安全评分
     * ```
     *
     * `.solra.saf.v1.SafetyScore score = 2 [json_name = "score"];`
     */
    public var score: com.solra.apis.saf.v1.Saf.SafetyScore
      @kotlin.jvm.JvmName("getScore")
        get() = _builder.score
      @kotlin.jvm.JvmName("setScore")
        set(value) {
        _builder.score = value
      }
    /**
     * ```
     * 安全评分
     * ```
     *
     * `.solra.saf.v1.SafetyScore score = 2 [json_name = "score"];`
     */
    public fun clearScore() {
      _builder.clearScore()
    }
    /**
     * ```
     * 安全评分
     * ```
     *
     * `.solra.saf.v1.SafetyScore score = 2 [json_name = "score"];`
     * @return Whether the score field is set.
     */
    public fun hasScore(): kotlin.Boolean {
      return _builder.hasScore()
    }

    public val FilterContentResponseKt.Dsl.scoreOrNull: com.solra.apis.saf.v1.Saf.SafetyScore?
      get() = _builder.scoreOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ViolationsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 违规详情
     * ```
     *
     * `repeated .solra.saf.v1.PolicyViolation violations = 3 [json_name = "violations"];`
     */
     public val violations: com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.PolicyViolation, ViolationsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.violationsList
      )
    /**
     * ```
     * 违规详情
     * ```
     *
     * `repeated .solra.saf.v1.PolicyViolation violations = 3 [json_name = "violations"];`
     * @param value The violations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addViolations")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.PolicyViolation, ViolationsProxy>.add(value: com.solra.apis.saf.v1.Saf.PolicyViolation) {
      _builder.addViolations(value)
    }
    /**
     * ```
     * 违规详情
     * ```
     *
     * `repeated .solra.saf.v1.PolicyViolation violations = 3 [json_name = "violations"];`
     * @param value The violations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignViolations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.PolicyViolation, ViolationsProxy>.plusAssign(value: com.solra.apis.saf.v1.Saf.PolicyViolation) {
      add(value)
    }
    /**
     * ```
     * 违规详情
     * ```
     *
     * `repeated .solra.saf.v1.PolicyViolation violations = 3 [json_name = "violations"];`
     * @param values The violations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllViolations")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.PolicyViolation, ViolationsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.saf.v1.Saf.PolicyViolation>) {
      _builder.addAllViolations(values)
    }
    /**
     * ```
     * 违规详情
     * ```
     *
     * `repeated .solra.saf.v1.PolicyViolation violations = 3 [json_name = "violations"];`
     * @param values The violations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllViolations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.PolicyViolation, ViolationsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.saf.v1.Saf.PolicyViolation>) {
      addAll(values)
    }
    /**
     * ```
     * 违规详情
     * ```
     *
     * `repeated .solra.saf.v1.PolicyViolation violations = 3 [json_name = "violations"];`
     * @param index The index to set the value at.
     * @param value The violations to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setViolations")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.PolicyViolation, ViolationsProxy>.set(index: kotlin.Int, value: com.solra.apis.saf.v1.Saf.PolicyViolation) {
      _builder.setViolations(index, value)
    }
    /**
     * ```
     * 违规详情
     * ```
     *
     * `repeated .solra.saf.v1.PolicyViolation violations = 3 [json_name = "violations"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearViolations")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.PolicyViolation, ViolationsProxy>.clear() {
      _builder.clearViolations()
    }

    /**
     * ```
     * 过滤后的内容（如脱敏文本）
     * ```
     *
     * `string filtered_content = 4 [json_name = "filteredContent"];`
     */
    public var filteredContent: kotlin.String
      @kotlin.jvm.JvmName("getFilteredContent")
        get() = _builder.filteredContent
      @kotlin.jvm.JvmName("setFilteredContent")
        set(value) {
        _builder.filteredContent = value
      }
    /**
     * ```
     * 过滤后的内容（如脱敏文本）
     * ```
     *
     * `string filtered_content = 4 [json_name = "filteredContent"];`
     */
    public fun clearFilteredContent() {
      _builder.clearFilteredContent()
    }

    /**
     * `.solra.common.SolraError error = 5 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 5 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 5 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val FilterContentResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.saf.v1.Saf.FilterContentResponse.copy(block: `com.solra.apis.saf.v1`.FilterContentResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.FilterContentResponse =
  `com.solra.apis.saf.v1`.FilterContentResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.saf.v1.Saf.FilterContentResponseOrBuilder.scoreOrNull: com.solra.apis.saf.v1.Saf.SafetyScore?
  get() = if (hasScore()) getScore() else null

public val com.solra.apis.saf.v1.Saf.FilterContentResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

