// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/saf/v1/saf.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.saf.v1;

@kotlin.jvm.JvmName("-initializegetWorkQueueResponse")
public inline fun getWorkQueueResponse(block: com.solra.apis.saf.v1.GetWorkQueueResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.GetWorkQueueResponse =
  com.solra.apis.saf.v1.GetWorkQueueResponseKt.Dsl._create(com.solra.apis.saf.v1.Saf.GetWorkQueueResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.saf.v1.GetWorkQueueResponse`
 */
public object GetWorkQueueResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.saf.v1.Saf.GetWorkQueueResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.saf.v1.Saf.GetWorkQueueResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.saf.v1.Saf.GetWorkQueueResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ItemsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.saf.v1.ReviewWorkbenchItem items = 1 [json_name = "items"];`
     */
     public val items: com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem, ItemsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.itemsList
      )
    /**
     * `repeated .solra.saf.v1.ReviewWorkbenchItem items = 1 [json_name = "items"];`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addItems")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem, ItemsProxy>.add(value: com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem) {
      _builder.addItems(value)
    }
    /**
     * `repeated .solra.saf.v1.ReviewWorkbenchItem items = 1 [json_name = "items"];`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem, ItemsProxy>.plusAssign(value: com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem) {
      add(value)
    }
    /**
     * `repeated .solra.saf.v1.ReviewWorkbenchItem items = 1 [json_name = "items"];`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllItems")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem, ItemsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem>) {
      _builder.addAllItems(values)
    }
    /**
     * `repeated .solra.saf.v1.ReviewWorkbenchItem items = 1 [json_name = "items"];`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem, ItemsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem>) {
      addAll(values)
    }
    /**
     * `repeated .solra.saf.v1.ReviewWorkbenchItem items = 1 [json_name = "items"];`
     * @param index The index to set the value at.
     * @param value The items to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setItems")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem, ItemsProxy>.set(index: kotlin.Int, value: com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem) {
      _builder.setItems(index, value)
    }
    /**
     * `repeated .solra.saf.v1.ReviewWorkbenchItem items = 1 [json_name = "items"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearItems")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.saf.v1.Saf.ReviewWorkbenchItem, ItemsProxy>.clear() {
      _builder.clearItems()
    }

    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val GetWorkQueueResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.saf.v1.Saf.GetWorkQueueResponse.copy(block: `com.solra.apis.saf.v1`.GetWorkQueueResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.GetWorkQueueResponse =
  `com.solra.apis.saf.v1`.GetWorkQueueResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.saf.v1.Saf.GetWorkQueueResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

