// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/saf/v1/saf.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.saf.v1;

@kotlin.jvm.JvmName("-initializequeryReportResultRequest")
public inline fun queryReportResultRequest(block: com.solra.apis.saf.v1.QueryReportResultRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.QueryReportResultRequest =
  com.solra.apis.saf.v1.QueryReportResultRequestKt.Dsl._create(com.solra.apis.saf.v1.Saf.QueryReportResultRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * QueryReportResult 查询举报结果
 * ```
 *
 * Protobuf type `solra.saf.v1.QueryReportResultRequest`
 */
public object QueryReportResultRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.saf.v1.Saf.QueryReportResultRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.saf.v1.Saf.QueryReportResultRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.saf.v1.Saf.QueryReportResultRequest = _builder.build()

    /**
     * `string report_id = 1 [json_name = "reportId"];`
     */
    public var reportId: kotlin.String
      @kotlin.jvm.JvmName("getReportId")
        get() = _builder.reportId
      @kotlin.jvm.JvmName("setReportId")
        set(value) {
        _builder.reportId = value
      }
    /**
     * `string report_id = 1 [json_name = "reportId"];`
     */
    public fun clearReportId() {
      _builder.clearReportId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.saf.v1.Saf.QueryReportResultRequest.copy(block: `com.solra.apis.saf.v1`.QueryReportResultRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.QueryReportResultRequest =
  `com.solra.apis.saf.v1`.QueryReportResultRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

