// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/saf/v1/saf.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.saf.v1;

@kotlin.jvm.JvmName("-initializequeryReviewResultResponse")
public inline fun queryReviewResultResponse(block: com.solra.apis.saf.v1.QueryReviewResultResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.QueryReviewResultResponse =
  com.solra.apis.saf.v1.QueryReviewResultResponseKt.Dsl._create(com.solra.apis.saf.v1.Saf.QueryReviewResultResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.saf.v1.QueryReviewResultResponse`
 */
public object QueryReviewResultResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.saf.v1.Saf.QueryReviewResultResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.saf.v1.Saf.QueryReviewResultResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.saf.v1.Saf.QueryReviewResultResponse = _builder.build()

    /**
     * `.solra.saf.v1.ReviewCase review_case = 1 [json_name = "reviewCase"];`
     */
    public var reviewCase: com.solra.apis.saf.v1.Saf.ReviewCase
      @kotlin.jvm.JvmName("getReviewCase")
        get() = _builder.reviewCase
      @kotlin.jvm.JvmName("setReviewCase")
        set(value) {
        _builder.reviewCase = value
      }
    /**
     * `.solra.saf.v1.ReviewCase review_case = 1 [json_name = "reviewCase"];`
     */
    public fun clearReviewCase() {
      _builder.clearReviewCase()
    }
    /**
     * `.solra.saf.v1.ReviewCase review_case = 1 [json_name = "reviewCase"];`
     * @return Whether the reviewCase field is set.
     */
    public fun hasReviewCase(): kotlin.Boolean {
      return _builder.hasReviewCase()
    }

    public val QueryReviewResultResponseKt.Dsl.reviewCaseOrNull: com.solra.apis.saf.v1.Saf.ReviewCase?
      get() = _builder.reviewCaseOrNull

    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val QueryReviewResultResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.saf.v1.Saf.QueryReviewResultResponse.copy(block: `com.solra.apis.saf.v1`.QueryReviewResultResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.QueryReviewResultResponse =
  `com.solra.apis.saf.v1`.QueryReviewResultResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.saf.v1.Saf.QueryReviewResultResponseOrBuilder.reviewCaseOrNull: com.solra.apis.saf.v1.Saf.ReviewCase?
  get() = if (hasReviewCase()) getReviewCase() else null

public val com.solra.apis.saf.v1.Saf.QueryReviewResultResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

