// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/saf/v1/saf.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.saf.v1;

@kotlin.jvm.JvmName("-initializereviewCase")
public inline fun reviewCase(block: com.solra.apis.saf.v1.ReviewCaseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.ReviewCase =
  com.solra.apis.saf.v1.ReviewCaseKt.Dsl._create(com.solra.apis.saf.v1.Saf.ReviewCase.newBuilder()).apply { block() }._build()
/**
 * ```
 * ReviewCase 审核案例
 * ```
 *
 * Protobuf type `solra.saf.v1.ReviewCase`
 */
public object ReviewCaseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.saf.v1.Saf.ReviewCase.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.saf.v1.Saf.ReviewCase.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.saf.v1.Saf.ReviewCase = _builder.build()

    /**
     * `string case_id = 1 [json_name = "caseId"];`
     */
    public var caseId: kotlin.String
      @kotlin.jvm.JvmName("getCaseId")
        get() = _builder.caseId
      @kotlin.jvm.JvmName("setCaseId")
        set(value) {
        _builder.caseId = value
      }
    /**
     * `string case_id = 1 [json_name = "caseId"];`
     */
    public fun clearCaseId() {
      _builder.clearCaseId()
    }

    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val ReviewCaseKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * ```
     * 被审核的内容
     * ```
     *
     * `.solra.saf.v1.ContentTarget target = 3 [json_name = "target"];`
     */
    public var target: com.solra.apis.saf.v1.Saf.ContentTarget
      @kotlin.jvm.JvmName("getTarget")
        get() = _builder.target
      @kotlin.jvm.JvmName("setTarget")
        set(value) {
        _builder.target = value
      }
    /**
     * ```
     * 被审核的内容
     * ```
     *
     * `.solra.saf.v1.ContentTarget target = 3 [json_name = "target"];`
     */
    public fun clearTarget() {
      _builder.clearTarget()
    }
    /**
     * ```
     * 被审核的内容
     * ```
     *
     * `.solra.saf.v1.ContentTarget target = 3 [json_name = "target"];`
     * @return Whether the target field is set.
     */
    public fun hasTarget(): kotlin.Boolean {
      return _builder.hasTarget()
    }

    public val ReviewCaseKt.Dsl.targetOrNull: com.solra.apis.saf.v1.Saf.ContentTarget?
      get() = _builder.targetOrNull

    /**
     * `.solra.saf.v1.ReviewType review_type = 4 [json_name = "reviewType"];`
     */
    public var reviewType: com.solra.apis.saf.v1.Saf.ReviewType
      @kotlin.jvm.JvmName("getReviewType")
        get() = _builder.reviewType
      @kotlin.jvm.JvmName("setReviewType")
        set(value) {
        _builder.reviewType = value
      }
    public var reviewTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getReviewTypeValue")
        get() = _builder.reviewTypeValue
      @kotlin.jvm.JvmName("setReviewTypeValue")
        set(value) {
        _builder.reviewTypeValue = value
      }
    /**
     * `.solra.saf.v1.ReviewType review_type = 4 [json_name = "reviewType"];`
     */
    public fun clearReviewType() {
      _builder.clearReviewType()
    }

    /**
     * `.solra.saf.v1.ReviewStatus status = 5 [json_name = "status"];`
     */
    public var status: com.solra.apis.saf.v1.Saf.ReviewStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.solra.saf.v1.ReviewStatus status = 5 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * 审核结果（完成时有值）
     * ```
     *
     * `.solra.saf.v1.ReviewResult result = 6 [json_name = "result"];`
     */
    public var result: com.solra.apis.saf.v1.Saf.ReviewResult
      @kotlin.jvm.JvmName("getResult")
        get() = _builder.result
      @kotlin.jvm.JvmName("setResult")
        set(value) {
        _builder.result = value
      }
    /**
     * ```
     * 审核结果（完成时有值）
     * ```
     *
     * `.solra.saf.v1.ReviewResult result = 6 [json_name = "result"];`
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * ```
     * 审核结果（完成时有值）
     * ```
     *
     * `.solra.saf.v1.ReviewResult result = 6 [json_name = "result"];`
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }

    public val ReviewCaseKt.Dsl.resultOrNull: com.solra.apis.saf.v1.Saf.ReviewResult?
      get() = _builder.resultOrNull

    /**
     * `.solra.saf.v1.ReviewPriority priority = 7 [json_name = "priority"];`
     */
    public var priority: com.solra.apis.saf.v1.Saf.ReviewPriority
      @kotlin.jvm.JvmName("getPriority")
        get() = _builder.priority
      @kotlin.jvm.JvmName("setPriority")
        set(value) {
        _builder.priority = value
      }
    public var priorityValue: kotlin.Int
      @kotlin.jvm.JvmName("getPriorityValue")
        get() = _builder.priorityValue
      @kotlin.jvm.JvmName("setPriorityValue")
        set(value) {
        _builder.priorityValue = value
      }
    /**
     * `.solra.saf.v1.ReviewPriority priority = 7 [json_name = "priority"];`
     */
    public fun clearPriority() {
      _builder.clearPriority()
    }

    /**
     * `.solra.common.SolraTimestamp submitted_at = 8 [json_name = "submittedAt"];`
     */
    public var submittedAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getSubmittedAt")
        get() = _builder.submittedAt
      @kotlin.jvm.JvmName("setSubmittedAt")
        set(value) {
        _builder.submittedAt = value
      }
    /**
     * `.solra.common.SolraTimestamp submitted_at = 8 [json_name = "submittedAt"];`
     */
    public fun clearSubmittedAt() {
      _builder.clearSubmittedAt()
    }
    /**
     * `.solra.common.SolraTimestamp submitted_at = 8 [json_name = "submittedAt"];`
     * @return Whether the submittedAt field is set.
     */
    public fun hasSubmittedAt(): kotlin.Boolean {
      return _builder.hasSubmittedAt()
    }

    public val ReviewCaseKt.Dsl.submittedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.submittedAtOrNull

    /**
     * ```
     * 审核完成时间
     * ```
     *
     * `.solra.common.SolraTimestamp reviewed_at = 9 [json_name = "reviewedAt"];`
     */
    public var reviewedAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getReviewedAt")
        get() = _builder.reviewedAt
      @kotlin.jvm.JvmName("setReviewedAt")
        set(value) {
        _builder.reviewedAt = value
      }
    /**
     * ```
     * 审核完成时间
     * ```
     *
     * `.solra.common.SolraTimestamp reviewed_at = 9 [json_name = "reviewedAt"];`
     */
    public fun clearReviewedAt() {
      _builder.clearReviewedAt()
    }
    /**
     * ```
     * 审核完成时间
     * ```
     *
     * `.solra.common.SolraTimestamp reviewed_at = 9 [json_name = "reviewedAt"];`
     * @return Whether the reviewedAt field is set.
     */
    public fun hasReviewedAt(): kotlin.Boolean {
      return _builder.hasReviewedAt()
    }

    public val ReviewCaseKt.Dsl.reviewedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.reviewedAtOrNull

    /**
     * ```
     * 审核员/模型ID
     * ```
     *
     * `string reviewer_id = 10 [json_name = "reviewerId"];`
     */
    public var reviewerId: kotlin.String
      @kotlin.jvm.JvmName("getReviewerId")
        get() = _builder.reviewerId
      @kotlin.jvm.JvmName("setReviewerId")
        set(value) {
        _builder.reviewerId = value
      }
    /**
     * ```
     * 审核员/模型ID
     * ```
     *
     * `string reviewer_id = 10 [json_name = "reviewerId"];`
     */
    public fun clearReviewerId() {
      _builder.clearReviewerId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MetadataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> metadata = 11 [json_name = "metadata"];`
     */
     public val metadata: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getMetadataMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.metadataMap
      )
    /**
     * `map<string, string> metadata = 11 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmName("putMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putMetadata(key, value)
       }
    /**
     * `map<string, string> metadata = 11 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMetadata")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> metadata = 11 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .remove(key: kotlin.String) {
         _builder.removeMetadata(key)
       }
    /**
     * `map<string, string> metadata = 11 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllMetadata(map)
       }
    /**
     * `map<string, string> metadata = 11 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .clear() {
         _builder.clearMetadata()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.saf.v1.Saf.ReviewCase.copy(block: `com.solra.apis.saf.v1`.ReviewCaseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.ReviewCase =
  `com.solra.apis.saf.v1`.ReviewCaseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.saf.v1.Saf.ReviewCaseOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

public val com.solra.apis.saf.v1.Saf.ReviewCaseOrBuilder.targetOrNull: com.solra.apis.saf.v1.Saf.ContentTarget?
  get() = if (hasTarget()) getTarget() else null

public val com.solra.apis.saf.v1.Saf.ReviewCaseOrBuilder.resultOrNull: com.solra.apis.saf.v1.Saf.ReviewResult?
  get() = if (hasResult()) getResult() else null

public val com.solra.apis.saf.v1.Saf.ReviewCaseOrBuilder.submittedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasSubmittedAt()) getSubmittedAt() else null

public val com.solra.apis.saf.v1.Saf.ReviewCaseOrBuilder.reviewedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasReviewedAt()) getReviewedAt() else null

