// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/saf/v1/saf.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.saf.v1;

@kotlin.jvm.JvmName("-initializesubmitAppealRequest")
public inline fun submitAppealRequest(block: com.solra.apis.saf.v1.SubmitAppealRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.SubmitAppealRequest =
  com.solra.apis.saf.v1.SubmitAppealRequestKt.Dsl._create(com.solra.apis.saf.v1.Saf.SubmitAppealRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * SubmitAppeal
 * ```
 *
 * Protobuf type `solra.saf.v1.SubmitAppealRequest`
 */
public object SubmitAppealRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.saf.v1.Saf.SubmitAppealRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.saf.v1.Saf.SubmitAppealRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.saf.v1.Saf.SubmitAppealRequest = _builder.build()

    /**
     * `string case_id = 1 [json_name = "caseId"];`
     */
    public var caseId: kotlin.String
      @kotlin.jvm.JvmName("getCaseId")
        get() = _builder.caseId
      @kotlin.jvm.JvmName("setCaseId")
        set(value) {
        _builder.caseId = value
      }
    /**
     * `string case_id = 1 [json_name = "caseId"];`
     */
    public fun clearCaseId() {
      _builder.clearCaseId()
    }

    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val SubmitAppealRequestKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `string reason = 3 [json_name = "reason"];`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 3 [json_name = "reason"];`
     */
    public fun clearReason() {
      _builder.clearReason()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EvidenceUrlsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string evidence_urls = 4 [json_name = "evidenceUrls"];`
     * @return A list containing the evidenceUrls.
     */
    public val evidenceUrls: com.google.protobuf.kotlin.DslList<kotlin.String, EvidenceUrlsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.evidenceUrlsList
      )
    /**
     * `repeated string evidence_urls = 4 [json_name = "evidenceUrls"];`
     * @param value The evidenceUrls to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addEvidenceUrls")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EvidenceUrlsProxy>.add(value: kotlin.String) {
      _builder.addEvidenceUrls(value)
    }
    /**
     * `repeated string evidence_urls = 4 [json_name = "evidenceUrls"];`
     * @param value The evidenceUrls to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignEvidenceUrls")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EvidenceUrlsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string evidence_urls = 4 [json_name = "evidenceUrls"];`
     * @param values The evidenceUrls to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllEvidenceUrls")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EvidenceUrlsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllEvidenceUrls(values)
    }
    /**
     * `repeated string evidence_urls = 4 [json_name = "evidenceUrls"];`
     * @param values The evidenceUrls to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllEvidenceUrls")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EvidenceUrlsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string evidence_urls = 4 [json_name = "evidenceUrls"];`
     * @param index The index to set the value at.
     * @param value The evidenceUrls to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEvidenceUrls")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EvidenceUrlsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setEvidenceUrls(index, value)
    }/**
     * `repeated string evidence_urls = 4 [json_name = "evidenceUrls"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEvidenceUrls")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EvidenceUrlsProxy>.clear() {
      _builder.clearEvidenceUrls()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.saf.v1.Saf.SubmitAppealRequest.copy(block: `com.solra.apis.saf.v1`.SubmitAppealRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.SubmitAppealRequest =
  `com.solra.apis.saf.v1`.SubmitAppealRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.saf.v1.Saf.SubmitAppealRequestOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

