// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/saf/v1/saf.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.saf.v1;

@kotlin.jvm.JvmName("-initializesubmitReviewResponse")
public inline fun submitReviewResponse(block: com.solra.apis.saf.v1.SubmitReviewResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.SubmitReviewResponse =
  com.solra.apis.saf.v1.SubmitReviewResponseKt.Dsl._create(com.solra.apis.saf.v1.Saf.SubmitReviewResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.saf.v1.SubmitReviewResponse`
 */
public object SubmitReviewResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.saf.v1.Saf.SubmitReviewResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.saf.v1.Saf.SubmitReviewResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.saf.v1.Saf.SubmitReviewResponse = _builder.build()

    /**
     * `string case_id = 1 [json_name = "caseId"];`
     */
    public var caseId: kotlin.String
      @kotlin.jvm.JvmName("getCaseId")
        get() = _builder.caseId
      @kotlin.jvm.JvmName("setCaseId")
        set(value) {
        _builder.caseId = value
      }
    /**
     * `string case_id = 1 [json_name = "caseId"];`
     */
    public fun clearCaseId() {
      _builder.clearCaseId()
    }

    /**
     * `.solra.saf.v1.ReviewStatus status = 2 [json_name = "status"];`
     */
    public var status: com.solra.apis.saf.v1.Saf.ReviewStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.solra.saf.v1.ReviewStatus status = 2 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * 自动审核时可能直接返回结果
     * ```
     *
     * `.solra.saf.v1.ReviewResult result = 3 [json_name = "result"];`
     */
    public var result: com.solra.apis.saf.v1.Saf.ReviewResult
      @kotlin.jvm.JvmName("getResult")
        get() = _builder.result
      @kotlin.jvm.JvmName("setResult")
        set(value) {
        _builder.result = value
      }
    /**
     * ```
     * 自动审核时可能直接返回结果
     * ```
     *
     * `.solra.saf.v1.ReviewResult result = 3 [json_name = "result"];`
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * ```
     * 自动审核时可能直接返回结果
     * ```
     *
     * `.solra.saf.v1.ReviewResult result = 3 [json_name = "result"];`
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }

    public val SubmitReviewResponseKt.Dsl.resultOrNull: com.solra.apis.saf.v1.Saf.ReviewResult?
      get() = _builder.resultOrNull

    /**
     * `.solra.common.SolraError error = 4 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 4 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 4 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val SubmitReviewResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.saf.v1.Saf.SubmitReviewResponse.copy(block: `com.solra.apis.saf.v1`.SubmitReviewResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.saf.v1.Saf.SubmitReviewResponse =
  `com.solra.apis.saf.v1`.SubmitReviewResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.saf.v1.Saf.SubmitReviewResponseOrBuilder.resultOrNull: com.solra.apis.saf.v1.Saf.ReviewResult?
  get() = if (hasResult()) getResult() else null

public val com.solra.apis.saf.v1.Saf.SubmitReviewResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

