// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grw/grw.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.grw;

@kotlin.jvm.JvmName("-initializeequipBadgeResponse")
public inline fun equipBadgeResponse(block: com.solra.proto.grw.EquipBadgeResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.EquipBadgeResponse =
  com.solra.proto.grw.EquipBadgeResponseKt.Dsl._create(com.solra.proto.grw.Grw.EquipBadgeResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.grw.EquipBadgeResponse`
 */
public object EquipBadgeResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.grw.Grw.EquipBadgeResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.grw.Grw.EquipBadgeResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.grw.Grw.EquipBadgeResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val EquipBadgeResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull

    /**
     * `.solra.grw.BadgeCollection collection = 2 [json_name = "collection"];`
     */
    public var collection: com.solra.proto.grw.Grw.BadgeCollection
      @kotlin.jvm.JvmName("getCollection")
        get() = _builder.collection
      @kotlin.jvm.JvmName("setCollection")
        set(value) {
        _builder.collection = value
      }
    /**
     * `.solra.grw.BadgeCollection collection = 2 [json_name = "collection"];`
     */
    public fun clearCollection() {
      _builder.clearCollection()
    }
    /**
     * `.solra.grw.BadgeCollection collection = 2 [json_name = "collection"];`
     * @return Whether the collection field is set.
     */
    public fun hasCollection(): kotlin.Boolean {
      return _builder.hasCollection()
    }

    public val EquipBadgeResponseKt.Dsl.collectionOrNull: com.solra.proto.grw.Grw.BadgeCollection?
      get() = _builder.collectionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.grw.Grw.EquipBadgeResponse.copy(block: `com.solra.proto.grw`.EquipBadgeResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.EquipBadgeResponse =
  `com.solra.proto.grw`.EquipBadgeResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.grw.Grw.EquipBadgeResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

public val com.solra.proto.grw.Grw.EquipBadgeResponseOrBuilder.collectionOrNull: com.solra.proto.grw.Grw.BadgeCollection?
  get() = if (hasCollection()) getCollection() else null

