// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grw/grw.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.grw;

@kotlin.jvm.JvmName("-initializegetAchievementProgressRequest")
public inline fun getAchievementProgressRequest(block: com.solra.proto.grw.GetAchievementProgressRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.GetAchievementProgressRequest =
  com.solra.proto.grw.GetAchievementProgressRequestKt.Dsl._create(com.solra.proto.grw.Grw.GetAchievementProgressRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.grw.GetAchievementProgressRequest`
 */
public object GetAchievementProgressRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.grw.Grw.GetAchievementProgressRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.grw.Grw.GetAchievementProgressRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.grw.Grw.GetAchievementProgressRequest = _builder.build()

    /**
     * `string achievement_id = 1 [json_name = "achievementId"];`
     */
    public var achievementId: kotlin.String
      @kotlin.jvm.JvmName("getAchievementId")
        get() = _builder.achievementId
      @kotlin.jvm.JvmName("setAchievementId")
        set(value) {
        _builder.achievementId = value
      }
    /**
     * `string achievement_id = 1 [json_name = "achievementId"];`
     */
    public fun clearAchievementId() {
      _builder.clearAchievementId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.grw.Grw.GetAchievementProgressRequest.copy(block: `com.solra.proto.grw`.GetAchievementProgressRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.GetAchievementProgressRequest =
  `com.solra.proto.grw`.GetAchievementProgressRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

