// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grw/grw.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.grw;

@kotlin.jvm.JvmName("-initializegetFaithLevelRequest")
public inline fun getFaithLevelRequest(block: com.solra.proto.grw.GetFaithLevelRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.GetFaithLevelRequest =
  com.solra.proto.grw.GetFaithLevelRequestKt.Dsl._create(com.solra.proto.grw.Grw.GetFaithLevelRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.grw.GetFaithLevelRequest`
 */
public object GetFaithLevelRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.grw.Grw.GetFaithLevelRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.grw.Grw.GetFaithLevelRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.grw.Grw.GetFaithLevelRequest = _builder.build()

    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val GetFaithLevelRequestKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.grw.Grw.GetFaithLevelRequest.copy(block: `com.solra.proto.grw`.GetFaithLevelRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.GetFaithLevelRequest =
  `com.solra.proto.grw`.GetFaithLevelRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.grw.Grw.GetFaithLevelRequestOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

