// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grw/grw.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.grw;

@kotlin.jvm.JvmName("-initializegetLeaderboardResponse")
public inline fun getLeaderboardResponse(block: com.solra.proto.grw.GetLeaderboardResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.GetLeaderboardResponse =
  com.solra.proto.grw.GetLeaderboardResponseKt.Dsl._create(com.solra.proto.grw.Grw.GetLeaderboardResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.grw.GetLeaderboardResponse`
 */
public object GetLeaderboardResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.grw.Grw.GetLeaderboardResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.grw.Grw.GetLeaderboardResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.grw.Grw.GetLeaderboardResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val GetLeaderboardResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EntriesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.grw.LeaderboardEntry entries = 2 [json_name = "entries"];`
     */
     public val entries: com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.LeaderboardEntry, EntriesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.entriesList
      )
    /**
     * `repeated .solra.grw.LeaderboardEntry entries = 2 [json_name = "entries"];`
     * @param value The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addEntries")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.LeaderboardEntry, EntriesProxy>.add(value: com.solra.proto.grw.Grw.LeaderboardEntry) {
      _builder.addEntries(value)
    }
    /**
     * `repeated .solra.grw.LeaderboardEntry entries = 2 [json_name = "entries"];`
     * @param value The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignEntries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.LeaderboardEntry, EntriesProxy>.plusAssign(value: com.solra.proto.grw.Grw.LeaderboardEntry) {
      add(value)
    }
    /**
     * `repeated .solra.grw.LeaderboardEntry entries = 2 [json_name = "entries"];`
     * @param values The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllEntries")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.LeaderboardEntry, EntriesProxy>.addAll(values: kotlin.collections.Iterable<com.solra.proto.grw.Grw.LeaderboardEntry>) {
      _builder.addAllEntries(values)
    }
    /**
     * `repeated .solra.grw.LeaderboardEntry entries = 2 [json_name = "entries"];`
     * @param values The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllEntries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.LeaderboardEntry, EntriesProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.proto.grw.Grw.LeaderboardEntry>) {
      addAll(values)
    }
    /**
     * `repeated .solra.grw.LeaderboardEntry entries = 2 [json_name = "entries"];`
     * @param index The index to set the value at.
     * @param value The entries to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEntries")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.LeaderboardEntry, EntriesProxy>.set(index: kotlin.Int, value: com.solra.proto.grw.Grw.LeaderboardEntry) {
      _builder.setEntries(index, value)
    }
    /**
     * `repeated .solra.grw.LeaderboardEntry entries = 2 [json_name = "entries"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearEntries")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.LeaderboardEntry, EntriesProxy>.clear() {
      _builder.clearEntries()
    }

    /**
     * `.solra.common.PageResponse page = 3 [json_name = "page"];`
     */
    public var page: com.solra.apis.common.Common.PageResponse
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * `.solra.common.PageResponse page = 3 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * `.solra.common.PageResponse page = 3 [json_name = "page"];`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }

    public val GetLeaderboardResponseKt.Dsl.pageOrNull: com.solra.apis.common.Common.PageResponse?
      get() = _builder.pageOrNull

    /**
     * `int32 user_rank = 4 [json_name = "userRank"];`
     */
    public var userRank: kotlin.Int
      @kotlin.jvm.JvmName("getUserRank")
        get() = _builder.userRank
      @kotlin.jvm.JvmName("setUserRank")
        set(value) {
        _builder.userRank = value
      }
    /**
     * `int32 user_rank = 4 [json_name = "userRank"];`
     */
    public fun clearUserRank() {
      _builder.clearUserRank()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.grw.Grw.GetLeaderboardResponse.copy(block: `com.solra.proto.grw`.GetLeaderboardResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.GetLeaderboardResponse =
  `com.solra.proto.grw`.GetLeaderboardResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.grw.Grw.GetLeaderboardResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

public val com.solra.proto.grw.Grw.GetLeaderboardResponseOrBuilder.pageOrNull: com.solra.apis.common.Common.PageResponse?
  get() = if (hasPage()) getPage() else null

