// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/grw/grw.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.grw;

@kotlin.jvm.JvmName("-initializelistAchievementsRequest")
public inline fun listAchievementsRequest(block: com.solra.proto.grw.ListAchievementsRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.ListAchievementsRequest =
  com.solra.proto.grw.ListAchievementsRequestKt.Dsl._create(com.solra.proto.grw.Grw.ListAchievementsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.grw.ListAchievementsRequest`
 */
public object ListAchievementsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.grw.Grw.ListAchievementsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.grw.Grw.ListAchievementsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.grw.Grw.ListAchievementsRequest = _builder.build()

    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val ListAchievementsRequestKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `.solra.grw.AchievementCategory category = 2 [json_name = "category"];`
     */
    public var category: com.solra.proto.grw.Grw.AchievementCategory
      @kotlin.jvm.JvmName("getCategory")
        get() = _builder.category
      @kotlin.jvm.JvmName("setCategory")
        set(value) {
        _builder.category = value
      }
    public var categoryValue: kotlin.Int
      @kotlin.jvm.JvmName("getCategoryValue")
        get() = _builder.categoryValue
      @kotlin.jvm.JvmName("setCategoryValue")
        set(value) {
        _builder.categoryValue = value
      }
    /**
     * `.solra.grw.AchievementCategory category = 2 [json_name = "category"];`
     */
    public fun clearCategory() {
      _builder.clearCategory()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.grw.Grw.ListAchievementsRequest.copy(block: `com.solra.proto.grw`.ListAchievementsRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.ListAchievementsRequest =
  `com.solra.proto.grw`.ListAchievementsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.grw.Grw.ListAchievementsRequestOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

