// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grw/grw.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.grw;

@kotlin.jvm.JvmName("-initializeuserProfile")
public inline fun userProfile(block: com.solra.proto.grw.UserProfileKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.UserProfile =
  com.solra.proto.grw.UserProfileKt.Dsl._create(com.solra.proto.grw.Grw.UserProfile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.grw.UserProfile`
 */
public object UserProfileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.grw.Grw.UserProfile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.grw.Grw.UserProfile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.grw.Grw.UserProfile = _builder.build()

    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val UserProfileKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `string display_name = 2 [json_name = "displayName"];`
     */
    public var displayName: kotlin.String
      @kotlin.jvm.JvmName("getDisplayName")
        get() = _builder.displayName
      @kotlin.jvm.JvmName("setDisplayName")
        set(value) {
        _builder.displayName = value
      }
    /**
     * `string display_name = 2 [json_name = "displayName"];`
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }

    /**
     * `string avatar_url = 3 [json_name = "avatarUrl"];`
     */
    public var avatarUrl: kotlin.String
      @kotlin.jvm.JvmName("getAvatarUrl")
        get() = _builder.avatarUrl
      @kotlin.jvm.JvmName("setAvatarUrl")
        set(value) {
        _builder.avatarUrl = value
      }
    /**
     * `string avatar_url = 3 [json_name = "avatarUrl"];`
     */
    public fun clearAvatarUrl() {
      _builder.clearAvatarUrl()
    }

    /**
     * `string bio = 4 [json_name = "bio"];`
     */
    public var bio: kotlin.String
      @kotlin.jvm.JvmName("getBio")
        get() = _builder.bio
      @kotlin.jvm.JvmName("setBio")
        set(value) {
        _builder.bio = value
      }
    /**
     * `string bio = 4 [json_name = "bio"];`
     */
    public fun clearBio() {
      _builder.clearBio()
    }

    /**
     * `.solra.common.SolraTimestamp created_at = 5 [json_name = "createdAt"];`
     */
    public var createdAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `.solra.common.SolraTimestamp created_at = 5 [json_name = "createdAt"];`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * `.solra.common.SolraTimestamp created_at = 5 [json_name = "createdAt"];`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    public val UserProfileKt.Dsl.createdAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.createdAtOrNull

    /**
     * `.solra.common.SolraTimestamp last_active_at = 6 [json_name = "lastActiveAt"];`
     */
    public var lastActiveAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getLastActiveAt")
        get() = _builder.lastActiveAt
      @kotlin.jvm.JvmName("setLastActiveAt")
        set(value) {
        _builder.lastActiveAt = value
      }
    /**
     * `.solra.common.SolraTimestamp last_active_at = 6 [json_name = "lastActiveAt"];`
     */
    public fun clearLastActiveAt() {
      _builder.clearLastActiveAt()
    }
    /**
     * `.solra.common.SolraTimestamp last_active_at = 6 [json_name = "lastActiveAt"];`
     * @return Whether the lastActiveAt field is set.
     */
    public fun hasLastActiveAt(): kotlin.Boolean {
      return _builder.hasLastActiveAt()
    }

    public val UserProfileKt.Dsl.lastActiveAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.lastActiveAtOrNull

    /**
     * `.solra.grw.FaithLevel faith_level = 7 [json_name = "faithLevel"];`
     */
    public var faithLevel: com.solra.proto.grw.Grw.FaithLevel
      @kotlin.jvm.JvmName("getFaithLevel")
        get() = _builder.faithLevel
      @kotlin.jvm.JvmName("setFaithLevel")
        set(value) {
        _builder.faithLevel = value
      }
    /**
     * `.solra.grw.FaithLevel faith_level = 7 [json_name = "faithLevel"];`
     */
    public fun clearFaithLevel() {
      _builder.clearFaithLevel()
    }
    /**
     * `.solra.grw.FaithLevel faith_level = 7 [json_name = "faithLevel"];`
     * @return Whether the faithLevel field is set.
     */
    public fun hasFaithLevel(): kotlin.Boolean {
      return _builder.hasFaithLevel()
    }

    public val UserProfileKt.Dsl.faithLevelOrNull: com.solra.proto.grw.Grw.FaithLevel?
      get() = _builder.faithLevelOrNull

    /**
     * `.solra.grw.ProfileStats stats = 8 [json_name = "stats"];`
     */
    public var stats: com.solra.proto.grw.Grw.ProfileStats
      @kotlin.jvm.JvmName("getStats")
        get() = _builder.stats
      @kotlin.jvm.JvmName("setStats")
        set(value) {
        _builder.stats = value
      }
    /**
     * `.solra.grw.ProfileStats stats = 8 [json_name = "stats"];`
     */
    public fun clearStats() {
      _builder.clearStats()
    }
    /**
     * `.solra.grw.ProfileStats stats = 8 [json_name = "stats"];`
     * @return Whether the stats field is set.
     */
    public fun hasStats(): kotlin.Boolean {
      return _builder.hasStats()
    }

    public val UserProfileKt.Dsl.statsOrNull: com.solra.proto.grw.Grw.ProfileStats?
      get() = _builder.statsOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AchievementsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.grw.Achievement achievements = 9 [json_name = "achievements"];`
     */
     public val achievements: com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.Achievement, AchievementsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.achievementsList
      )
    /**
     * `repeated .solra.grw.Achievement achievements = 9 [json_name = "achievements"];`
     * @param value The achievements to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAchievements")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.Achievement, AchievementsProxy>.add(value: com.solra.proto.grw.Grw.Achievement) {
      _builder.addAchievements(value)
    }
    /**
     * `repeated .solra.grw.Achievement achievements = 9 [json_name = "achievements"];`
     * @param value The achievements to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAchievements")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.Achievement, AchievementsProxy>.plusAssign(value: com.solra.proto.grw.Grw.Achievement) {
      add(value)
    }
    /**
     * `repeated .solra.grw.Achievement achievements = 9 [json_name = "achievements"];`
     * @param values The achievements to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAchievements")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.Achievement, AchievementsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.proto.grw.Grw.Achievement>) {
      _builder.addAllAchievements(values)
    }
    /**
     * `repeated .solra.grw.Achievement achievements = 9 [json_name = "achievements"];`
     * @param values The achievements to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAchievements")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.Achievement, AchievementsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.proto.grw.Grw.Achievement>) {
      addAll(values)
    }
    /**
     * `repeated .solra.grw.Achievement achievements = 9 [json_name = "achievements"];`
     * @param index The index to set the value at.
     * @param value The achievements to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAchievements")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.Achievement, AchievementsProxy>.set(index: kotlin.Int, value: com.solra.proto.grw.Grw.Achievement) {
      _builder.setAchievements(index, value)
    }
    /**
     * `repeated .solra.grw.Achievement achievements = 9 [json_name = "achievements"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearAchievements")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.grw.Grw.Achievement, AchievementsProxy>.clear() {
      _builder.clearAchievements()
    }

    /**
     * `.solra.grw.BadgeCollection badges = 10 [json_name = "badges"];`
     */
    public var badges: com.solra.proto.grw.Grw.BadgeCollection
      @kotlin.jvm.JvmName("getBadges")
        get() = _builder.badges
      @kotlin.jvm.JvmName("setBadges")
        set(value) {
        _builder.badges = value
      }
    /**
     * `.solra.grw.BadgeCollection badges = 10 [json_name = "badges"];`
     */
    public fun clearBadges() {
      _builder.clearBadges()
    }
    /**
     * `.solra.grw.BadgeCollection badges = 10 [json_name = "badges"];`
     * @return Whether the badges field is set.
     */
    public fun hasBadges(): kotlin.Boolean {
      return _builder.hasBadges()
    }

    public val UserProfileKt.Dsl.badgesOrNull: com.solra.proto.grw.Grw.BadgeCollection?
      get() = _builder.badgesOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.grw.Grw.UserProfile.copy(block: `com.solra.proto.grw`.UserProfileKt.Dsl.() -> kotlin.Unit): com.solra.proto.grw.Grw.UserProfile =
  `com.solra.proto.grw`.UserProfileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.grw.Grw.UserProfileOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

public val com.solra.proto.grw.Grw.UserProfileOrBuilder.createdAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

public val com.solra.proto.grw.Grw.UserProfileOrBuilder.lastActiveAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasLastActiveAt()) getLastActiveAt() else null

public val com.solra.proto.grw.Grw.UserProfileOrBuilder.faithLevelOrNull: com.solra.proto.grw.Grw.FaithLevel?
  get() = if (hasFaithLevel()) getFaithLevel() else null

public val com.solra.proto.grw.Grw.UserProfileOrBuilder.statsOrNull: com.solra.proto.grw.Grw.ProfileStats?
  get() = if (hasStats()) getStats() else null

public val com.solra.proto.grw.Grw.UserProfileOrBuilder.badgesOrNull: com.solra.proto.grw.Grw.BadgeCollection?
  get() = if (hasBadges()) getBadges() else null

