// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/soc/soc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.soc;

@kotlin.jvm.JvmName("-initializeanimationState")
public inline fun animationState(block: com.solra.proto.soc.AnimationStateKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.AnimationState =
  com.solra.proto.soc.AnimationStateKt.Dsl._create(com.solra.proto.soc.Soc.AnimationState.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.soc.AnimationState`
 */
public object AnimationStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.soc.Soc.AnimationState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.soc.Soc.AnimationState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.soc.Soc.AnimationState = _builder.build()

    /**
     * `string current_animation_id = 1 [json_name = "currentAnimationId"];`
     */
    public var currentAnimationId: kotlin.String
      @kotlin.jvm.JvmName("getCurrentAnimationId")
        get() = _builder.currentAnimationId
      @kotlin.jvm.JvmName("setCurrentAnimationId")
        set(value) {
        _builder.currentAnimationId = value
      }
    /**
     * `string current_animation_id = 1 [json_name = "currentAnimationId"];`
     */
    public fun clearCurrentAnimationId() {
      _builder.clearCurrentAnimationId()
    }

    /**
     * ```
     * 当前播放位置(秒)
     * ```
     *
     * `float playhead_time = 2 [json_name = "playheadTime"];`
     */
    public var playheadTime: kotlin.Float
      @kotlin.jvm.JvmName("getPlayheadTime")
        get() = _builder.playheadTime
      @kotlin.jvm.JvmName("setPlayheadTime")
        set(value) {
        _builder.playheadTime = value
      }
    /**
     * ```
     * 当前播放位置(秒)
     * ```
     *
     * `float playhead_time = 2 [json_name = "playheadTime"];`
     */
    public fun clearPlayheadTime() {
      _builder.clearPlayheadTime()
    }

    /**
     * `float speed = 3 [json_name = "speed"];`
     */
    public var speed: kotlin.Float
      @kotlin.jvm.JvmName("getSpeed")
        get() = _builder.speed
      @kotlin.jvm.JvmName("setSpeed")
        set(value) {
        _builder.speed = value
      }
    /**
     * `float speed = 3 [json_name = "speed"];`
     */
    public fun clearSpeed() {
      _builder.clearSpeed()
    }

    /**
     * `float blend_weight = 4 [json_name = "blendWeight"];`
     */
    public var blendWeight: kotlin.Float
      @kotlin.jvm.JvmName("getBlendWeight")
        get() = _builder.blendWeight
      @kotlin.jvm.JvmName("setBlendWeight")
        set(value) {
        _builder.blendWeight = value
      }
    /**
     * `float blend_weight = 4 [json_name = "blendWeight"];`
     */
    public fun clearBlendWeight() {
      _builder.clearBlendWeight()
    }

    /**
     * `bool loop = 5 [json_name = "loop"];`
     */
    public var loop: kotlin.Boolean
      @kotlin.jvm.JvmName("getLoop")
        get() = _builder.loop
      @kotlin.jvm.JvmName("setLoop")
        set(value) {
        _builder.loop = value
      }
    /**
     * `bool loop = 5 [json_name = "loop"];`
     */
    public fun clearLoop() {
      _builder.clearLoop()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.soc.Soc.AnimationState.copy(block: `com.solra.proto.soc`.AnimationStateKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.AnimationState =
  `com.solra.proto.soc`.AnimationStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

