// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: soc/soc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.soc;

@kotlin.jvm.JvmName("-initializeendSessionRequest")
public inline fun endSessionRequest(block: com.solra.proto.soc.EndSessionRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.EndSessionRequest =
  com.solra.proto.soc.EndSessionRequestKt.Dsl._create(com.solra.proto.soc.Soc.EndSessionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.soc.EndSessionRequest`
 */
public object EndSessionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.soc.Soc.EndSessionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.soc.Soc.EndSessionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.soc.Soc.EndSessionRequest = _builder.build()

    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.soc.Soc.EndSessionRequest.copy(block: `com.solra.proto.soc`.EndSessionRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.EndSessionRequest =
  `com.solra.proto.soc`.EndSessionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

