// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: soc/soc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.soc;

@kotlin.jvm.JvmName("-initializeinviteToSessionResponse")
public inline fun inviteToSessionResponse(block: com.solra.proto.soc.InviteToSessionResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.InviteToSessionResponse =
  com.solra.proto.soc.InviteToSessionResponseKt.Dsl._create(com.solra.proto.soc.Soc.InviteToSessionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.soc.InviteToSessionResponse`
 */
public object InviteToSessionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.soc.Soc.InviteToSessionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.soc.Soc.InviteToSessionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.soc.Soc.InviteToSessionResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val InviteToSessionResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.soc.Soc.InviteToSessionResponse.copy(block: `com.solra.proto.soc`.InviteToSessionResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.InviteToSessionResponse =
  `com.solra.proto.soc`.InviteToSessionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.soc.Soc.InviteToSessionResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

