// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: soc/soc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.soc;

@kotlin.jvm.JvmName("-initializelistFollowersResponse")
public inline fun listFollowersResponse(block: com.solra.proto.soc.ListFollowersResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.ListFollowersResponse =
  com.solra.proto.soc.ListFollowersResponseKt.Dsl._create(com.solra.proto.soc.Soc.ListFollowersResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.soc.ListFollowersResponse`
 */
public object ListFollowersResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.soc.Soc.ListFollowersResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.soc.Soc.ListFollowersResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.soc.Soc.ListFollowersResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val ListFollowersResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UserIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.common.UserId user_ids = 2 [json_name = "userIds"];`
     */
     public val userIds: com.google.protobuf.kotlin.DslList<com.solra.apis.common.Common.UserId, UserIdsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.userIdsList
      )
    /**
     * `repeated .solra.common.UserId user_ids = 2 [json_name = "userIds"];`
     * @param value The userIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addUserIds")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.common.Common.UserId, UserIdsProxy>.add(value: com.solra.apis.common.Common.UserId) {
      _builder.addUserIds(value)
    }
    /**
     * `repeated .solra.common.UserId user_ids = 2 [json_name = "userIds"];`
     * @param value The userIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignUserIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.common.Common.UserId, UserIdsProxy>.plusAssign(value: com.solra.apis.common.Common.UserId) {
      add(value)
    }
    /**
     * `repeated .solra.common.UserId user_ids = 2 [json_name = "userIds"];`
     * @param values The userIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllUserIds")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.common.Common.UserId, UserIdsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.common.Common.UserId>) {
      _builder.addAllUserIds(values)
    }
    /**
     * `repeated .solra.common.UserId user_ids = 2 [json_name = "userIds"];`
     * @param values The userIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllUserIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.common.Common.UserId, UserIdsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.common.Common.UserId>) {
      addAll(values)
    }
    /**
     * `repeated .solra.common.UserId user_ids = 2 [json_name = "userIds"];`
     * @param index The index to set the value at.
     * @param value The userIds to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setUserIds")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.common.Common.UserId, UserIdsProxy>.set(index: kotlin.Int, value: com.solra.apis.common.Common.UserId) {
      _builder.setUserIds(index, value)
    }
    /**
     * `repeated .solra.common.UserId user_ids = 2 [json_name = "userIds"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearUserIds")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.common.Common.UserId, UserIdsProxy>.clear() {
      _builder.clearUserIds()
    }

    /**
     * `.solra.common.PageResponse page = 3 [json_name = "page"];`
     */
    public var page: com.solra.apis.common.Common.PageResponse
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * `.solra.common.PageResponse page = 3 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * `.solra.common.PageResponse page = 3 [json_name = "page"];`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }

    public val ListFollowersResponseKt.Dsl.pageOrNull: com.solra.apis.common.Common.PageResponse?
      get() = _builder.pageOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.soc.Soc.ListFollowersResponse.copy(block: `com.solra.proto.soc`.ListFollowersResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.ListFollowersResponse =
  `com.solra.proto.soc`.ListFollowersResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.soc.Soc.ListFollowersResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

public val com.solra.proto.soc.Soc.ListFollowersResponseOrBuilder.pageOrNull: com.solra.apis.common.Common.PageResponse?
  get() = if (hasPage()) getPage() else null

