// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/soc/soc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.soc;

@kotlin.jvm.JvmName("-initializepresenceUpdate")
public inline fun presenceUpdate(block: com.solra.proto.soc.PresenceUpdateKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.PresenceUpdate =
  com.solra.proto.soc.PresenceUpdateKt.Dsl._create(com.solra.proto.soc.Soc.PresenceUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.soc.PresenceUpdate`
 */
public object PresenceUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.soc.Soc.PresenceUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.soc.Soc.PresenceUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.soc.Soc.PresenceUpdate = _builder.build()

    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParticipantsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.soc.Participant participants = 2 [json_name = "participants"];`
     */
     public val participants: com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.participantsList
      )
    /**
     * `repeated .solra.soc.Participant participants = 2 [json_name = "participants"];`
     * @param value The participants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addParticipants")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.add(value: com.solra.proto.soc.Soc.Participant) {
      _builder.addParticipants(value)
    }
    /**
     * `repeated .solra.soc.Participant participants = 2 [json_name = "participants"];`
     * @param value The participants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignParticipants")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.plusAssign(value: com.solra.proto.soc.Soc.Participant) {
      add(value)
    }
    /**
     * `repeated .solra.soc.Participant participants = 2 [json_name = "participants"];`
     * @param values The participants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllParticipants")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.proto.soc.Soc.Participant>) {
      _builder.addAllParticipants(values)
    }
    /**
     * `repeated .solra.soc.Participant participants = 2 [json_name = "participants"];`
     * @param values The participants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllParticipants")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.proto.soc.Soc.Participant>) {
      addAll(values)
    }
    /**
     * `repeated .solra.soc.Participant participants = 2 [json_name = "participants"];`
     * @param index The index to set the value at.
     * @param value The participants to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setParticipants")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.set(index: kotlin.Int, value: com.solra.proto.soc.Soc.Participant) {
      _builder.setParticipants(index, value)
    }
    /**
     * `repeated .solra.soc.Participant participants = 2 [json_name = "participants"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearParticipants")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.clear() {
      _builder.clearParticipants()
    }

    /**
     * `int64 sequence_number = 3 [json_name = "sequenceNumber"];`
     */
    public var sequenceNumber: kotlin.Long
      @kotlin.jvm.JvmName("getSequenceNumber")
        get() = _builder.sequenceNumber
      @kotlin.jvm.JvmName("setSequenceNumber")
        set(value) {
        _builder.sequenceNumber = value
      }
    /**
     * `int64 sequence_number = 3 [json_name = "sequenceNumber"];`
     */
    public fun clearSequenceNumber() {
      _builder.clearSequenceNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.soc.Soc.PresenceUpdate.copy(block: `com.solra.proto.soc`.PresenceUpdateKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.PresenceUpdate =
  `com.solra.proto.soc`.PresenceUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

