// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: soc/soc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.soc;

@kotlin.jvm.JvmName("-initializesession")
public inline fun session(block: com.solra.proto.soc.SessionKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.Session =
  com.solra.proto.soc.SessionKt.Dsl._create(com.solra.proto.soc.Soc.Session.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.soc.Session`
 */
public object SessionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.soc.Soc.Session.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.soc.Soc.Session.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.soc.Soc.Session = _builder.build()

    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `.solra.common.SpaceId space_id = 2 [json_name = "spaceId"];`
     */
    public var spaceId: com.solra.apis.common.Common.SpaceId
      @kotlin.jvm.JvmName("getSpaceId")
        get() = _builder.spaceId
      @kotlin.jvm.JvmName("setSpaceId")
        set(value) {
        _builder.spaceId = value
      }
    /**
     * `.solra.common.SpaceId space_id = 2 [json_name = "spaceId"];`
     */
    public fun clearSpaceId() {
      _builder.clearSpaceId()
    }
    /**
     * `.solra.common.SpaceId space_id = 2 [json_name = "spaceId"];`
     * @return Whether the spaceId field is set.
     */
    public fun hasSpaceId(): kotlin.Boolean {
      return _builder.hasSpaceId()
    }

    public val SessionKt.Dsl.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
      get() = _builder.spaceIdOrNull

    /**
     * `.solra.soc.SessionType type = 3 [json_name = "type"];`
     */
    public var type: com.solra.proto.soc.Soc.SessionType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * `.solra.soc.SessionType type = 3 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `.solra.soc.SessionStatus status = 4 [json_name = "status"];`
     */
    public var status: com.solra.proto.soc.Soc.SessionStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.solra.soc.SessionStatus status = 4 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParticipantsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.soc.Participant participants = 5 [json_name = "participants"];`
     */
     public val participants: com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.participantsList
      )
    /**
     * `repeated .solra.soc.Participant participants = 5 [json_name = "participants"];`
     * @param value The participants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addParticipants")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.add(value: com.solra.proto.soc.Soc.Participant) {
      _builder.addParticipants(value)
    }
    /**
     * `repeated .solra.soc.Participant participants = 5 [json_name = "participants"];`
     * @param value The participants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignParticipants")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.plusAssign(value: com.solra.proto.soc.Soc.Participant) {
      add(value)
    }
    /**
     * `repeated .solra.soc.Participant participants = 5 [json_name = "participants"];`
     * @param values The participants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllParticipants")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.proto.soc.Soc.Participant>) {
      _builder.addAllParticipants(values)
    }
    /**
     * `repeated .solra.soc.Participant participants = 5 [json_name = "participants"];`
     * @param values The participants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllParticipants")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.proto.soc.Soc.Participant>) {
      addAll(values)
    }
    /**
     * `repeated .solra.soc.Participant participants = 5 [json_name = "participants"];`
     * @param index The index to set the value at.
     * @param value The participants to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setParticipants")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.set(index: kotlin.Int, value: com.solra.proto.soc.Soc.Participant) {
      _builder.setParticipants(index, value)
    }
    /**
     * `repeated .solra.soc.Participant participants = 5 [json_name = "participants"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearParticipants")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.soc.Soc.Participant, ParticipantsProxy>.clear() {
      _builder.clearParticipants()
    }

    /**
     * `int32 max_participants = 6 [json_name = "maxParticipants"];`
     */
    public var maxParticipants: kotlin.Int
      @kotlin.jvm.JvmName("getMaxParticipants")
        get() = _builder.maxParticipants
      @kotlin.jvm.JvmName("setMaxParticipants")
        set(value) {
        _builder.maxParticipants = value
      }
    /**
     * `int32 max_participants = 6 [json_name = "maxParticipants"];`
     */
    public fun clearMaxParticipants() {
      _builder.clearMaxParticipants()
    }

    /**
     * `.solra.common.UserId host_id = 7 [json_name = "hostId"];`
     */
    public var hostId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getHostId")
        get() = _builder.hostId
      @kotlin.jvm.JvmName("setHostId")
        set(value) {
        _builder.hostId = value
      }
    /**
     * `.solra.common.UserId host_id = 7 [json_name = "hostId"];`
     */
    public fun clearHostId() {
      _builder.clearHostId()
    }
    /**
     * `.solra.common.UserId host_id = 7 [json_name = "hostId"];`
     * @return Whether the hostId field is set.
     */
    public fun hasHostId(): kotlin.Boolean {
      return _builder.hasHostId()
    }

    public val SessionKt.Dsl.hostIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.hostIdOrNull

    /**
     * `.solra.common.SolraTimestamp started_at = 8 [json_name = "startedAt"];`
     */
    public var startedAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getStartedAt")
        get() = _builder.startedAt
      @kotlin.jvm.JvmName("setStartedAt")
        set(value) {
        _builder.startedAt = value
      }
    /**
     * `.solra.common.SolraTimestamp started_at = 8 [json_name = "startedAt"];`
     */
    public fun clearStartedAt() {
      _builder.clearStartedAt()
    }
    /**
     * `.solra.common.SolraTimestamp started_at = 8 [json_name = "startedAt"];`
     * @return Whether the startedAt field is set.
     */
    public fun hasStartedAt(): kotlin.Boolean {
      return _builder.hasStartedAt()
    }

    public val SessionKt.Dsl.startedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.startedAtOrNull

    /**
     * `.solra.common.SolraTimestamp ended_at = 9 [json_name = "endedAt"];`
     */
    public var endedAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getEndedAt")
        get() = _builder.endedAt
      @kotlin.jvm.JvmName("setEndedAt")
        set(value) {
        _builder.endedAt = value
      }
    /**
     * `.solra.common.SolraTimestamp ended_at = 9 [json_name = "endedAt"];`
     */
    public fun clearEndedAt() {
      _builder.clearEndedAt()
    }
    /**
     * `.solra.common.SolraTimestamp ended_at = 9 [json_name = "endedAt"];`
     * @return Whether the endedAt field is set.
     */
    public fun hasEndedAt(): kotlin.Boolean {
      return _builder.hasEndedAt()
    }

    public val SessionKt.Dsl.endedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.endedAtOrNull

    /**
     * `.solra.soc.SessionConfig config = 10 [json_name = "config"];`
     */
    public var config: com.solra.proto.soc.Soc.SessionConfig
      @kotlin.jvm.JvmName("getConfig")
        get() = _builder.config
      @kotlin.jvm.JvmName("setConfig")
        set(value) {
        _builder.config = value
      }
    /**
     * `.solra.soc.SessionConfig config = 10 [json_name = "config"];`
     */
    public fun clearConfig() {
      _builder.clearConfig()
    }
    /**
     * `.solra.soc.SessionConfig config = 10 [json_name = "config"];`
     * @return Whether the config field is set.
     */
    public fun hasConfig(): kotlin.Boolean {
      return _builder.hasConfig()
    }

    public val SessionKt.Dsl.configOrNull: com.solra.proto.soc.Soc.SessionConfig?
      get() = _builder.configOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.soc.Soc.Session.copy(block: `com.solra.proto.soc`.SessionKt.Dsl.() -> kotlin.Unit): com.solra.proto.soc.Soc.Session =
  `com.solra.proto.soc`.SessionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.soc.Soc.SessionOrBuilder.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
  get() = if (hasSpaceId()) getSpaceId() else null

public val com.solra.proto.soc.Soc.SessionOrBuilder.hostIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasHostId()) getHostId() else null

public val com.solra.proto.soc.Soc.SessionOrBuilder.startedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasStartedAt()) getStartedAt() else null

public val com.solra.proto.soc.Soc.SessionOrBuilder.endedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasEndedAt()) getEndedAt() else null

public val com.solra.proto.soc.Soc.SessionOrBuilder.configOrNull: com.solra.proto.soc.Soc.SessionConfig?
  get() = if (hasConfig()) getConfig() else null

