// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializeassetChunk")
public inline fun assetChunk(block: com.solra.apis.spc.v1.AssetChunkKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.AssetChunk =
  com.solra.apis.spc.v1.AssetChunkKt.Dsl._create(com.solra.apis.spc.v1.Spc.AssetChunk.newBuilder()).apply { block() }._build()
/**
 * ```
 * AssetChunk 资产分块
 * ```
 *
 * Protobuf type `solra.spc.v1.AssetChunk`
 */
public object AssetChunkKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.AssetChunk.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.AssetChunk.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.AssetChunk = _builder.build()

    /**
     * `.solra.common.AssetId asset_id = 1 [json_name = "assetId"];`
     */
    public var assetId: com.solra.apis.common.Common.AssetId
      @kotlin.jvm.JvmName("getAssetId")
        get() = _builder.assetId
      @kotlin.jvm.JvmName("setAssetId")
        set(value) {
        _builder.assetId = value
      }
    /**
     * `.solra.common.AssetId asset_id = 1 [json_name = "assetId"];`
     */
    public fun clearAssetId() {
      _builder.clearAssetId()
    }
    /**
     * `.solra.common.AssetId asset_id = 1 [json_name = "assetId"];`
     * @return Whether the assetId field is set.
     */
    public fun hasAssetId(): kotlin.Boolean {
      return _builder.hasAssetId()
    }

    public val AssetChunkKt.Dsl.assetIdOrNull: com.solra.apis.common.Common.AssetId?
      get() = _builder.assetIdOrNull

    /**
     * ```
     * 块序号（从0开始）
     * ```
     *
     * `int32 chunk_index = 2 [json_name = "chunkIndex"];`
     */
    public var chunkIndex: kotlin.Int
      @kotlin.jvm.JvmName("getChunkIndex")
        get() = _builder.chunkIndex
      @kotlin.jvm.JvmName("setChunkIndex")
        set(value) {
        _builder.chunkIndex = value
      }
    /**
     * ```
     * 块序号（从0开始）
     * ```
     *
     * `int32 chunk_index = 2 [json_name = "chunkIndex"];`
     */
    public fun clearChunkIndex() {
      _builder.clearChunkIndex()
    }

    /**
     * ```
     * 总块数
     * ```
     *
     * `int32 total_chunks = 3 [json_name = "totalChunks"];`
     */
    public var totalChunks: kotlin.Int
      @kotlin.jvm.JvmName("getTotalChunks")
        get() = _builder.totalChunks
      @kotlin.jvm.JvmName("setTotalChunks")
        set(value) {
        _builder.totalChunks = value
      }
    /**
     * ```
     * 总块数
     * ```
     *
     * `int32 total_chunks = 3 [json_name = "totalChunks"];`
     */
    public fun clearTotalChunks() {
      _builder.clearTotalChunks()
    }

    /**
     * ```
     * 块数据
     * ```
     *
     * `bytes data = 4 [json_name = "data"];`
     */
    public var data: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getData")
        get() = _builder.data
      @kotlin.jvm.JvmName("setData")
        set(value) {
        _builder.data = value
      }
    /**
     * ```
     * 块数据
     * ```
     *
     * `bytes data = 4 [json_name = "data"];`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * ```
     * 是否最后一块
     * ```
     *
     * `bool is_final = 5 [json_name = "isFinal"];`
     */
    public var isFinal: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsFinal")
        get() = _builder.isFinal
      @kotlin.jvm.JvmName("setIsFinal")
        set(value) {
        _builder.isFinal = value
      }
    /**
     * ```
     * 是否最后一块
     * ```
     *
     * `bool is_final = 5 [json_name = "isFinal"];`
     */
    public fun clearIsFinal() {
      _builder.clearIsFinal()
    }

    /**
     * ```
     * 压缩等级
     * ```
     *
     * `int32 compression_level = 6 [json_name = "compressionLevel"];`
     */
    public var compressionLevel: kotlin.Int
      @kotlin.jvm.JvmName("getCompressionLevel")
        get() = _builder.compressionLevel
      @kotlin.jvm.JvmName("setCompressionLevel")
        set(value) {
        _builder.compressionLevel = value
      }
    /**
     * ```
     * 压缩等级
     * ```
     *
     * `int32 compression_level = 6 [json_name = "compressionLevel"];`
     */
    public fun clearCompressionLevel() {
      _builder.clearCompressionLevel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.AssetChunk.copy(block: `com.solra.apis.spc.v1`.AssetChunkKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.AssetChunk =
  `com.solra.apis.spc.v1`.AssetChunkKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.AssetChunkOrBuilder.assetIdOrNull: com.solra.apis.common.Common.AssetId?
  get() = if (hasAssetId()) getAssetId() else null

