// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spc/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializebatchGetPreviewCardsResponse")
public inline fun batchGetPreviewCardsResponse(block: com.solra.apis.spc.v1.BatchGetPreviewCardsResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.BatchGetPreviewCardsResponse =
  com.solra.apis.spc.v1.BatchGetPreviewCardsResponseKt.Dsl._create(com.solra.apis.spc.v1.Spc.BatchGetPreviewCardsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.BatchGetPreviewCardsResponse`
 */
public object BatchGetPreviewCardsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.BatchGetPreviewCardsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.BatchGetPreviewCardsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.BatchGetPreviewCardsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CardsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 1 [json_name = "cards"];`
     */
     public val cards: com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.cardsList
      )
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 1 [json_name = "cards"];`
     * @param value The cards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addCards")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.add(value: com.solra.apis.spc.v1.Spc.PreviewCard) {
      _builder.addCards(value)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 1 [json_name = "cards"];`
     * @param value The cards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignCards")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.plusAssign(value: com.solra.apis.spc.v1.Spc.PreviewCard) {
      add(value)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 1 [json_name = "cards"];`
     * @param values The cards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllCards")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.PreviewCard>) {
      _builder.addAllCards(values)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 1 [json_name = "cards"];`
     * @param values The cards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllCards")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.PreviewCard>) {
      addAll(values)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 1 [json_name = "cards"];`
     * @param index The index to set the value at.
     * @param value The cards to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setCards")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.set(index: kotlin.Int, value: com.solra.apis.spc.v1.Spc.PreviewCard) {
      _builder.setCards(index, value)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 1 [json_name = "cards"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearCards")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.clear() {
      _builder.clearCards()
    }

    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val BatchGetPreviewCardsResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.BatchGetPreviewCardsResponse.copy(block: `com.solra.apis.spc.v1`.BatchGetPreviewCardsResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.BatchGetPreviewCardsResponse =
  `com.solra.apis.spc.v1`.BatchGetPreviewCardsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.BatchGetPreviewCardsResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

