// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializebrowseByCategoryResponse")
public inline fun browseByCategoryResponse(block: com.solra.apis.spc.v1.BrowseByCategoryResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.BrowseByCategoryResponse =
  com.solra.apis.spc.v1.BrowseByCategoryResponseKt.Dsl._create(com.solra.apis.spc.v1.Spc.BrowseByCategoryResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.BrowseByCategoryResponse`
 */
public object BrowseByCategoryResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.BrowseByCategoryResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.BrowseByCategoryResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.BrowseByCategoryResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SpacesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.spc.v1.Space spaces = 1 [json_name = "spaces"];`
     */
     public val spaces: com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.Space, SpacesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.spacesList
      )
    /**
     * `repeated .solra.spc.v1.Space spaces = 1 [json_name = "spaces"];`
     * @param value The spaces to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSpaces")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.Space, SpacesProxy>.add(value: com.solra.apis.spc.v1.Spc.Space) {
      _builder.addSpaces(value)
    }
    /**
     * `repeated .solra.spc.v1.Space spaces = 1 [json_name = "spaces"];`
     * @param value The spaces to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSpaces")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.Space, SpacesProxy>.plusAssign(value: com.solra.apis.spc.v1.Spc.Space) {
      add(value)
    }
    /**
     * `repeated .solra.spc.v1.Space spaces = 1 [json_name = "spaces"];`
     * @param values The spaces to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSpaces")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.Space, SpacesProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.Space>) {
      _builder.addAllSpaces(values)
    }
    /**
     * `repeated .solra.spc.v1.Space spaces = 1 [json_name = "spaces"];`
     * @param values The spaces to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSpaces")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.Space, SpacesProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.Space>) {
      addAll(values)
    }
    /**
     * `repeated .solra.spc.v1.Space spaces = 1 [json_name = "spaces"];`
     * @param index The index to set the value at.
     * @param value The spaces to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSpaces")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.Space, SpacesProxy>.set(index: kotlin.Int, value: com.solra.apis.spc.v1.Spc.Space) {
      _builder.setSpaces(index, value)
    }
    /**
     * `repeated .solra.spc.v1.Space spaces = 1 [json_name = "spaces"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSpaces")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.Space, SpacesProxy>.clear() {
      _builder.clearSpaces()
    }

    /**
     * `.solra.common.PageResponse page = 2 [json_name = "page"];`
     */
    public var page: com.solra.apis.common.Common.PageResponse
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * `.solra.common.PageResponse page = 2 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * `.solra.common.PageResponse page = 2 [json_name = "page"];`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }

    public val BrowseByCategoryResponseKt.Dsl.pageOrNull: com.solra.apis.common.Common.PageResponse?
      get() = _builder.pageOrNull

    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val BrowseByCategoryResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.BrowseByCategoryResponse.copy(block: `com.solra.apis.spc.v1`.BrowseByCategoryResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.BrowseByCategoryResponse =
  `com.solra.apis.spc.v1`.BrowseByCategoryResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.BrowseByCategoryResponseOrBuilder.pageOrNull: com.solra.apis.common.Common.PageResponse?
  get() = if (hasPage()) getPage() else null

public val com.solra.apis.spc.v1.Spc.BrowseByCategoryResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

