// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializeexitTransitionDTO")
public inline fun exitTransitionDTO(block: com.solra.apis.spc.v1.ExitTransitionDTOKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.ExitTransitionDTO =
  com.solra.apis.spc.v1.ExitTransitionDTOKt.Dsl._create(com.solra.apis.spc.v1.Spc.ExitTransitionDTO.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.ExitTransitionDTO`
 */
public object ExitTransitionDTOKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.ExitTransitionDTO.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.ExitTransitionDTO.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.ExitTransitionDTO = _builder.build()

    /**
     * `string space_id = 1 [json_name = "spaceId"];`
     */
    public var spaceId: kotlin.String
      @kotlin.jvm.JvmName("getSpaceId")
        get() = _builder.spaceId
      @kotlin.jvm.JvmName("setSpaceId")
        set(value) {
        _builder.spaceId = value
      }
    /**
     * `string space_id = 1 [json_name = "spaceId"];`
     */
    public fun clearSpaceId() {
      _builder.clearSpaceId()
    }

    /**
     * ```
     * FADE_OUT_ZOOM
     * ```
     *
     * `string effect = 2 [json_name = "effect"];`
     */
    public var effect: kotlin.String
      @kotlin.jvm.JvmName("getEffect")
        get() = _builder.effect
      @kotlin.jvm.JvmName("setEffect")
        set(value) {
        _builder.effect = value
      }
    /**
     * ```
     * FADE_OUT_ZOOM
     * ```
     *
     * `string effect = 2 [json_name = "effect"];`
     */
    public fun clearEffect() {
      _builder.clearEffect()
    }

    /**
     * `int32 duration_ms = 3 [json_name = "durationMs"];`
     */
    public var durationMs: kotlin.Int
      @kotlin.jvm.JvmName("getDurationMs")
        get() = _builder.durationMs
      @kotlin.jvm.JvmName("setDurationMs")
        set(value) {
        _builder.durationMs = value
      }
    /**
     * `int32 duration_ms = 3 [json_name = "durationMs"];`
     */
    public fun clearDurationMs() {
      _builder.clearDurationMs()
    }

    /**
     * `string easing = 4 [json_name = "easing"];`
     */
    public var easing: kotlin.String
      @kotlin.jvm.JvmName("getEasing")
        get() = _builder.easing
      @kotlin.jvm.JvmName("setEasing")
        set(value) {
        _builder.easing = value
      }
    /**
     * `string easing = 4 [json_name = "easing"];`
     */
    public fun clearEasing() {
      _builder.clearEasing()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class KeyframesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.spc.v1.TransitionKeyframeDTO keyframes = 5 [json_name = "keyframes"];`
     */
     public val keyframes: com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO, KeyframesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.keyframesList
      )
    /**
     * `repeated .solra.spc.v1.TransitionKeyframeDTO keyframes = 5 [json_name = "keyframes"];`
     * @param value The keyframes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addKeyframes")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO, KeyframesProxy>.add(value: com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO) {
      _builder.addKeyframes(value)
    }
    /**
     * `repeated .solra.spc.v1.TransitionKeyframeDTO keyframes = 5 [json_name = "keyframes"];`
     * @param value The keyframes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignKeyframes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO, KeyframesProxy>.plusAssign(value: com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO) {
      add(value)
    }
    /**
     * `repeated .solra.spc.v1.TransitionKeyframeDTO keyframes = 5 [json_name = "keyframes"];`
     * @param values The keyframes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllKeyframes")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO, KeyframesProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO>) {
      _builder.addAllKeyframes(values)
    }
    /**
     * `repeated .solra.spc.v1.TransitionKeyframeDTO keyframes = 5 [json_name = "keyframes"];`
     * @param values The keyframes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllKeyframes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO, KeyframesProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO>) {
      addAll(values)
    }
    /**
     * `repeated .solra.spc.v1.TransitionKeyframeDTO keyframes = 5 [json_name = "keyframes"];`
     * @param index The index to set the value at.
     * @param value The keyframes to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setKeyframes")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO, KeyframesProxy>.set(index: kotlin.Int, value: com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO) {
      _builder.setKeyframes(index, value)
    }
    /**
     * `repeated .solra.spc.v1.TransitionKeyframeDTO keyframes = 5 [json_name = "keyframes"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearKeyframes")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionKeyframeDTO, KeyframesProxy>.clear() {
      _builder.clearKeyframes()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.ExitTransitionDTO.copy(block: `com.solra.apis.spc.v1`.ExitTransitionDTOKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.ExitTransitionDTO =
  `com.solra.apis.spc.v1`.ExitTransitionDTOKt.Dsl._create(this.toBuilder()).apply { block() }._build()

