// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializegetCdnManifestRequest")
public inline fun getCdnManifestRequest(block: com.solra.apis.spc.v1.GetCdnManifestRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.GetCdnManifestRequest =
  com.solra.apis.spc.v1.GetCdnManifestRequestKt.Dsl._create(com.solra.apis.spc.v1.Spc.GetCdnManifestRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.GetCdnManifestRequest`
 */
public object GetCdnManifestRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.GetCdnManifestRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.GetCdnManifestRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.GetCdnManifestRequest = _builder.build()

    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     */
    public var spaceId: com.solra.apis.common.Common.SpaceId
      @kotlin.jvm.JvmName("getSpaceId")
        get() = _builder.spaceId
      @kotlin.jvm.JvmName("setSpaceId")
        set(value) {
        _builder.spaceId = value
      }
    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     */
    public fun clearSpaceId() {
      _builder.clearSpaceId()
    }
    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     * @return Whether the spaceId field is set.
     */
    public fun hasSpaceId(): kotlin.Boolean {
      return _builder.hasSpaceId()
    }

    public val GetCdnManifestRequestKt.Dsl.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
      get() = _builder.spaceIdOrNull

    /**
     * ```
     * e.g., ap-shanghai, us-west-1
     * ```
     *
     * `string client_region = 2 [json_name = "clientRegion"];`
     */
    public var clientRegion: kotlin.String
      @kotlin.jvm.JvmName("getClientRegion")
        get() = _builder.clientRegion
      @kotlin.jvm.JvmName("setClientRegion")
        set(value) {
        _builder.clientRegion = value
      }
    /**
     * ```
     * e.g., ap-shanghai, us-west-1
     * ```
     *
     * `string client_region = 2 [json_name = "clientRegion"];`
     */
    public fun clearClientRegion() {
      _builder.clearClientRegion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.GetCdnManifestRequest.copy(block: `com.solra.apis.spc.v1`.GetCdnManifestRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.GetCdnManifestRequest =
  `com.solra.apis.spc.v1`.GetCdnManifestRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.GetCdnManifestRequestOrBuilder.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
  get() = if (hasSpaceId()) getSpaceId() else null

