// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spc/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializegetPreviewCardRequest")
public inline fun getPreviewCardRequest(block: com.solra.apis.spc.v1.GetPreviewCardRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.GetPreviewCardRequest =
  com.solra.apis.spc.v1.GetPreviewCardRequestKt.Dsl._create(com.solra.apis.spc.v1.Spc.GetPreviewCardRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * GetPreviewCard
 * ```
 *
 * Protobuf type `solra.spc.v1.GetPreviewCardRequest`
 */
public object GetPreviewCardRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.GetPreviewCardRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.GetPreviewCardRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.GetPreviewCardRequest = _builder.build()

    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     */
    public var spaceId: com.solra.apis.common.Common.SpaceId
      @kotlin.jvm.JvmName("getSpaceId")
        get() = _builder.spaceId
      @kotlin.jvm.JvmName("setSpaceId")
        set(value) {
        _builder.spaceId = value
      }
    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     */
    public fun clearSpaceId() {
      _builder.clearSpaceId()
    }
    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     * @return Whether the spaceId field is set.
     */
    public fun hasSpaceId(): kotlin.Boolean {
      return _builder.hasSpaceId()
    }

    public val GetPreviewCardRequestKt.Dsl.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
      get() = _builder.spaceIdOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.GetPreviewCardRequest.copy(block: `com.solra.apis.spc.v1`.GetPreviewCardRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.GetPreviewCardRequest =
  `com.solra.apis.spc.v1`.GetPreviewCardRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.GetPreviewCardRequestOrBuilder.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
  get() = if (hasSpaceId()) getSpaceId() else null

