// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializegetSearchFacetsRequest")
public inline fun getSearchFacetsRequest(block: com.solra.apis.spc.v1.GetSearchFacetsRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.GetSearchFacetsRequest =
  com.solra.apis.spc.v1.GetSearchFacetsRequestKt.Dsl._create(com.solra.apis.spc.v1.Spc.GetSearchFacetsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.GetSearchFacetsRequest`
 */
public object GetSearchFacetsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.GetSearchFacetsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.GetSearchFacetsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.GetSearchFacetsRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.GetSearchFacetsRequest.copy(block: `com.solra.apis.spc.v1`.GetSearchFacetsRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.GetSearchFacetsRequest =
  `com.solra.apis.spc.v1`.GetSearchFacetsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

