// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializegetTransitionPresetsResponse")
public inline fun getTransitionPresetsResponse(block: com.solra.apis.spc.v1.GetTransitionPresetsResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.GetTransitionPresetsResponse =
  com.solra.apis.spc.v1.GetTransitionPresetsResponseKt.Dsl._create(com.solra.apis.spc.v1.Spc.GetTransitionPresetsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.GetTransitionPresetsResponse`
 */
public object GetTransitionPresetsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.GetTransitionPresetsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.GetTransitionPresetsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.GetTransitionPresetsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PresetsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.spc.v1.TransitionPresetDTO presets = 1 [json_name = "presets"];`
     */
     public val presets: com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionPresetDTO, PresetsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.presetsList
      )
    /**
     * `repeated .solra.spc.v1.TransitionPresetDTO presets = 1 [json_name = "presets"];`
     * @param value The presets to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPresets")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionPresetDTO, PresetsProxy>.add(value: com.solra.apis.spc.v1.Spc.TransitionPresetDTO) {
      _builder.addPresets(value)
    }
    /**
     * `repeated .solra.spc.v1.TransitionPresetDTO presets = 1 [json_name = "presets"];`
     * @param value The presets to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPresets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionPresetDTO, PresetsProxy>.plusAssign(value: com.solra.apis.spc.v1.Spc.TransitionPresetDTO) {
      add(value)
    }
    /**
     * `repeated .solra.spc.v1.TransitionPresetDTO presets = 1 [json_name = "presets"];`
     * @param values The presets to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPresets")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionPresetDTO, PresetsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.TransitionPresetDTO>) {
      _builder.addAllPresets(values)
    }
    /**
     * `repeated .solra.spc.v1.TransitionPresetDTO presets = 1 [json_name = "presets"];`
     * @param values The presets to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPresets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionPresetDTO, PresetsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.TransitionPresetDTO>) {
      addAll(values)
    }
    /**
     * `repeated .solra.spc.v1.TransitionPresetDTO presets = 1 [json_name = "presets"];`
     * @param index The index to set the value at.
     * @param value The presets to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPresets")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionPresetDTO, PresetsProxy>.set(index: kotlin.Int, value: com.solra.apis.spc.v1.Spc.TransitionPresetDTO) {
      _builder.setPresets(index, value)
    }
    /**
     * `repeated .solra.spc.v1.TransitionPresetDTO presets = 1 [json_name = "presets"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearPresets")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.TransitionPresetDTO, PresetsProxy>.clear() {
      _builder.clearPresets()
    }

    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 2 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val GetTransitionPresetsResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.GetTransitionPresetsResponse.copy(block: `com.solra.apis.spc.v1`.GetTransitionPresetsResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.GetTransitionPresetsResponse =
  `com.solra.apis.spc.v1`.GetTransitionPresetsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.GetTransitionPresetsResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

