// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializeloadSpaceResponse")
public inline fun loadSpaceResponse(block: com.solra.apis.spc.v1.LoadSpaceResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.LoadSpaceResponse =
  com.solra.apis.spc.v1.LoadSpaceResponseKt.Dsl._create(com.solra.apis.spc.v1.Spc.LoadSpaceResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.LoadSpaceResponse`
 */
public object LoadSpaceResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.LoadSpaceResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.LoadSpaceResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.LoadSpaceResponse = _builder.build()

    /**
     * `.solra.spc.v1.Space space = 1 [json_name = "space"];`
     */
    public var space: com.solra.apis.spc.v1.Spc.Space
      @kotlin.jvm.JvmName("getSpace")
        get() = _builder.space
      @kotlin.jvm.JvmName("setSpace")
        set(value) {
        _builder.space = value
      }
    /**
     * `.solra.spc.v1.Space space = 1 [json_name = "space"];`
     */
    public fun clearSpace() {
      _builder.clearSpace()
    }
    /**
     * `.solra.spc.v1.Space space = 1 [json_name = "space"];`
     * @return Whether the space field is set.
     */
    public fun hasSpace(): kotlin.Boolean {
      return _builder.hasSpace()
    }

    public val LoadSpaceResponseKt.Dsl.spaceOrNull: com.solra.apis.spc.v1.Spc.Space?
      get() = _builder.spaceOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InitialChunksProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 初始必要资产块
     * ```
     *
     * `repeated .solra.spc.v1.AssetChunk initial_chunks = 2 [json_name = "initialChunks"];`
     */
     public val initialChunks: com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.AssetChunk, InitialChunksProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.initialChunksList
      )
    /**
     * ```
     * 初始必要资产块
     * ```
     *
     * `repeated .solra.spc.v1.AssetChunk initial_chunks = 2 [json_name = "initialChunks"];`
     * @param value The initialChunks to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addInitialChunks")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.AssetChunk, InitialChunksProxy>.add(value: com.solra.apis.spc.v1.Spc.AssetChunk) {
      _builder.addInitialChunks(value)
    }
    /**
     * ```
     * 初始必要资产块
     * ```
     *
     * `repeated .solra.spc.v1.AssetChunk initial_chunks = 2 [json_name = "initialChunks"];`
     * @param value The initialChunks to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignInitialChunks")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.AssetChunk, InitialChunksProxy>.plusAssign(value: com.solra.apis.spc.v1.Spc.AssetChunk) {
      add(value)
    }
    /**
     * ```
     * 初始必要资产块
     * ```
     *
     * `repeated .solra.spc.v1.AssetChunk initial_chunks = 2 [json_name = "initialChunks"];`
     * @param values The initialChunks to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllInitialChunks")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.AssetChunk, InitialChunksProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.AssetChunk>) {
      _builder.addAllInitialChunks(values)
    }
    /**
     * ```
     * 初始必要资产块
     * ```
     *
     * `repeated .solra.spc.v1.AssetChunk initial_chunks = 2 [json_name = "initialChunks"];`
     * @param values The initialChunks to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllInitialChunks")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.AssetChunk, InitialChunksProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.AssetChunk>) {
      addAll(values)
    }
    /**
     * ```
     * 初始必要资产块
     * ```
     *
     * `repeated .solra.spc.v1.AssetChunk initial_chunks = 2 [json_name = "initialChunks"];`
     * @param index The index to set the value at.
     * @param value The initialChunks to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setInitialChunks")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.AssetChunk, InitialChunksProxy>.set(index: kotlin.Int, value: com.solra.apis.spc.v1.Spc.AssetChunk) {
      _builder.setInitialChunks(index, value)
    }
    /**
     * ```
     * 初始必要资产块
     * ```
     *
     * `repeated .solra.spc.v1.AssetChunk initial_chunks = 2 [json_name = "initialChunks"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearInitialChunks")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.AssetChunk, InitialChunksProxy>.clear() {
      _builder.clearInitialChunks()
    }

    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val LoadSpaceResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.LoadSpaceResponse.copy(block: `com.solra.apis.spc.v1`.LoadSpaceResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.LoadSpaceResponse =
  `com.solra.apis.spc.v1`.LoadSpaceResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.LoadSpaceResponseOrBuilder.spaceOrNull: com.solra.apis.spc.v1.Spc.Space?
  get() = if (hasSpace()) getSpace() else null

public val com.solra.apis.spc.v1.Spc.LoadSpaceResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

