// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializepredictPreloadResponse")
public inline fun predictPreloadResponse(block: com.solra.apis.spc.v1.PredictPreloadResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.PredictPreloadResponse =
  com.solra.apis.spc.v1.PredictPreloadResponseKt.Dsl._create(com.solra.apis.spc.v1.Spc.PredictPreloadResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.PredictPreloadResponse`
 */
public object PredictPreloadResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.PredictPreloadResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.PredictPreloadResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.PredictPreloadResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PredictedSpaceIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string predicted_space_ids = 1 [json_name = "predictedSpaceIds"];`
     * @return A list containing the predictedSpaceIds.
     */
    public val predictedSpaceIds: com.google.protobuf.kotlin.DslList<kotlin.String, PredictedSpaceIdsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.predictedSpaceIdsList
      )
    /**
     * `repeated string predicted_space_ids = 1 [json_name = "predictedSpaceIds"];`
     * @param value The predictedSpaceIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPredictedSpaceIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PredictedSpaceIdsProxy>.add(value: kotlin.String) {
      _builder.addPredictedSpaceIds(value)
    }
    /**
     * `repeated string predicted_space_ids = 1 [json_name = "predictedSpaceIds"];`
     * @param value The predictedSpaceIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPredictedSpaceIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PredictedSpaceIdsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string predicted_space_ids = 1 [json_name = "predictedSpaceIds"];`
     * @param values The predictedSpaceIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPredictedSpaceIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PredictedSpaceIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPredictedSpaceIds(values)
    }
    /**
     * `repeated string predicted_space_ids = 1 [json_name = "predictedSpaceIds"];`
     * @param values The predictedSpaceIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPredictedSpaceIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PredictedSpaceIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string predicted_space_ids = 1 [json_name = "predictedSpaceIds"];`
     * @param index The index to set the value at.
     * @param value The predictedSpaceIds to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPredictedSpaceIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PredictedSpaceIdsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setPredictedSpaceIds(index, value)
    }/**
     * `repeated string predicted_space_ids = 1 [json_name = "predictedSpaceIds"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPredictedSpaceIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PredictedSpaceIdsProxy>.clear() {
      _builder.clearPredictedSpaceIds()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LoadTimeEstimatesMsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * spaceId -> estimate ms
     * ```
     *
     * `map<string, int64> load_time_estimates_ms = 2 [json_name = "loadTimeEstimatesMs"];`
     */
     public val loadTimeEstimatesMs: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Long, LoadTimeEstimatesMsProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getLoadTimeEstimatesMsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.loadTimeEstimatesMsMap
      )
    /**
     * ```
     * spaceId -> estimate ms
     * ```
     *
     * `map<string, int64> load_time_estimates_ms = 2 [json_name = "loadTimeEstimatesMs"];`
     */
    @kotlin.jvm.JvmName("putLoadTimeEstimatesMs")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Long, LoadTimeEstimatesMsProxy>
      .put(key: kotlin.String, value: kotlin.Long) {
         _builder.putLoadTimeEstimatesMs(key, value)
       }
    /**
     * ```
     * spaceId -> estimate ms
     * ```
     *
     * `map<string, int64> load_time_estimates_ms = 2 [json_name = "loadTimeEstimatesMs"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setLoadTimeEstimatesMs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Long, LoadTimeEstimatesMsProxy>
      .set(key: kotlin.String, value: kotlin.Long) {
         put(key, value)
       }
    /**
     * ```
     * spaceId -> estimate ms
     * ```
     *
     * `map<string, int64> load_time_estimates_ms = 2 [json_name = "loadTimeEstimatesMs"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeLoadTimeEstimatesMs")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Long, LoadTimeEstimatesMsProxy>
      .remove(key: kotlin.String) {
         _builder.removeLoadTimeEstimatesMs(key)
       }
    /**
     * ```
     * spaceId -> estimate ms
     * ```
     *
     * `map<string, int64> load_time_estimates_ms = 2 [json_name = "loadTimeEstimatesMs"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllLoadTimeEstimatesMs")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Long, LoadTimeEstimatesMsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.Long>) {
         _builder.putAllLoadTimeEstimatesMs(map)
       }
    /**
     * ```
     * spaceId -> estimate ms
     * ```
     *
     * `map<string, int64> load_time_estimates_ms = 2 [json_name = "loadTimeEstimatesMs"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearLoadTimeEstimatesMs")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Long, LoadTimeEstimatesMsProxy>
      .clear() {
         _builder.clearLoadTimeEstimatesMs()
       }

    /**
     * ```
     * 预加载覆盖率
     * ```
     *
     * `double preload_coverage_rate = 3 [json_name = "preloadCoverageRate"];`
     */
    public var preloadCoverageRate: kotlin.Double
      @kotlin.jvm.JvmName("getPreloadCoverageRate")
        get() = _builder.preloadCoverageRate
      @kotlin.jvm.JvmName("setPreloadCoverageRate")
        set(value) {
        _builder.preloadCoverageRate = value
      }
    /**
     * ```
     * 预加载覆盖率
     * ```
     *
     * `double preload_coverage_rate = 3 [json_name = "preloadCoverageRate"];`
     */
    public fun clearPreloadCoverageRate() {
      _builder.clearPreloadCoverageRate()
    }

    /**
     * `.solra.common.SolraError error = 4 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 4 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 4 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val PredictPreloadResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.PredictPreloadResponse.copy(block: `com.solra.apis.spc.v1`.PredictPreloadResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.PredictPreloadResponse =
  `com.solra.apis.spc.v1`.PredictPreloadResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.PredictPreloadResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

