// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializepredictPreloadRequest")
public inline fun predictPreloadRequest(block: com.solra.apis.spc.v1.PredictPreloadRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.PredictPreloadRequest =
  com.solra.apis.spc.v1.PredictPreloadRequestKt.Dsl._create(com.solra.apis.spc.v1.Spc.PredictPreloadRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.PredictPreloadRequest`
 */
public object PredictPreloadRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.PredictPreloadRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.PredictPreloadRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.PredictPreloadRequest = _builder.build()

    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val PredictPreloadRequestKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `.solra.common.SpaceId current_space_id = 2 [json_name = "currentSpaceId"];`
     */
    public var currentSpaceId: com.solra.apis.common.Common.SpaceId
      @kotlin.jvm.JvmName("getCurrentSpaceId")
        get() = _builder.currentSpaceId
      @kotlin.jvm.JvmName("setCurrentSpaceId")
        set(value) {
        _builder.currentSpaceId = value
      }
    /**
     * `.solra.common.SpaceId current_space_id = 2 [json_name = "currentSpaceId"];`
     */
    public fun clearCurrentSpaceId() {
      _builder.clearCurrentSpaceId()
    }
    /**
     * `.solra.common.SpaceId current_space_id = 2 [json_name = "currentSpaceId"];`
     * @return Whether the currentSpaceId field is set.
     */
    public fun hasCurrentSpaceId(): kotlin.Boolean {
      return _builder.hasCurrentSpaceId()
    }

    public val PredictPreloadRequestKt.Dsl.currentSpaceIdOrNull: com.solra.apis.common.Common.SpaceId?
      get() = _builder.currentSpaceIdOrNull

    /**
     * ```
     * 预加载目标数
     * ```
     *
     * `int32 count = 3 [json_name = "count"];`
     */
    public var count: kotlin.Int
      @kotlin.jvm.JvmName("getCount")
        get() = _builder.count
      @kotlin.jvm.JvmName("setCount")
        set(value) {
        _builder.count = value
      }
    /**
     * ```
     * 预加载目标数
     * ```
     *
     * `int32 count = 3 [json_name = "count"];`
     */
    public fun clearCount() {
      _builder.clearCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.PredictPreloadRequest.copy(block: `com.solra.apis.spc.v1`.PredictPreloadRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.PredictPreloadRequest =
  `com.solra.apis.spc.v1`.PredictPreloadRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.PredictPreloadRequestOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

public val com.solra.apis.spc.v1.Spc.PredictPreloadRequestOrBuilder.currentSpaceIdOrNull: com.solra.apis.common.Common.SpaceId?
  get() = if (hasCurrentSpaceId()) getCurrentSpaceId() else null

