// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spc/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializepreviewCardList")
public inline fun previewCardList(block: com.solra.apis.spc.v1.PreviewCardListKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.PreviewCardList =
  com.solra.apis.spc.v1.PreviewCardListKt.Dsl._create(com.solra.apis.spc.v1.Spc.PreviewCardList.newBuilder()).apply { block() }._build()
/**
 * ```
 * PreviewCardList 预览卡片列表
 * ```
 *
 * Protobuf type `solra.spc.v1.PreviewCardList`
 */
public object PreviewCardListKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.PreviewCardList.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.PreviewCardList.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.PreviewCardList = _builder.build()

    /**
     * `string list_id = 1 [json_name = "listId"];`
     */
    public var listId: kotlin.String
      @kotlin.jvm.JvmName("getListId")
        get() = _builder.listId
      @kotlin.jvm.JvmName("setListId")
        set(value) {
        _builder.listId = value
      }
    /**
     * `string list_id = 1 [json_name = "listId"];`
     */
    public fun clearListId() {
      _builder.clearListId()
    }

    /**
     * ```
     * "热门推荐" / "最新" / "为你推荐"
     * ```
     *
     * `string list_name = 2 [json_name = "listName"];`
     */
    public var listName: kotlin.String
      @kotlin.jvm.JvmName("getListName")
        get() = _builder.listName
      @kotlin.jvm.JvmName("setListName")
        set(value) {
        _builder.listName = value
      }
    /**
     * ```
     * "热门推荐" / "最新" / "为你推荐"
     * ```
     *
     * `string list_name = 2 [json_name = "listName"];`
     */
    public fun clearListName() {
      _builder.clearListName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CardsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 3 [json_name = "cards"];`
     */
     public val cards: com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.cardsList
      )
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 3 [json_name = "cards"];`
     * @param value The cards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addCards")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.add(value: com.solra.apis.spc.v1.Spc.PreviewCard) {
      _builder.addCards(value)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 3 [json_name = "cards"];`
     * @param value The cards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignCards")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.plusAssign(value: com.solra.apis.spc.v1.Spc.PreviewCard) {
      add(value)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 3 [json_name = "cards"];`
     * @param values The cards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllCards")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.PreviewCard>) {
      _builder.addAllCards(values)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 3 [json_name = "cards"];`
     * @param values The cards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllCards")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.spc.v1.Spc.PreviewCard>) {
      addAll(values)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 3 [json_name = "cards"];`
     * @param index The index to set the value at.
     * @param value The cards to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setCards")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.set(index: kotlin.Int, value: com.solra.apis.spc.v1.Spc.PreviewCard) {
      _builder.setCards(index, value)
    }
    /**
     * `repeated .solra.spc.v1.PreviewCard cards = 3 [json_name = "cards"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearCards")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.spc.v1.Spc.PreviewCard, CardsProxy>.clear() {
      _builder.clearCards()
    }

    /**
     * `.solra.common.PageResponse page = 4 [json_name = "page"];`
     */
    public var page: com.solra.apis.common.Common.PageResponse
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * `.solra.common.PageResponse page = 4 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * `.solra.common.PageResponse page = 4 [json_name = "page"];`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }

    public val PreviewCardListKt.Dsl.pageOrNull: com.solra.apis.common.Common.PageResponse?
      get() = _builder.pageOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.PreviewCardList.copy(block: `com.solra.apis.spc.v1`.PreviewCardListKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.PreviewCardList =
  `com.solra.apis.spc.v1`.PreviewCardListKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.PreviewCardListOrBuilder.pageOrNull: com.solra.apis.common.Common.PageResponse?
  get() = if (hasPage()) getPage() else null

