// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spc/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializespaceModule")
public inline fun spaceModule(block: com.solra.apis.spc.v1.SpaceModuleKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.SpaceModule =
  com.solra.apis.spc.v1.SpaceModuleKt.Dsl._create(com.solra.apis.spc.v1.Spc.SpaceModule.newBuilder()).apply { block() }._build()
/**
 * ```
 * SpaceModule 空间功能模块
 * ```
 *
 * Protobuf type `solra.spc.v1.SpaceModule`
 */
public object SpaceModuleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.SpaceModule.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.SpaceModule.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.SpaceModule = _builder.build()

    /**
     * `string module_id = 1 [json_name = "moduleId"];`
     */
    public var moduleId: kotlin.String
      @kotlin.jvm.JvmName("getModuleId")
        get() = _builder.moduleId
      @kotlin.jvm.JvmName("setModuleId")
        set(value) {
        _builder.moduleId = value
      }
    /**
     * `string module_id = 1 [json_name = "moduleId"];`
     */
    public fun clearModuleId() {
      _builder.clearModuleId()
    }

    /**
     * ```
     * chat / game / media / commerce
     * ```
     *
     * `string module_type = 2 [json_name = "moduleType"];`
     */
    public var moduleType: kotlin.String
      @kotlin.jvm.JvmName("getModuleType")
        get() = _builder.moduleType
      @kotlin.jvm.JvmName("setModuleType")
        set(value) {
        _builder.moduleType = value
      }
    /**
     * ```
     * chat / game / media / commerce
     * ```
     *
     * `string module_type = 2 [json_name = "moduleType"];`
     */
    public fun clearModuleType() {
      _builder.clearModuleType()
    }

    /**
     * ```
     * 模块配置（JSON）
     * ```
     *
     * `string config_json = 3 [json_name = "configJson"];`
     */
    public var configJson: kotlin.String
      @kotlin.jvm.JvmName("getConfigJson")
        get() = _builder.configJson
      @kotlin.jvm.JvmName("setConfigJson")
        set(value) {
        _builder.configJson = value
      }
    /**
     * ```
     * 模块配置（JSON）
     * ```
     *
     * `string config_json = 3 [json_name = "configJson"];`
     */
    public fun clearConfigJson() {
      _builder.clearConfigJson()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.SpaceModule.copy(block: `com.solra.apis.spc.v1`.SpaceModuleKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.SpaceModule =
  `com.solra.apis.spc.v1`.SpaceModuleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

