// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializespaceMeta")
public inline fun spaceMeta(block: com.solra.apis.spc.v1.SpaceMetaKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.SpaceMeta =
  com.solra.apis.spc.v1.SpaceMetaKt.Dsl._create(com.solra.apis.spc.v1.Spc.SpaceMeta.newBuilder()).apply { block() }._build()
/**
 * ```
 * SpaceMeta 空间元信息
 * ```
 *
 * Protobuf type `solra.spc.v1.SpaceMeta`
 */
public object SpaceMetaKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.SpaceMeta.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.SpaceMeta.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.SpaceMeta = _builder.build()

    /**
     * ```
     * 标题
     * ```
     *
     * `string title = 1 [json_name = "title"];`
     */
    public var title: kotlin.String
      @kotlin.jvm.JvmName("getTitle")
        get() = _builder.title
      @kotlin.jvm.JvmName("setTitle")
        set(value) {
        _builder.title = value
      }
    /**
     * ```
     * 标题
     * ```
     *
     * `string title = 1 [json_name = "title"];`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * 描述
     * ```
     *
     * `string description = 2 [json_name = "description"];`
     */
    public var description: kotlin.String
      @kotlin.jvm.JvmName("getDescription")
        get() = _builder.description
      @kotlin.jvm.JvmName("setDescription")
        set(value) {
        _builder.description = value
      }
    /**
     * ```
     * 描述
     * ```
     *
     * `string description = 2 [json_name = "description"];`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * ```
     * 分类
     * ```
     *
     * `.solra.spc.v1.SpaceCategory category = 3 [json_name = "category"];`
     */
    public var category: com.solra.apis.spc.v1.Spc.SpaceCategory
      @kotlin.jvm.JvmName("getCategory")
        get() = _builder.category
      @kotlin.jvm.JvmName("setCategory")
        set(value) {
        _builder.category = value
      }
    public var categoryValue: kotlin.Int
      @kotlin.jvm.JvmName("getCategoryValue")
        get() = _builder.categoryValue
      @kotlin.jvm.JvmName("setCategoryValue")
        set(value) {
        _builder.categoryValue = value
      }
    /**
     * ```
     * 分类
     * ```
     *
     * `.solra.spc.v1.SpaceCategory category = 3 [json_name = "category"];`
     */
    public fun clearCategory() {
      _builder.clearCategory()
    }

    /**
     * ```
     * 缩略图
     * ```
     *
     * `string thumbnail_url = 4 [json_name = "thumbnailUrl"];`
     */
    public var thumbnailUrl: kotlin.String
      @kotlin.jvm.JvmName("getThumbnailUrl")
        get() = _builder.thumbnailUrl
      @kotlin.jvm.JvmName("setThumbnailUrl")
        set(value) {
        _builder.thumbnailUrl = value
      }
    /**
     * ```
     * 缩略图
     * ```
     *
     * `string thumbnail_url = 4 [json_name = "thumbnailUrl"];`
     */
    public fun clearThumbnailUrl() {
      _builder.clearThumbnailUrl()
    }

    /**
     * ```
     * 地理位置（可选）
     * ```
     *
     * `.solra.common.GeoPoint location = 5 [json_name = "location"];`
     */
    public var location: com.solra.apis.common.Common.GeoPoint
      @kotlin.jvm.JvmName("getLocation")
        get() = _builder.location
      @kotlin.jvm.JvmName("setLocation")
        set(value) {
        _builder.location = value
      }
    /**
     * ```
     * 地理位置（可选）
     * ```
     *
     * `.solra.common.GeoPoint location = 5 [json_name = "location"];`
     */
    public fun clearLocation() {
      _builder.clearLocation()
    }
    /**
     * ```
     * 地理位置（可选）
     * ```
     *
     * `.solra.common.GeoPoint location = 5 [json_name = "location"];`
     * @return Whether the location field is set.
     */
    public fun hasLocation(): kotlin.Boolean {
      return _builder.hasLocation()
    }

    public val SpaceMetaKt.Dsl.locationOrNull: com.solra.apis.common.Common.GeoPoint?
      get() = _builder.locationOrNull

    /**
     * ```
     * 隐私设置
     * ```
     *
     * `.solra.spc.v1.SpacePrivacy privacy = 6 [json_name = "privacy"];`
     */
    public var privacy: com.solra.apis.spc.v1.Spc.SpacePrivacy
      @kotlin.jvm.JvmName("getPrivacy")
        get() = _builder.privacy
      @kotlin.jvm.JvmName("setPrivacy")
        set(value) {
        _builder.privacy = value
      }
    public var privacyValue: kotlin.Int
      @kotlin.jvm.JvmName("getPrivacyValue")
        get() = _builder.privacyValue
      @kotlin.jvm.JvmName("setPrivacyValue")
        set(value) {
        _builder.privacyValue = value
      }
    /**
     * ```
     * 隐私设置
     * ```
     *
     * `.solra.spc.v1.SpacePrivacy privacy = 6 [json_name = "privacy"];`
     */
    public fun clearPrivacy() {
      _builder.clearPrivacy()
    }

    /**
     * ```
     * 语言
     * ```
     *
     * `string language_code = 7 [json_name = "languageCode"];`
     */
    public var languageCode: kotlin.String
      @kotlin.jvm.JvmName("getLanguageCode")
        get() = _builder.languageCode
      @kotlin.jvm.JvmName("setLanguageCode")
        set(value) {
        _builder.languageCode = value
      }
    /**
     * ```
     * 语言
     * ```
     *
     * `string language_code = 7 [json_name = "languageCode"];`
     */
    public fun clearLanguageCode() {
      _builder.clearLanguageCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.SpaceMeta.copy(block: `com.solra.apis.spc.v1`.SpaceMetaKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.SpaceMeta =
  `com.solra.apis.spc.v1`.SpaceMetaKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.spc.v1.Spc.SpaceMetaOrBuilder.locationOrNull: com.solra.apis.common.Common.GeoPoint?
  get() = if (hasLocation()) getLocation() else null

