// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/spc/v1/spc.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.spc.v1;

@kotlin.jvm.JvmName("-initializetransitionPresetDTO")
public inline fun transitionPresetDTO(block: com.solra.apis.spc.v1.TransitionPresetDTOKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.TransitionPresetDTO =
  com.solra.apis.spc.v1.TransitionPresetDTOKt.Dsl._create(com.solra.apis.spc.v1.Spc.TransitionPresetDTO.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.spc.v1.TransitionPresetDTO`
 */
public object TransitionPresetDTOKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.spc.v1.Spc.TransitionPresetDTO.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.spc.v1.Spc.TransitionPresetDTO.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.spc.v1.Spc.TransitionPresetDTO = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string effect = 3 [json_name = "effect"];`
     */
    public var effect: kotlin.String
      @kotlin.jvm.JvmName("getEffect")
        get() = _builder.effect
      @kotlin.jvm.JvmName("setEffect")
        set(value) {
        _builder.effect = value
      }
    /**
     * `string effect = 3 [json_name = "effect"];`
     */
    public fun clearEffect() {
      _builder.clearEffect()
    }

    /**
     * `int32 default_duration_ms = 4 [json_name = "defaultDurationMs"];`
     */
    public var defaultDurationMs: kotlin.Int
      @kotlin.jvm.JvmName("getDefaultDurationMs")
        get() = _builder.defaultDurationMs
      @kotlin.jvm.JvmName("setDefaultDurationMs")
        set(value) {
        _builder.defaultDurationMs = value
      }
    /**
     * `int32 default_duration_ms = 4 [json_name = "defaultDurationMs"];`
     */
    public fun clearDefaultDurationMs() {
      _builder.clearDefaultDurationMs()
    }

    /**
     * `string easing = 5 [json_name = "easing"];`
     */
    public var easing: kotlin.String
      @kotlin.jvm.JvmName("getEasing")
        get() = _builder.easing
      @kotlin.jvm.JvmName("setEasing")
        set(value) {
        _builder.easing = value
      }
    /**
     * `string easing = 5 [json_name = "easing"];`
     */
    public fun clearEasing() {
      _builder.clearEasing()
    }

    /**
     * `string description = 6 [json_name = "description"];`
     */
    public var description: kotlin.String
      @kotlin.jvm.JvmName("getDescription")
        get() = _builder.description
      @kotlin.jvm.JvmName("setDescription")
        set(value) {
        _builder.description = value
      }
    /**
     * `string description = 6 [json_name = "description"];`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.spc.v1.Spc.TransitionPresetDTO.copy(block: `com.solra.apis.spc.v1`.TransitionPresetDTOKt.Dsl.() -> kotlin.Unit): com.solra.apis.spc.v1.Spc.TransitionPresetDTO =
  `com.solra.apis.spc.v1`.TransitionPresetDTOKt.Dsl._create(this.toBuilder()).apply { block() }._build()

