// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializeaudioConfig")
public inline fun audioConfig(block: com.solra.proto.crt.AudioConfigKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.AudioConfig =
  com.solra.proto.crt.AudioConfigKt.Dsl._create(com.solra.proto.crt.Crt.AudioConfig.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.AudioConfig`
 */
public object AudioConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.AudioConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.AudioConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.AudioConfig = _builder.build()

    /**
     * `float master_volume = 1 [json_name = "masterVolume"];`
     */
    public var masterVolume: kotlin.Float
      @kotlin.jvm.JvmName("getMasterVolume")
        get() = _builder.masterVolume
      @kotlin.jvm.JvmName("setMasterVolume")
        set(value) {
        _builder.masterVolume = value
      }
    /**
     * `float master_volume = 1 [json_name = "masterVolume"];`
     */
    public fun clearMasterVolume() {
      _builder.clearMasterVolume()
    }

    /**
     * `bool spatial_audio = 2 [json_name = "spatialAudio"];`
     */
    public var spatialAudio: kotlin.Boolean
      @kotlin.jvm.JvmName("getSpatialAudio")
        get() = _builder.spatialAudio
      @kotlin.jvm.JvmName("setSpatialAudio")
        set(value) {
        _builder.spatialAudio = value
      }
    /**
     * `bool spatial_audio = 2 [json_name = "spatialAudio"];`
     */
    public fun clearSpatialAudio() {
      _builder.clearSpatialAudio()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SourcesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.crt.AudioSource sources = 3 [json_name = "sources"];`
     */
     public val sources: com.google.protobuf.kotlin.DslList<com.solra.proto.crt.Crt.AudioSource, SourcesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.sourcesList
      )
    /**
     * `repeated .solra.crt.AudioSource sources = 3 [json_name = "sources"];`
     * @param value The sources to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSources")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.crt.Crt.AudioSource, SourcesProxy>.add(value: com.solra.proto.crt.Crt.AudioSource) {
      _builder.addSources(value)
    }
    /**
     * `repeated .solra.crt.AudioSource sources = 3 [json_name = "sources"];`
     * @param value The sources to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSources")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.crt.Crt.AudioSource, SourcesProxy>.plusAssign(value: com.solra.proto.crt.Crt.AudioSource) {
      add(value)
    }
    /**
     * `repeated .solra.crt.AudioSource sources = 3 [json_name = "sources"];`
     * @param values The sources to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSources")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.crt.Crt.AudioSource, SourcesProxy>.addAll(values: kotlin.collections.Iterable<com.solra.proto.crt.Crt.AudioSource>) {
      _builder.addAllSources(values)
    }
    /**
     * `repeated .solra.crt.AudioSource sources = 3 [json_name = "sources"];`
     * @param values The sources to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSources")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.crt.Crt.AudioSource, SourcesProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.proto.crt.Crt.AudioSource>) {
      addAll(values)
    }
    /**
     * `repeated .solra.crt.AudioSource sources = 3 [json_name = "sources"];`
     * @param index The index to set the value at.
     * @param value The sources to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSources")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.crt.Crt.AudioSource, SourcesProxy>.set(index: kotlin.Int, value: com.solra.proto.crt.Crt.AudioSource) {
      _builder.setSources(index, value)
    }
    /**
     * `repeated .solra.crt.AudioSource sources = 3 [json_name = "sources"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSources")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.crt.Crt.AudioSource, SourcesProxy>.clear() {
      _builder.clearSources()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.AudioConfig.copy(block: `com.solra.proto.crt`.AudioConfigKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.AudioConfig =
  `com.solra.proto.crt`.AudioConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

