// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializebuildProjectResponse")
public inline fun buildProjectResponse(block: com.solra.proto.crt.BuildProjectResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.BuildProjectResponse =
  com.solra.proto.crt.BuildProjectResponseKt.Dsl._create(com.solra.proto.crt.Crt.BuildProjectResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.BuildProjectResponse`
 */
public object BuildProjectResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.BuildProjectResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.BuildProjectResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.BuildProjectResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val BuildProjectResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull

    /**
     * `string build_id = 2 [json_name = "buildId"];`
     */
    public var buildId: kotlin.String
      @kotlin.jvm.JvmName("getBuildId")
        get() = _builder.buildId
      @kotlin.jvm.JvmName("setBuildId")
        set(value) {
        _builder.buildId = value
      }
    /**
     * `string build_id = 2 [json_name = "buildId"];`
     */
    public fun clearBuildId() {
      _builder.clearBuildId()
    }

    /**
     * ```
     * 0.0 - 1.0
     * ```
     *
     * `float progress = 3 [json_name = "progress"];`
     */
    public var progress: kotlin.Float
      @kotlin.jvm.JvmName("getProgress")
        get() = _builder.progress
      @kotlin.jvm.JvmName("setProgress")
        set(value) {
        _builder.progress = value
      }
    /**
     * ```
     * 0.0 - 1.0
     * ```
     *
     * `float progress = 3 [json_name = "progress"];`
     */
    public fun clearProgress() {
      _builder.clearProgress()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.BuildProjectResponse.copy(block: `com.solra.proto.crt`.BuildProjectResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.BuildProjectResponse =
  `com.solra.proto.crt`.BuildProjectResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.crt.Crt.BuildProjectResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

