// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializebuildProjectRequest")
public inline fun buildProjectRequest(block: com.solra.proto.crt.BuildProjectRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.BuildProjectRequest =
  com.solra.proto.crt.BuildProjectRequestKt.Dsl._create(com.solra.proto.crt.Crt.BuildProjectRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.BuildProjectRequest`
 */
public object BuildProjectRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.BuildProjectRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.BuildProjectRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.BuildProjectRequest = _builder.build()

    /**
     * `string project_id = 1 [json_name = "projectId"];`
     */
    public var projectId: kotlin.String
      @kotlin.jvm.JvmName("getProjectId")
        get() = _builder.projectId
      @kotlin.jvm.JvmName("setProjectId")
        set(value) {
        _builder.projectId = value
      }
    /**
     * `string project_id = 1 [json_name = "projectId"];`
     */
    public fun clearProjectId() {
      _builder.clearProjectId()
    }

    /**
     * ```
     * 增量构建
     * ```
     *
     * `bool incremental = 2 [json_name = "incremental"];`
     */
    public var incremental: kotlin.Boolean
      @kotlin.jvm.JvmName("getIncremental")
        get() = _builder.incremental
      @kotlin.jvm.JvmName("setIncremental")
        set(value) {
        _builder.incremental = value
      }
    /**
     * ```
     * 增量构建
     * ```
     *
     * `bool incremental = 2 [json_name = "incremental"];`
     */
    public fun clearIncremental() {
      _builder.clearIncremental()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.BuildProjectRequest.copy(block: `com.solra.proto.crt`.BuildProjectRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.BuildProjectRequest =
  `com.solra.proto.crt`.BuildProjectRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

