// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializecreateProjectRequest")
public inline fun createProjectRequest(block: com.solra.proto.crt.CreateProjectRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.CreateProjectRequest =
  com.solra.proto.crt.CreateProjectRequestKt.Dsl._create(com.solra.proto.crt.Crt.CreateProjectRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.CreateProjectRequest`
 */
public object CreateProjectRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.CreateProjectRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.CreateProjectRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.CreateProjectRequest = _builder.build()

    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     */
    public var spaceId: com.solra.apis.common.Common.SpaceId
      @kotlin.jvm.JvmName("getSpaceId")
        get() = _builder.spaceId
      @kotlin.jvm.JvmName("setSpaceId")
        set(value) {
        _builder.spaceId = value
      }
    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     */
    public fun clearSpaceId() {
      _builder.clearSpaceId()
    }
    /**
     * `.solra.common.SpaceId space_id = 1 [json_name = "spaceId"];`
     * @return Whether the spaceId field is set.
     */
    public fun hasSpaceId(): kotlin.Boolean {
      return _builder.hasSpaceId()
    }

    public val CreateProjectRequestKt.Dsl.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
      get() = _builder.spaceIdOrNull

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.solra.crt.ProjectType type = 3 [json_name = "type"];`
     */
    public var type: com.solra.proto.crt.Crt.ProjectType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * `.solra.crt.ProjectType type = 3 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * ```
     * 可选，从模板创建
     * ```
     *
     * `string template_id = 4 [json_name = "templateId"];`
     */
    public var templateId: kotlin.String
      @kotlin.jvm.JvmName("getTemplateId")
        get() = _builder.templateId
      @kotlin.jvm.JvmName("setTemplateId")
        set(value) {
        _builder.templateId = value
      }
    /**
     * ```
     * 可选，从模板创建
     * ```
     *
     * `string template_id = 4 [json_name = "templateId"];`
     */
    public fun clearTemplateId() {
      _builder.clearTemplateId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.CreateProjectRequest.copy(block: `com.solra.proto.crt`.CreateProjectRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.CreateProjectRequest =
  `com.solra.proto.crt`.CreateProjectRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.crt.Crt.CreateProjectRequestOrBuilder.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
  get() = if (hasSpaceId()) getSpaceId() else null

