// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializecreateProjectResponse")
public inline fun createProjectResponse(block: com.solra.proto.crt.CreateProjectResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.CreateProjectResponse =
  com.solra.proto.crt.CreateProjectResponseKt.Dsl._create(com.solra.proto.crt.Crt.CreateProjectResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.CreateProjectResponse`
 */
public object CreateProjectResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.CreateProjectResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.CreateProjectResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.CreateProjectResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val CreateProjectResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull

    /**
     * `.solra.crt.SpaceProject project = 2 [json_name = "project"];`
     */
    public var project: com.solra.proto.crt.Crt.SpaceProject
      @kotlin.jvm.JvmName("getProject")
        get() = _builder.project
      @kotlin.jvm.JvmName("setProject")
        set(value) {
        _builder.project = value
      }
    /**
     * `.solra.crt.SpaceProject project = 2 [json_name = "project"];`
     */
    public fun clearProject() {
      _builder.clearProject()
    }
    /**
     * `.solra.crt.SpaceProject project = 2 [json_name = "project"];`
     * @return Whether the project field is set.
     */
    public fun hasProject(): kotlin.Boolean {
      return _builder.hasProject()
    }

    public val CreateProjectResponseKt.Dsl.projectOrNull: com.solra.proto.crt.Crt.SpaceProject?
      get() = _builder.projectOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.CreateProjectResponse.copy(block: `com.solra.proto.crt`.CreateProjectResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.CreateProjectResponse =
  `com.solra.proto.crt`.CreateProjectResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.crt.Crt.CreateProjectResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

public val com.solra.proto.crt.Crt.CreateProjectResponseOrBuilder.projectOrNull: com.solra.proto.crt.Crt.SpaceProject?
  get() = if (hasProject()) getProject() else null

