// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializegetAssetRequest")
public inline fun getAssetRequest(block: com.solra.proto.crt.GetAssetRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.GetAssetRequest =
  com.solra.proto.crt.GetAssetRequestKt.Dsl._create(com.solra.proto.crt.Crt.GetAssetRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.GetAssetRequest`
 */
public object GetAssetRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.GetAssetRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.GetAssetRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.GetAssetRequest = _builder.build()

    /**
     * `string asset_id = 1 [json_name = "assetId"];`
     */
    public var assetId: kotlin.String
      @kotlin.jvm.JvmName("getAssetId")
        get() = _builder.assetId
      @kotlin.jvm.JvmName("setAssetId")
        set(value) {
        _builder.assetId = value
      }
    /**
     * `string asset_id = 1 [json_name = "assetId"];`
     */
    public fun clearAssetId() {
      _builder.clearAssetId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.GetAssetRequest.copy(block: `com.solra.proto.crt`.GetAssetRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.GetAssetRequest =
  `com.solra.proto.crt`.GetAssetRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

