// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializegetSceneGraphRequest")
public inline fun getSceneGraphRequest(block: com.solra.proto.crt.GetSceneGraphRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.GetSceneGraphRequest =
  com.solra.proto.crt.GetSceneGraphRequestKt.Dsl._create(com.solra.proto.crt.Crt.GetSceneGraphRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.GetSceneGraphRequest`
 */
public object GetSceneGraphRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.GetSceneGraphRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.GetSceneGraphRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.GetSceneGraphRequest = _builder.build()

    /**
     * `string project_id = 1 [json_name = "projectId"];`
     */
    public var projectId: kotlin.String
      @kotlin.jvm.JvmName("getProjectId")
        get() = _builder.projectId
      @kotlin.jvm.JvmName("setProjectId")
        set(value) {
        _builder.projectId = value
      }
    /**
     * `string project_id = 1 [json_name = "projectId"];`
     */
    public fun clearProjectId() {
      _builder.clearProjectId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.GetSceneGraphRequest.copy(block: `com.solra.proto.crt`.GetSceneGraphRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.GetSceneGraphRequest =
  `com.solra.proto.crt`.GetSceneGraphRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

