// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializelistTemplatesRequest")
public inline fun listTemplatesRequest(block: com.solra.proto.crt.ListTemplatesRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.ListTemplatesRequest =
  com.solra.proto.crt.ListTemplatesRequestKt.Dsl._create(com.solra.proto.crt.Crt.ListTemplatesRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.ListTemplatesRequest`
 */
public object ListTemplatesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.ListTemplatesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.ListTemplatesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.ListTemplatesRequest = _builder.build()

    /**
     * `.solra.common.PageRequest page = 1 [json_name = "page"];`
     */
    public var page: com.solra.apis.common.Common.PageRequest
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * `.solra.common.PageRequest page = 1 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * `.solra.common.PageRequest page = 1 [json_name = "page"];`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }

    public val ListTemplatesRequestKt.Dsl.pageOrNull: com.solra.apis.common.Common.PageRequest?
      get() = _builder.pageOrNull

    /**
     * `.solra.crt.TemplateCategory category = 2 [json_name = "category"];`
     */
    public var category: com.solra.proto.crt.Crt.TemplateCategory
      @kotlin.jvm.JvmName("getCategory")
        get() = _builder.category
      @kotlin.jvm.JvmName("setCategory")
        set(value) {
        _builder.category = value
      }
    public var categoryValue: kotlin.Int
      @kotlin.jvm.JvmName("getCategoryValue")
        get() = _builder.categoryValue
      @kotlin.jvm.JvmName("setCategoryValue")
        set(value) {
        _builder.categoryValue = value
      }
    /**
     * `.solra.crt.TemplateCategory category = 2 [json_name = "category"];`
     */
    public fun clearCategory() {
      _builder.clearCategory()
    }

    /**
     * `string keyword = 3 [json_name = "keyword"];`
     */
    public var keyword: kotlin.String
      @kotlin.jvm.JvmName("getKeyword")
        get() = _builder.keyword
      @kotlin.jvm.JvmName("setKeyword")
        set(value) {
        _builder.keyword = value
      }
    /**
     * `string keyword = 3 [json_name = "keyword"];`
     */
    public fun clearKeyword() {
      _builder.clearKeyword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.ListTemplatesRequest.copy(block: `com.solra.proto.crt`.ListTemplatesRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.ListTemplatesRequest =
  `com.solra.proto.crt`.ListTemplatesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.crt.Crt.ListTemplatesRequestOrBuilder.pageOrNull: com.solra.apis.common.Common.PageRequest?
  get() = if (hasPage()) getPage() else null

