// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializeupdateProjectRequest")
public inline fun updateProjectRequest(block: com.solra.proto.crt.UpdateProjectRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.UpdateProjectRequest =
  com.solra.proto.crt.UpdateProjectRequestKt.Dsl._create(com.solra.proto.crt.Crt.UpdateProjectRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.UpdateProjectRequest`
 */
public object UpdateProjectRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.UpdateProjectRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.UpdateProjectRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.UpdateProjectRequest = _builder.build()

    /**
     * `string project_id = 1 [json_name = "projectId"];`
     */
    public var projectId: kotlin.String
      @kotlin.jvm.JvmName("getProjectId")
        get() = _builder.projectId
      @kotlin.jvm.JvmName("setProjectId")
        set(value) {
        _builder.projectId = value
      }
    /**
     * `string project_id = 1 [json_name = "projectId"];`
     */
    public fun clearProjectId() {
      _builder.clearProjectId()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string description = 3 [json_name = "description"];`
     */
    public var description: kotlin.String
      @kotlin.jvm.JvmName("getDescription")
        get() = _builder.description
      @kotlin.jvm.JvmName("setDescription")
        set(value) {
        _builder.description = value
      }
    /**
     * `string description = 3 [json_name = "description"];`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `.solra.crt.ProjectConfig config = 4 [json_name = "config"];`
     */
    public var config: com.solra.proto.crt.Crt.ProjectConfig
      @kotlin.jvm.JvmName("getConfig")
        get() = _builder.config
      @kotlin.jvm.JvmName("setConfig")
        set(value) {
        _builder.config = value
      }
    /**
     * `.solra.crt.ProjectConfig config = 4 [json_name = "config"];`
     */
    public fun clearConfig() {
      _builder.clearConfig()
    }
    /**
     * `.solra.crt.ProjectConfig config = 4 [json_name = "config"];`
     * @return Whether the config field is set.
     */
    public fun hasConfig(): kotlin.Boolean {
      return _builder.hasConfig()
    }

    public val UpdateProjectRequestKt.Dsl.configOrNull: com.solra.proto.crt.Crt.ProjectConfig?
      get() = _builder.configOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.UpdateProjectRequest.copy(block: `com.solra.proto.crt`.UpdateProjectRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.UpdateProjectRequest =
  `com.solra.proto.crt`.UpdateProjectRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.crt.Crt.UpdateProjectRequestOrBuilder.configOrNull: com.solra.proto.crt.Crt.ProjectConfig?
  get() = if (hasConfig()) getConfig() else null

