// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/crt/crt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.crt;

@kotlin.jvm.JvmName("-initializeuploadAssetResponse")
public inline fun uploadAssetResponse(block: com.solra.proto.crt.UploadAssetResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.UploadAssetResponse =
  com.solra.proto.crt.UploadAssetResponseKt.Dsl._create(com.solra.proto.crt.Crt.UploadAssetResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.crt.UploadAssetResponse`
 */
public object UploadAssetResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.crt.Crt.UploadAssetResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.crt.Crt.UploadAssetResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.crt.Crt.UploadAssetResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val UploadAssetResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull

    /**
     * `.solra.crt.Asset asset = 2 [json_name = "asset"];`
     */
    public var asset: com.solra.proto.crt.Crt.Asset
      @kotlin.jvm.JvmName("getAsset")
        get() = _builder.asset
      @kotlin.jvm.JvmName("setAsset")
        set(value) {
        _builder.asset = value
      }
    /**
     * `.solra.crt.Asset asset = 2 [json_name = "asset"];`
     */
    public fun clearAsset() {
      _builder.clearAsset()
    }
    /**
     * `.solra.crt.Asset asset = 2 [json_name = "asset"];`
     * @return Whether the asset field is set.
     */
    public fun hasAsset(): kotlin.Boolean {
      return _builder.hasAsset()
    }

    public val UploadAssetResponseKt.Dsl.assetOrNull: com.solra.proto.crt.Crt.Asset?
      get() = _builder.assetOrNull

    /**
     * ```
     * 大文件预签名上传URL
     * ```
     *
     * `string upload_url = 3 [json_name = "uploadUrl"];`
     */
    public var uploadUrl: kotlin.String
      @kotlin.jvm.JvmName("getUploadUrl")
        get() = _builder.uploadUrl
      @kotlin.jvm.JvmName("setUploadUrl")
        set(value) {
        _builder.uploadUrl = value
      }
    /**
     * ```
     * 大文件预签名上传URL
     * ```
     *
     * `string upload_url = 3 [json_name = "uploadUrl"];`
     */
    public fun clearUploadUrl() {
      _builder.clearUploadUrl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.crt.Crt.UploadAssetResponse.copy(block: `com.solra.proto.crt`.UploadAssetResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.crt.Crt.UploadAssetResponse =
  `com.solra.proto.crt`.UploadAssetResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.crt.Crt.UploadAssetResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

public val com.solra.proto.crt.Crt.UploadAssetResponseOrBuilder.assetOrNull: com.solra.proto.crt.Crt.Asset?
  get() = if (hasAsset()) getAsset() else null

