// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializeaddBalanceRequest")
public inline fun addBalanceRequest(block: com.solra.proto.mon.AddBalanceRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.AddBalanceRequest =
  com.solra.proto.mon.AddBalanceRequestKt.Dsl._create(com.solra.proto.mon.Mon.AddBalanceRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.AddBalanceRequest`
 */
public object AddBalanceRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.AddBalanceRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.AddBalanceRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.AddBalanceRequest = _builder.build()

    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `.solra.mon.CurrencyType currency = 2 [json_name = "currency"];`
     */
    public var currency: com.solra.proto.mon.Mon.CurrencyType
      @kotlin.jvm.JvmName("getCurrency")
        get() = _builder.currency
      @kotlin.jvm.JvmName("setCurrency")
        set(value) {
        _builder.currency = value
      }
    public var currencyValue: kotlin.Int
      @kotlin.jvm.JvmName("getCurrencyValue")
        get() = _builder.currencyValue
      @kotlin.jvm.JvmName("setCurrencyValue")
        set(value) {
        _builder.currencyValue = value
      }
    /**
     * `.solra.mon.CurrencyType currency = 2 [json_name = "currency"];`
     */
    public fun clearCurrency() {
      _builder.clearCurrency()
    }

    /**
     * `int64 amount = 3 [json_name = "amount"];`
     */
    public var amount: kotlin.Long
      @kotlin.jvm.JvmName("getAmount")
        get() = _builder.amount
      @kotlin.jvm.JvmName("setAmount")
        set(value) {
        _builder.amount = value
      }
    /**
     * `int64 amount = 3 [json_name = "amount"];`
     */
    public fun clearAmount() {
      _builder.clearAmount()
    }

    /**
     * `string reason = 4 [json_name = "reason"];`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 4 [json_name = "reason"];`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.AddBalanceRequest.copy(block: `com.solra.proto.mon`.AddBalanceRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.AddBalanceRequest =
  `com.solra.proto.mon`.AddBalanceRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

