// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializeaddBalanceResponse")
public inline fun addBalanceResponse(block: com.solra.proto.mon.AddBalanceResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.AddBalanceResponse =
  com.solra.proto.mon.AddBalanceResponseKt.Dsl._create(com.solra.proto.mon.Mon.AddBalanceResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.AddBalanceResponse`
 */
public object AddBalanceResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.AddBalanceResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.AddBalanceResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.AddBalanceResponse = _builder.build()

    /**
     * `.solra.mon.VirtualWallet wallet = 1 [json_name = "wallet"];`
     */
    public var wallet: com.solra.proto.mon.Mon.VirtualWallet
      @kotlin.jvm.JvmName("getWallet")
        get() = _builder.wallet
      @kotlin.jvm.JvmName("setWallet")
        set(value) {
        _builder.wallet = value
      }
    /**
     * `.solra.mon.VirtualWallet wallet = 1 [json_name = "wallet"];`
     */
    public fun clearWallet() {
      _builder.clearWallet()
    }
    /**
     * `.solra.mon.VirtualWallet wallet = 1 [json_name = "wallet"];`
     * @return Whether the wallet field is set.
     */
    public fun hasWallet(): kotlin.Boolean {
      return _builder.hasWallet()
    }

    public val AddBalanceResponseKt.Dsl.walletOrNull: com.solra.proto.mon.Mon.VirtualWallet?
      get() = _builder.walletOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.AddBalanceResponse.copy(block: `com.solra.proto.mon`.AddBalanceResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.AddBalanceResponse =
  `com.solra.proto.mon`.AddBalanceResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.mon.Mon.AddBalanceResponseOrBuilder.walletOrNull: com.solra.proto.mon.Mon.VirtualWallet?
  get() = if (hasWallet()) getWallet() else null

