// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializecreateOrderResponse")
public inline fun createOrderResponse(block: com.solra.proto.mon.CreateOrderResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.CreateOrderResponse =
  com.solra.proto.mon.CreateOrderResponseKt.Dsl._create(com.solra.proto.mon.Mon.CreateOrderResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.CreateOrderResponse`
 */
public object CreateOrderResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.CreateOrderResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.CreateOrderResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.CreateOrderResponse = _builder.build()

    /**
     * `.solra.mon.Order order = 1 [json_name = "order"];`
     */
    public var order: com.solra.proto.mon.Mon.Order
      @kotlin.jvm.JvmName("getOrder")
        get() = _builder.order
      @kotlin.jvm.JvmName("setOrder")
        set(value) {
        _builder.order = value
      }
    /**
     * `.solra.mon.Order order = 1 [json_name = "order"];`
     */
    public fun clearOrder() {
      _builder.clearOrder()
    }
    /**
     * `.solra.mon.Order order = 1 [json_name = "order"];`
     * @return Whether the order field is set.
     */
    public fun hasOrder(): kotlin.Boolean {
      return _builder.hasOrder()
    }

    public val CreateOrderResponseKt.Dsl.orderOrNull: com.solra.proto.mon.Mon.Order?
      get() = _builder.orderOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.CreateOrderResponse.copy(block: `com.solra.proto.mon`.CreateOrderResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.CreateOrderResponse =
  `com.solra.proto.mon`.CreateOrderResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.mon.Mon.CreateOrderResponseOrBuilder.orderOrNull: com.solra.proto.mon.Mon.Order?
  get() = if (hasOrder()) getOrder() else null

