// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializecreateOrderRequest")
public inline fun createOrderRequest(block: com.solra.proto.mon.CreateOrderRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.CreateOrderRequest =
  com.solra.proto.mon.CreateOrderRequestKt.Dsl._create(com.solra.proto.mon.Mon.CreateOrderRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.CreateOrderRequest`
 */
public object CreateOrderRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.CreateOrderRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.CreateOrderRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.CreateOrderRequest = _builder.build()

    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ItemsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.mon.OrderItem items = 2 [json_name = "items"];`
     */
     public val items: com.google.protobuf.kotlin.DslList<com.solra.proto.mon.Mon.OrderItem, ItemsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.itemsList
      )
    /**
     * `repeated .solra.mon.OrderItem items = 2 [json_name = "items"];`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addItems")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.mon.Mon.OrderItem, ItemsProxy>.add(value: com.solra.proto.mon.Mon.OrderItem) {
      _builder.addItems(value)
    }
    /**
     * `repeated .solra.mon.OrderItem items = 2 [json_name = "items"];`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.mon.Mon.OrderItem, ItemsProxy>.plusAssign(value: com.solra.proto.mon.Mon.OrderItem) {
      add(value)
    }
    /**
     * `repeated .solra.mon.OrderItem items = 2 [json_name = "items"];`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllItems")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.mon.Mon.OrderItem, ItemsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.proto.mon.Mon.OrderItem>) {
      _builder.addAllItems(values)
    }
    /**
     * `repeated .solra.mon.OrderItem items = 2 [json_name = "items"];`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.mon.Mon.OrderItem, ItemsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.proto.mon.Mon.OrderItem>) {
      addAll(values)
    }
    /**
     * `repeated .solra.mon.OrderItem items = 2 [json_name = "items"];`
     * @param index The index to set the value at.
     * @param value The items to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setItems")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.mon.Mon.OrderItem, ItemsProxy>.set(index: kotlin.Int, value: com.solra.proto.mon.Mon.OrderItem) {
      _builder.setItems(index, value)
    }
    /**
     * `repeated .solra.mon.OrderItem items = 2 [json_name = "items"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearItems")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.mon.Mon.OrderItem, ItemsProxy>.clear() {
      _builder.clearItems()
    }

    /**
     * `.solra.mon.CurrencyType currency = 3 [json_name = "currency"];`
     */
    public var currency: com.solra.proto.mon.Mon.CurrencyType
      @kotlin.jvm.JvmName("getCurrency")
        get() = _builder.currency
      @kotlin.jvm.JvmName("setCurrency")
        set(value) {
        _builder.currency = value
      }
    public var currencyValue: kotlin.Int
      @kotlin.jvm.JvmName("getCurrencyValue")
        get() = _builder.currencyValue
      @kotlin.jvm.JvmName("setCurrencyValue")
        set(value) {
        _builder.currencyValue = value
      }
    /**
     * `.solra.mon.CurrencyType currency = 3 [json_name = "currency"];`
     */
    public fun clearCurrency() {
      _builder.clearCurrency()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.CreateOrderRequest.copy(block: `com.solra.proto.mon`.CreateOrderRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.CreateOrderRequest =
  `com.solra.proto.mon`.CreateOrderRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

