// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializegetWalletRequest")
public inline fun getWalletRequest(block: com.solra.proto.mon.GetWalletRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.GetWalletRequest =
  com.solra.proto.mon.GetWalletRequestKt.Dsl._create(com.solra.proto.mon.Mon.GetWalletRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.GetWalletRequest`
 */
public object GetWalletRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.GetWalletRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.GetWalletRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.GetWalletRequest = _builder.build()

    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.GetWalletRequest.copy(block: `com.solra.proto.mon`.GetWalletRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.GetWalletRequest =
  `com.solra.proto.mon`.GetWalletRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

