// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializeinventoryEntry")
public inline fun inventoryEntry(block: com.solra.proto.mon.InventoryEntryKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.InventoryEntry =
  com.solra.proto.mon.InventoryEntryKt.Dsl._create(com.solra.proto.mon.Mon.InventoryEntry.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.InventoryEntry`
 */
public object InventoryEntryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.InventoryEntry.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.InventoryEntry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.InventoryEntry = _builder.build()

    /**
     * `string item_id = 1 [json_name = "itemId"];`
     */
    public var itemId: kotlin.String
      @kotlin.jvm.JvmName("getItemId")
        get() = _builder.itemId
      @kotlin.jvm.JvmName("setItemId")
        set(value) {
        _builder.itemId = value
      }
    /**
     * `string item_id = 1 [json_name = "itemId"];`
     */
    public fun clearItemId() {
      _builder.clearItemId()
    }

    /**
     * `int32 quantity = 2 [json_name = "quantity"];`
     */
    public var quantity: kotlin.Int
      @kotlin.jvm.JvmName("getQuantity")
        get() = _builder.quantity
      @kotlin.jvm.JvmName("setQuantity")
        set(value) {
        _builder.quantity = value
      }
    /**
     * `int32 quantity = 2 [json_name = "quantity"];`
     */
    public fun clearQuantity() {
      _builder.clearQuantity()
    }

    /**
     * `int64 acquired_at = 3 [json_name = "acquiredAt"];`
     */
    public var acquiredAt: kotlin.Long
      @kotlin.jvm.JvmName("getAcquiredAt")
        get() = _builder.acquiredAt
      @kotlin.jvm.JvmName("setAcquiredAt")
        set(value) {
        _builder.acquiredAt = value
      }
    /**
     * `int64 acquired_at = 3 [json_name = "acquiredAt"];`
     */
    public fun clearAcquiredAt() {
      _builder.clearAcquiredAt()
    }

    /**
     * ```
     * 0=永久
     * ```
     *
     * `int64 expires_at = 4 [json_name = "expiresAt"];`
     */
    public var expiresAt: kotlin.Long
      @kotlin.jvm.JvmName("getExpiresAt")
        get() = _builder.expiresAt
      @kotlin.jvm.JvmName("setExpiresAt")
        set(value) {
        _builder.expiresAt = value
      }
    /**
     * ```
     * 0=永久
     * ```
     *
     * `int64 expires_at = 4 [json_name = "expiresAt"];`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.InventoryEntry.copy(block: `com.solra.proto.mon`.InventoryEntryKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.InventoryEntry =
  `com.solra.proto.mon`.InventoryEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

