// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializeorderItem")
public inline fun orderItem(block: com.solra.proto.mon.OrderItemKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.OrderItem =
  com.solra.proto.mon.OrderItemKt.Dsl._create(com.solra.proto.mon.Mon.OrderItem.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.OrderItem`
 */
public object OrderItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.OrderItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.OrderItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.OrderItem = _builder.build()

    /**
     * `string product_id = 1 [json_name = "productId"];`
     */
    public var productId: kotlin.String
      @kotlin.jvm.JvmName("getProductId")
        get() = _builder.productId
      @kotlin.jvm.JvmName("setProductId")
        set(value) {
        _builder.productId = value
      }
    /**
     * `string product_id = 1 [json_name = "productId"];`
     */
    public fun clearProductId() {
      _builder.clearProductId()
    }

    /**
     * `string product_name = 2 [json_name = "productName"];`
     */
    public var productName: kotlin.String
      @kotlin.jvm.JvmName("getProductName")
        get() = _builder.productName
      @kotlin.jvm.JvmName("setProductName")
        set(value) {
        _builder.productName = value
      }
    /**
     * `string product_name = 2 [json_name = "productName"];`
     */
    public fun clearProductName() {
      _builder.clearProductName()
    }

    /**
     * `int32 quantity = 3 [json_name = "quantity"];`
     */
    public var quantity: kotlin.Int
      @kotlin.jvm.JvmName("getQuantity")
        get() = _builder.quantity
      @kotlin.jvm.JvmName("setQuantity")
        set(value) {
        _builder.quantity = value
      }
    /**
     * `int32 quantity = 3 [json_name = "quantity"];`
     */
    public fun clearQuantity() {
      _builder.clearQuantity()
    }

    /**
     * ```
     * 单位：分
     * ```
     *
     * `int64 unit_price = 4 [json_name = "unitPrice"];`
     */
    public var unitPrice: kotlin.Long
      @kotlin.jvm.JvmName("getUnitPrice")
        get() = _builder.unitPrice
      @kotlin.jvm.JvmName("setUnitPrice")
        set(value) {
        _builder.unitPrice = value
      }
    /**
     * ```
     * 单位：分
     * ```
     *
     * `int64 unit_price = 4 [json_name = "unitPrice"];`
     */
    public fun clearUnitPrice() {
      _builder.clearUnitPrice()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.OrderItem.copy(block: `com.solra.proto.mon`.OrderItemKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.OrderItem =
  `com.solra.proto.mon`.OrderItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

