// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializeverifyPaymentRequest")
public inline fun verifyPaymentRequest(block: com.solra.proto.mon.VerifyPaymentRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.VerifyPaymentRequest =
  com.solra.proto.mon.VerifyPaymentRequestKt.Dsl._create(com.solra.proto.mon.Mon.VerifyPaymentRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.VerifyPaymentRequest`
 */
public object VerifyPaymentRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.VerifyPaymentRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.VerifyPaymentRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.VerifyPaymentRequest = _builder.build()

    /**
     * `string order_id = 1 [json_name = "orderId"];`
     */
    public var orderId: kotlin.String
      @kotlin.jvm.JvmName("getOrderId")
        get() = _builder.orderId
      @kotlin.jvm.JvmName("setOrderId")
        set(value) {
        _builder.orderId = value
      }
    /**
     * `string order_id = 1 [json_name = "orderId"];`
     */
    public fun clearOrderId() {
      _builder.clearOrderId()
    }

    /**
     * `string payment_channel = 2 [json_name = "paymentChannel"];`
     */
    public var paymentChannel: kotlin.String
      @kotlin.jvm.JvmName("getPaymentChannel")
        get() = _builder.paymentChannel
      @kotlin.jvm.JvmName("setPaymentChannel")
        set(value) {
        _builder.paymentChannel = value
      }
    /**
     * `string payment_channel = 2 [json_name = "paymentChannel"];`
     */
    public fun clearPaymentChannel() {
      _builder.clearPaymentChannel()
    }

    /**
     * ```
     * 支付平台回执
     * ```
     *
     * `string receipt = 3 [json_name = "receipt"];`
     */
    public var receipt: kotlin.String
      @kotlin.jvm.JvmName("getReceipt")
        get() = _builder.receipt
      @kotlin.jvm.JvmName("setReceipt")
        set(value) {
        _builder.receipt = value
      }
    /**
     * ```
     * 支付平台回执
     * ```
     *
     * `string receipt = 3 [json_name = "receipt"];`
     */
    public fun clearReceipt() {
      _builder.clearReceipt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.VerifyPaymentRequest.copy(block: `com.solra.proto.mon`.VerifyPaymentRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.VerifyPaymentRequest =
  `com.solra.proto.mon`.VerifyPaymentRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

