// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/mon/mon.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.mon;

@kotlin.jvm.JvmName("-initializevirtualWallet")
public inline fun virtualWallet(block: com.solra.proto.mon.VirtualWalletKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.VirtualWallet =
  com.solra.proto.mon.VirtualWalletKt.Dsl._create(com.solra.proto.mon.Mon.VirtualWallet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.mon.VirtualWallet`
 */
public object VirtualWalletKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.mon.Mon.VirtualWallet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.mon.Mon.VirtualWallet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.mon.Mon.VirtualWallet = _builder.build()

    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class BalancesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * CurrencyType -> 余额
     * ```
     *
     * `map<int32, int64> balances = 2 [json_name = "balances"];`
     */
     public val balances: com.google.protobuf.kotlin.DslMap<kotlin.Int, kotlin.Long, BalancesProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getBalancesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.balancesMap
      )
    /**
     * ```
     * CurrencyType -> 余额
     * ```
     *
     * `map<int32, int64> balances = 2 [json_name = "balances"];`
     */
    @kotlin.jvm.JvmName("putBalances")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.Int, kotlin.Long, BalancesProxy>
      .put(key: kotlin.Int, value: kotlin.Long) {
         _builder.putBalances(key, value)
       }
    /**
     * ```
     * CurrencyType -> 余额
     * ```
     *
     * `map<int32, int64> balances = 2 [json_name = "balances"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setBalances")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.Int, kotlin.Long, BalancesProxy>
      .set(key: kotlin.Int, value: kotlin.Long) {
         put(key, value)
       }
    /**
     * ```
     * CurrencyType -> 余额
     * ```
     *
     * `map<int32, int64> balances = 2 [json_name = "balances"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeBalances")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.Int, kotlin.Long, BalancesProxy>
      .remove(key: kotlin.Int) {
         _builder.removeBalances(key)
       }
    /**
     * ```
     * CurrencyType -> 余额
     * ```
     *
     * `map<int32, int64> balances = 2 [json_name = "balances"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllBalances")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.Int, kotlin.Long, BalancesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.Int, kotlin.Long>) {
         _builder.putAllBalances(map)
       }
    /**
     * ```
     * CurrencyType -> 余额
     * ```
     *
     * `map<int32, int64> balances = 2 [json_name = "balances"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearBalances")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.Int, kotlin.Long, BalancesProxy>
      .clear() {
         _builder.clearBalances()
       }

    /**
     * `int64 updated_at = 3 [json_name = "updatedAt"];`
     */
    public var updatedAt: kotlin.Long
      @kotlin.jvm.JvmName("getUpdatedAt")
        get() = _builder.updatedAt
      @kotlin.jvm.JvmName("setUpdatedAt")
        set(value) {
        _builder.updatedAt = value
      }
    /**
     * `int64 updated_at = 3 [json_name = "updatedAt"];`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.mon.Mon.VirtualWallet.copy(block: `com.solra.proto.mon`.VirtualWalletKt.Dsl.() -> kotlin.Unit): com.solra.proto.mon.Mon.VirtualWallet =
  `com.solra.proto.mon`.VirtualWalletKt.Dsl._create(this.toBuilder()).apply { block() }._build()

