// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/common/common.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.common;

@kotlin.jvm.JvmName("-initializeempty")
public inline fun empty(block: com.solra.apis.common.EmptyKt.Dsl.() -> kotlin.Unit): com.solra.apis.common.Common.Empty =
  com.solra.apis.common.EmptyKt.Dsl._create(com.solra.apis.common.Common.Empty.newBuilder()).apply { block() }._build()
/**
 * ```
 * Empty 空消息（用于无参数的RPC）
 * ```
 *
 * Protobuf type `solra.common.Empty`
 */
public object EmptyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.common.Common.Empty.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.common.Common.Empty.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.common.Common.Empty = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.common.Common.Empty.copy(block: `com.solra.apis.common`.EmptyKt.Dsl.() -> kotlin.Unit): com.solra.apis.common.Common.Empty =
  `com.solra.apis.common`.EmptyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

