// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/common/common.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.common;

@kotlin.jvm.JvmName("-initializegeoPoint")
public inline fun geoPoint(block: com.solra.apis.common.GeoPointKt.Dsl.() -> kotlin.Unit): com.solra.apis.common.Common.GeoPoint =
  com.solra.apis.common.GeoPointKt.Dsl._create(com.solra.apis.common.Common.GeoPoint.newBuilder()).apply { block() }._build()
/**
 * ```
 * GeoPoint 地理坐标点
 * ```
 *
 * Protobuf type `solra.common.GeoPoint`
 */
public object GeoPointKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.common.Common.GeoPoint.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.common.Common.GeoPoint.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.common.Common.GeoPoint = _builder.build()

    /**
     * `double latitude = 1 [json_name = "latitude"];`
     */
    public var latitude: kotlin.Double
      @kotlin.jvm.JvmName("getLatitude")
        get() = _builder.latitude
      @kotlin.jvm.JvmName("setLatitude")
        set(value) {
        _builder.latitude = value
      }
    /**
     * `double latitude = 1 [json_name = "latitude"];`
     */
    public fun clearLatitude() {
      _builder.clearLatitude()
    }

    /**
     * `double longitude = 2 [json_name = "longitude"];`
     */
    public var longitude: kotlin.Double
      @kotlin.jvm.JvmName("getLongitude")
        get() = _builder.longitude
      @kotlin.jvm.JvmName("setLongitude")
        set(value) {
        _builder.longitude = value
      }
    /**
     * `double longitude = 2 [json_name = "longitude"];`
     */
    public fun clearLongitude() {
      _builder.clearLongitude()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.common.Common.GeoPoint.copy(block: `com.solra.apis.common`.GeoPointKt.Dsl.() -> kotlin.Unit): com.solra.apis.common.Common.GeoPoint =
  `com.solra.apis.common`.GeoPointKt.Dsl._create(this.toBuilder()).apply { block() }._build()

