// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/common.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.common;

@kotlin.jvm.JvmName("-initializesolraError")
public inline fun solraError(block: com.solra.apis.common.SolraErrorKt.Dsl.() -> kotlin.Unit): com.solra.apis.common.Common.SolraError =
  com.solra.apis.common.SolraErrorKt.Dsl._create(com.solra.apis.common.Common.SolraError.newBuilder()).apply { block() }._build()
/**
 * ```
 * SolraError 统一错误响应
 * ```
 *
 * Protobuf type `solra.common.SolraError`
 */
public object SolraErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.common.Common.SolraError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.common.Common.SolraError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.common.Common.SolraError = _builder.build()

    /**
     * ```
     * 错误码
     * ```
     *
     * `.solra.common.ErrorCode code = 1 [json_name = "code"];`
     */
    public var code: com.solra.apis.common.Common.ErrorCode
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    public var codeValue: kotlin.Int
      @kotlin.jvm.JvmName("getCodeValue")
        get() = _builder.codeValue
      @kotlin.jvm.JvmName("setCodeValue")
        set(value) {
        _builder.codeValue = value
      }
    /**
     * ```
     * 错误码
     * ```
     *
     * `.solra.common.ErrorCode code = 1 [json_name = "code"];`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * ```
     * 人类可读的错误描述
     * ```
     *
     * `string message = 2 [json_name = "message"];`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * ```
     * 人类可读的错误描述
     * ```
     *
     * `string message = 2 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DetailsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 附加详情
     * ```
     *
     * `map<string, string> details = 3 [json_name = "details"];`
     */
     public val details: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getDetailsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.detailsMap
      )
    /**
     * ```
     * 附加详情
     * ```
     *
     * `map<string, string> details = 3 [json_name = "details"];`
     */
    @kotlin.jvm.JvmName("putDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putDetails(key, value)
       }
    /**
     * ```
     * 附加详情
     * ```
     *
     * `map<string, string> details = 3 [json_name = "details"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDetails")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * ```
     * 附加详情
     * ```
     *
     * `map<string, string> details = 3 [json_name = "details"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .remove(key: kotlin.String) {
         _builder.removeDetails(key)
       }
    /**
     * ```
     * 附加详情
     * ```
     *
     * `map<string, string> details = 3 [json_name = "details"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllDetails(map)
       }
    /**
     * ```
     * 附加详情
     * ```
     *
     * `map<string, string> details = 3 [json_name = "details"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .clear() {
         _builder.clearDetails()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.common.Common.SolraError.copy(block: `com.solra.apis.common`.SolraErrorKt.Dsl.() -> kotlin.Unit): com.solra.apis.common.Common.SolraError =
  `com.solra.apis.common`.SolraErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

