// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializeanimationConfig")
public inline fun animationConfig(block: com.solra.apis.avt.v1.AnimationConfigKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.AnimationConfig =
  com.solra.apis.avt.v1.AnimationConfigKt.Dsl._create(com.solra.apis.avt.v1.Avt.AnimationConfig.newBuilder()).apply { block() }._build()
/**
 * ```
 * AnimationConfig 动画配置
 * ```
 *
 * Protobuf type `solra.avt.v1.AnimationConfig`
 */
public object AnimationConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.AnimationConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.AnimationConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.AnimationConfig = _builder.build()

    /**
     * ```
     * 手势速度
     * ```
     *
     * `float gesture_speed = 1 [json_name = "gestureSpeed"];`
     */
    public var gestureSpeed: kotlin.Float
      @kotlin.jvm.JvmName("getGestureSpeed")
        get() = _builder.gestureSpeed
      @kotlin.jvm.JvmName("setGestureSpeed")
        set(value) {
        _builder.gestureSpeed = value
      }
    /**
     * ```
     * 手势速度
     * ```
     *
     * `float gesture_speed = 1 [json_name = "gestureSpeed"];`
     */
    public fun clearGestureSpeed() {
      _builder.clearGestureSpeed()
    }

    /**
     * ```
     * 表情强度
     * ```
     *
     * `float expression_intensity = 2 [json_name = "expressionIntensity"];`
     */
    public var expressionIntensity: kotlin.Float
      @kotlin.jvm.JvmName("getExpressionIntensity")
        get() = _builder.expressionIntensity
      @kotlin.jvm.JvmName("setExpressionIntensity")
        set(value) {
        _builder.expressionIntensity = value
      }
    /**
     * ```
     * 表情强度
     * ```
     *
     * `float expression_intensity = 2 [json_name = "expressionIntensity"];`
     */
    public fun clearExpressionIntensity() {
      _builder.clearExpressionIntensity()
    }

    /**
     * ```
     * 自动眨眼
     * ```
     *
     * `bool auto_blink = 3 [json_name = "autoBlink"];`
     */
    public var autoBlink: kotlin.Boolean
      @kotlin.jvm.JvmName("getAutoBlink")
        get() = _builder.autoBlink
      @kotlin.jvm.JvmName("setAutoBlink")
        set(value) {
        _builder.autoBlink = value
      }
    /**
     * ```
     * 自动眨眼
     * ```
     *
     * `bool auto_blink = 3 [json_name = "autoBlink"];`
     */
    public fun clearAutoBlink() {
      _builder.clearAutoBlink()
    }

    /**
     * ```
     * 自动手势
     * ```
     *
     * `bool auto_gesture = 4 [json_name = "autoGesture"];`
     */
    public var autoGesture: kotlin.Boolean
      @kotlin.jvm.JvmName("getAutoGesture")
        get() = _builder.autoGesture
      @kotlin.jvm.JvmName("setAutoGesture")
        set(value) {
        _builder.autoGesture = value
      }
    /**
     * ```
     * 自动手势
     * ```
     *
     * `bool auto_gesture = 4 [json_name = "autoGesture"];`
     */
    public fun clearAutoGesture() {
      _builder.clearAutoGesture()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.AnimationConfig.copy(block: `com.solra.apis.avt.v1`.AnimationConfigKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.AnimationConfig =
  `com.solra.apis.avt.v1`.AnimationConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

