// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializeapplyEmotionEventRequest")
public inline fun applyEmotionEventRequest(block: com.solra.apis.avt.v1.ApplyEmotionEventRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.ApplyEmotionEventRequest =
  com.solra.apis.avt.v1.ApplyEmotionEventRequestKt.Dsl._create(com.solra.apis.avt.v1.Avt.ApplyEmotionEventRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.avt.v1.ApplyEmotionEventRequest`
 */
public object ApplyEmotionEventRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.ApplyEmotionEventRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.ApplyEmotionEventRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.ApplyEmotionEventRequest = _builder.build()

    /**
     * `string avatar_id = 1 [json_name = "avatarId"];`
     */
    public var avatarId: kotlin.String
      @kotlin.jvm.JvmName("getAvatarId")
        get() = _builder.avatarId
      @kotlin.jvm.JvmName("setAvatarId")
        set(value) {
        _builder.avatarId = value
      }
    /**
     * `string avatar_id = 1 [json_name = "avatarId"];`
     */
    public fun clearAvatarId() {
      _builder.clearAvatarId()
    }

    /**
     * ```
     * USER_COMPLIMENT/USER_INSULT/USER_IGNORED/...
     * ```
     *
     * `string event_type = 2 [json_name = "eventType"];`
     */
    public var eventType: kotlin.String
      @kotlin.jvm.JvmName("getEventType")
        get() = _builder.eventType
      @kotlin.jvm.JvmName("setEventType")
        set(value) {
        _builder.eventType = value
      }
    /**
     * ```
     * USER_COMPLIMENT/USER_INSULT/USER_IGNORED/...
     * ```
     *
     * `string event_type = 2 [json_name = "eventType"];`
     */
    public fun clearEventType() {
      _builder.clearEventType()
    }

    /**
     * `float intensity = 3 [json_name = "intensity"];`
     */
    public var intensity: kotlin.Float
      @kotlin.jvm.JvmName("getIntensity")
        get() = _builder.intensity
      @kotlin.jvm.JvmName("setIntensity")
        set(value) {
        _builder.intensity = value
      }
    /**
     * `float intensity = 3 [json_name = "intensity"];`
     */
    public fun clearIntensity() {
      _builder.clearIntensity()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.ApplyEmotionEventRequest.copy(block: `com.solra.apis.avt.v1`.ApplyEmotionEventRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.ApplyEmotionEventRequest =
  `com.solra.apis.avt.v1`.ApplyEmotionEventRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

