// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: avt/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializeavatarConfig")
public inline fun avatarConfig(block: com.solra.apis.avt.v1.AvatarConfigKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.AvatarConfig =
  com.solra.apis.avt.v1.AvatarConfigKt.Dsl._create(com.solra.apis.avt.v1.Avt.AvatarConfig.newBuilder()).apply { block() }._build()
/**
 * ```
 * AvatarConfig 虚拟人配置
 * ```
 *
 * Protobuf type `solra.avt.v1.AvatarConfig`
 */
public object AvatarConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.AvatarConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.AvatarConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.AvatarConfig = _builder.build()

    /**
     * ```
     * 3D模型ID
     * ```
     *
     * `string model_id = 1 [json_name = "modelId"];`
     */
    public var modelId: kotlin.String
      @kotlin.jvm.JvmName("getModelId")
        get() = _builder.modelId
      @kotlin.jvm.JvmName("setModelId")
        set(value) {
        _builder.modelId = value
      }
    /**
     * ```
     * 3D模型ID
     * ```
     *
     * `string model_id = 1 [json_name = "modelId"];`
     */
    public fun clearModelId() {
      _builder.clearModelId()
    }

    /**
     * ```
     * 语音模型ID
     * ```
     *
     * `string voice_id = 2 [json_name = "voiceId"];`
     */
    public var voiceId: kotlin.String
      @kotlin.jvm.JvmName("getVoiceId")
        get() = _builder.voiceId
      @kotlin.jvm.JvmName("setVoiceId")
        set(value) {
        _builder.voiceId = value
      }
    /**
     * ```
     * 语音模型ID
     * ```
     *
     * `string voice_id = 2 [json_name = "voiceId"];`
     */
    public fun clearVoiceId() {
      _builder.clearVoiceId()
    }

    /**
     * ```
     * 主要语言（BCP-47）
     * ```
     *
     * `string language_code = 3 [json_name = "languageCode"];`
     */
    public var languageCode: kotlin.String
      @kotlin.jvm.JvmName("getLanguageCode")
        get() = _builder.languageCode
      @kotlin.jvm.JvmName("setLanguageCode")
        set(value) {
        _builder.languageCode = value
      }
    /**
     * ```
     * 主要语言（BCP-47）
     * ```
     *
     * `string language_code = 3 [json_name = "languageCode"];`
     */
    public fun clearLanguageCode() {
      _builder.clearLanguageCode()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SupportedLanguagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string supported_languages = 4 [json_name = "supportedLanguages"];`
     * @return A list containing the supportedLanguages.
     */
    public val supportedLanguages: com.google.protobuf.kotlin.DslList<kotlin.String, SupportedLanguagesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.supportedLanguagesList
      )
    /**
     * `repeated string supported_languages = 4 [json_name = "supportedLanguages"];`
     * @param value The supportedLanguages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSupportedLanguages")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedLanguagesProxy>.add(value: kotlin.String) {
      _builder.addSupportedLanguages(value)
    }
    /**
     * `repeated string supported_languages = 4 [json_name = "supportedLanguages"];`
     * @param value The supportedLanguages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSupportedLanguages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedLanguagesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string supported_languages = 4 [json_name = "supportedLanguages"];`
     * @param values The supportedLanguages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSupportedLanguages")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedLanguagesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllSupportedLanguages(values)
    }
    /**
     * `repeated string supported_languages = 4 [json_name = "supportedLanguages"];`
     * @param values The supportedLanguages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSupportedLanguages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedLanguagesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string supported_languages = 4 [json_name = "supportedLanguages"];`
     * @param index The index to set the value at.
     * @param value The supportedLanguages to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSupportedLanguages")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedLanguagesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setSupportedLanguages(index, value)
    }/**
     * `repeated string supported_languages = 4 [json_name = "supportedLanguages"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSupportedLanguages")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SupportedLanguagesProxy>.clear() {
      _builder.clearSupportedLanguages()
    }
    /**
     * ```
     * 外观配置
     * ```
     *
     * `.solra.avt.v1.AvatarAppearance appearance = 5 [json_name = "appearance"];`
     */
    public var appearance: com.solra.apis.avt.v1.Avt.AvatarAppearance
      @kotlin.jvm.JvmName("getAppearance")
        get() = _builder.appearance
      @kotlin.jvm.JvmName("setAppearance")
        set(value) {
        _builder.appearance = value
      }
    /**
     * ```
     * 外观配置
     * ```
     *
     * `.solra.avt.v1.AvatarAppearance appearance = 5 [json_name = "appearance"];`
     */
    public fun clearAppearance() {
      _builder.clearAppearance()
    }
    /**
     * ```
     * 外观配置
     * ```
     *
     * `.solra.avt.v1.AvatarAppearance appearance = 5 [json_name = "appearance"];`
     * @return Whether the appearance field is set.
     */
    public fun hasAppearance(): kotlin.Boolean {
      return _builder.hasAppearance()
    }

    public val AvatarConfigKt.Dsl.appearanceOrNull: com.solra.apis.avt.v1.Avt.AvatarAppearance?
      get() = _builder.appearanceOrNull

    /**
     * ```
     * 动画配置
     * ```
     *
     * `.solra.avt.v1.AnimationConfig animation = 6 [json_name = "animation"];`
     */
    public var animation: com.solra.apis.avt.v1.Avt.AnimationConfig
      @kotlin.jvm.JvmName("getAnimation")
        get() = _builder.animation
      @kotlin.jvm.JvmName("setAnimation")
        set(value) {
        _builder.animation = value
      }
    /**
     * ```
     * 动画配置
     * ```
     *
     * `.solra.avt.v1.AnimationConfig animation = 6 [json_name = "animation"];`
     */
    public fun clearAnimation() {
      _builder.clearAnimation()
    }
    /**
     * ```
     * 动画配置
     * ```
     *
     * `.solra.avt.v1.AnimationConfig animation = 6 [json_name = "animation"];`
     * @return Whether the animation field is set.
     */
    public fun hasAnimation(): kotlin.Boolean {
      return _builder.hasAnimation()
    }

    public val AvatarConfigKt.Dsl.animationOrNull: com.solra.apis.avt.v1.Avt.AnimationConfig?
      get() = _builder.animationOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.AvatarConfig.copy(block: `com.solra.apis.avt.v1`.AvatarConfigKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.AvatarConfig =
  `com.solra.apis.avt.v1`.AvatarConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.avt.v1.Avt.AvatarConfigOrBuilder.appearanceOrNull: com.solra.apis.avt.v1.Avt.AvatarAppearance?
  get() = if (hasAppearance()) getAppearance() else null

public val com.solra.apis.avt.v1.Avt.AvatarConfigOrBuilder.animationOrNull: com.solra.apis.avt.v1.Avt.AnimationConfig?
  get() = if (hasAnimation()) getAnimation() else null

