// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: avt/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializeconversation")
public inline fun conversation(block: com.solra.apis.avt.v1.ConversationKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.Conversation =
  com.solra.apis.avt.v1.ConversationKt.Dsl._create(com.solra.apis.avt.v1.Avt.Conversation.newBuilder()).apply { block() }._build()
/**
 * ```
 * Conversation 对话
 * ```
 *
 * Protobuf type `solra.avt.v1.Conversation`
 */
public object ConversationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.Conversation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.Conversation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.Conversation = _builder.build()

    /**
     * `.solra.common.ConversationId conversation_id = 1 [json_name = "conversationId"];`
     */
    public var conversationId: com.solra.apis.common.Common.ConversationId
      @kotlin.jvm.JvmName("getConversationId")
        get() = _builder.conversationId
      @kotlin.jvm.JvmName("setConversationId")
        set(value) {
        _builder.conversationId = value
      }
    /**
     * `.solra.common.ConversationId conversation_id = 1 [json_name = "conversationId"];`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }
    /**
     * `.solra.common.ConversationId conversation_id = 1 [json_name = "conversationId"];`
     * @return Whether the conversationId field is set.
     */
    public fun hasConversationId(): kotlin.Boolean {
      return _builder.hasConversationId()
    }

    public val ConversationKt.Dsl.conversationIdOrNull: com.solra.apis.common.Common.ConversationId?
      get() = _builder.conversationIdOrNull

    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val ConversationKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `.solra.common.SpaceId space_id = 3 [json_name = "spaceId"];`
     */
    public var spaceId: com.solra.apis.common.Common.SpaceId
      @kotlin.jvm.JvmName("getSpaceId")
        get() = _builder.spaceId
      @kotlin.jvm.JvmName("setSpaceId")
        set(value) {
        _builder.spaceId = value
      }
    /**
     * `.solra.common.SpaceId space_id = 3 [json_name = "spaceId"];`
     */
    public fun clearSpaceId() {
      _builder.clearSpaceId()
    }
    /**
     * `.solra.common.SpaceId space_id = 3 [json_name = "spaceId"];`
     * @return Whether the spaceId field is set.
     */
    public fun hasSpaceId(): kotlin.Boolean {
      return _builder.hasSpaceId()
    }

    public val ConversationKt.Dsl.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
      get() = _builder.spaceIdOrNull

    /**
     * `string avatar_id = 4 [json_name = "avatarId"];`
     */
    public var avatarId: kotlin.String
      @kotlin.jvm.JvmName("getAvatarId")
        get() = _builder.avatarId
      @kotlin.jvm.JvmName("setAvatarId")
        set(value) {
        _builder.avatarId = value
      }
    /**
     * `string avatar_id = 4 [json_name = "avatarId"];`
     */
    public fun clearAvatarId() {
      _builder.clearAvatarId()
    }

    /**
     * `.solra.avt.v1.ConversationStatus status = 5 [json_name = "status"];`
     */
    public var status: com.solra.apis.avt.v1.Avt.ConversationStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.solra.avt.v1.ConversationStatus status = 5 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.solra.common.SolraTimestamp created_at = 6 [json_name = "createdAt"];`
     */
    public var createdAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `.solra.common.SolraTimestamp created_at = 6 [json_name = "createdAt"];`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * `.solra.common.SolraTimestamp created_at = 6 [json_name = "createdAt"];`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    public val ConversationKt.Dsl.createdAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.createdAtOrNull

    /**
     * `.solra.common.SolraTimestamp updated_at = 7 [json_name = "updatedAt"];`
     */
    public var updatedAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getUpdatedAt")
        get() = _builder.updatedAt
      @kotlin.jvm.JvmName("setUpdatedAt")
        set(value) {
        _builder.updatedAt = value
      }
    /**
     * `.solra.common.SolraTimestamp updated_at = 7 [json_name = "updatedAt"];`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }
    /**
     * `.solra.common.SolraTimestamp updated_at = 7 [json_name = "updatedAt"];`
     * @return Whether the updatedAt field is set.
     */
    public fun hasUpdatedAt(): kotlin.Boolean {
      return _builder.hasUpdatedAt()
    }

    public val ConversationKt.Dsl.updatedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.updatedAtOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MetadataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> metadata = 8 [json_name = "metadata"];`
     */
     public val metadata: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getMetadataMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.metadataMap
      )
    /**
     * `map<string, string> metadata = 8 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmName("putMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putMetadata(key, value)
       }
    /**
     * `map<string, string> metadata = 8 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMetadata")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> metadata = 8 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .remove(key: kotlin.String) {
         _builder.removeMetadata(key)
       }
    /**
     * `map<string, string> metadata = 8 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllMetadata(map)
       }
    /**
     * `map<string, string> metadata = 8 [json_name = "metadata"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMetadata")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
      .clear() {
         _builder.clearMetadata()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.Conversation.copy(block: `com.solra.apis.avt.v1`.ConversationKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.Conversation =
  `com.solra.apis.avt.v1`.ConversationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.avt.v1.Avt.ConversationOrBuilder.conversationIdOrNull: com.solra.apis.common.Common.ConversationId?
  get() = if (hasConversationId()) getConversationId() else null

public val com.solra.apis.avt.v1.Avt.ConversationOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

public val com.solra.apis.avt.v1.Avt.ConversationOrBuilder.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
  get() = if (hasSpaceId()) getSpaceId() else null

public val com.solra.apis.avt.v1.Avt.ConversationOrBuilder.createdAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

public val com.solra.apis.avt.v1.Avt.ConversationOrBuilder.updatedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasUpdatedAt()) getUpdatedAt() else null

