// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializeemotionVector")
public inline fun emotionVector(block: com.solra.apis.avt.v1.EmotionVectorKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.EmotionVector =
  com.solra.apis.avt.v1.EmotionVectorKt.Dsl._create(com.solra.apis.avt.v1.Avt.EmotionVector.newBuilder()).apply { block() }._build()
/**
 * ```
 * EmotionVector 情感向量
 * ```
 *
 * Protobuf type `solra.avt.v1.EmotionVector`
 */
public object EmotionVectorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.EmotionVector.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.EmotionVector.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.EmotionVector = _builder.build()

    /**
     * `string vector_id = 1 [json_name = "vectorId"];`
     */
    public var vectorId: kotlin.String
      @kotlin.jvm.JvmName("getVectorId")
        get() = _builder.vectorId
      @kotlin.jvm.JvmName("setVectorId")
        set(value) {
        _builder.vectorId = value
      }
    /**
     * `string vector_id = 1 [json_name = "vectorId"];`
     */
    public fun clearVectorId() {
      _builder.clearVectorId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ValuesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated float values = 2 [json_name = "values"];`
     */
     public val values: com.google.protobuf.kotlin.DslList<kotlin.Float, ValuesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.valuesList
      )
    /**
     * `repeated float values = 2 [json_name = "values"];`
     * @param value The values to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addValues")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, ValuesProxy>.add(value: kotlin.Float) {
      _builder.addValues(value)
    }/**
     * `repeated float values = 2 [json_name = "values"];`
     * @param value The values to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, ValuesProxy>.plusAssign(value: kotlin.Float) {
      add(value)
    }/**
     * `repeated float values = 2 [json_name = "values"];`
     * @param values The values to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllValues")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, ValuesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Float>) {
      _builder.addAllValues(values)
    }/**
     * `repeated float values = 2 [json_name = "values"];`
     * @param values The values to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, ValuesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Float>) {
      addAll(values)
    }/**
     * `repeated float values = 2 [json_name = "values"];`
     * @param index The index to set the value at.
     * @param value The values to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setValues")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, ValuesProxy>.set(index: kotlin.Int, value: kotlin.Float) {
      _builder.setValues(index, value)
    }/**
     * `repeated float values = 2 [json_name = "values"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearValues")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, ValuesProxy>.clear() {
      _builder.clearValues()
    }
    /**
     * `string model_version = 3 [json_name = "modelVersion"];`
     */
    public var modelVersion: kotlin.String
      @kotlin.jvm.JvmName("getModelVersion")
        get() = _builder.modelVersion
      @kotlin.jvm.JvmName("setModelVersion")
        set(value) {
        _builder.modelVersion = value
      }
    /**
     * `string model_version = 3 [json_name = "modelVersion"];`
     */
    public fun clearModelVersion() {
      _builder.clearModelVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.EmotionVector.copy(block: `com.solra.apis.avt.v1`.EmotionVectorKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.EmotionVector =
  `com.solra.apis.avt.v1`.EmotionVectorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

