// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: avt/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializeemotionDimension")
public inline fun emotionDimension(block: com.solra.apis.avt.v1.EmotionDimensionKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.EmotionDimension =
  com.solra.apis.avt.v1.EmotionDimensionKt.Dsl._create(com.solra.apis.avt.v1.Avt.EmotionDimension.newBuilder()).apply { block() }._build()
/**
 * ```
 * EmotionDimension PAD三维情感维度（Pleasure-Arousal-Dominance）
 * ```
 *
 * Protobuf type `solra.avt.v1.EmotionDimension`
 */
public object EmotionDimensionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.EmotionDimension.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.EmotionDimension.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.EmotionDimension = _builder.build()

    /**
     * ```
     * pleasure / arousal / dominance
     * ```
     *
     * `string dimension_name = 1 [json_name = "dimensionName"];`
     */
    public var dimensionName: kotlin.String
      @kotlin.jvm.JvmName("getDimensionName")
        get() = _builder.dimensionName
      @kotlin.jvm.JvmName("setDimensionName")
        set(value) {
        _builder.dimensionName = value
      }
    /**
     * ```
     * pleasure / arousal / dominance
     * ```
     *
     * `string dimension_name = 1 [json_name = "dimensionName"];`
     */
    public fun clearDimensionName() {
      _builder.clearDimensionName()
    }

    /**
     * ```
     * -1.0 到 1.0
     * ```
     *
     * `float value = 2 [json_name = "value"];`
     */
    public var value: kotlin.Float
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * ```
     * -1.0 到 1.0
     * ```
     *
     * `float value = 2 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.EmotionDimension.copy(block: `com.solra.apis.avt.v1`.EmotionDimensionKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.EmotionDimension =
  `com.solra.apis.avt.v1`.EmotionDimensionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

