// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializeevaluateSurpriseResponse")
public inline fun evaluateSurpriseResponse(block: com.solra.apis.avt.v1.EvaluateSurpriseResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponse =
  com.solra.apis.avt.v1.EvaluateSurpriseResponseKt.Dsl._create(com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.avt.v1.EvaluateSurpriseResponse`
 */
public object EvaluateSurpriseResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponse = _builder.build()

    /**
     * `bool triggered = 1 [json_name = "triggered"];`
     */
    public var triggered: kotlin.Boolean
      @kotlin.jvm.JvmName("getTriggered")
        get() = _builder.triggered
      @kotlin.jvm.JvmName("setTriggered")
        set(value) {
        _builder.triggered = value
      }
    /**
     * `bool triggered = 1 [json_name = "triggered"];`
     */
    public fun clearTriggered() {
      _builder.clearTriggered()
    }

    /**
     * `.solra.avt.v1.SurpriseMomentDTO moment = 2 [json_name = "moment"];`
     */
    public var moment: com.solra.apis.avt.v1.Avt.SurpriseMomentDTO
      @kotlin.jvm.JvmName("getMoment")
        get() = _builder.moment
      @kotlin.jvm.JvmName("setMoment")
        set(value) {
        _builder.moment = value
      }
    /**
     * `.solra.avt.v1.SurpriseMomentDTO moment = 2 [json_name = "moment"];`
     */
    public fun clearMoment() {
      _builder.clearMoment()
    }
    /**
     * `.solra.avt.v1.SurpriseMomentDTO moment = 2 [json_name = "moment"];`
     * @return Whether the moment field is set.
     */
    public fun hasMoment(): kotlin.Boolean {
      return _builder.hasMoment()
    }

    public val EvaluateSurpriseResponseKt.Dsl.momentOrNull: com.solra.apis.avt.v1.Avt.SurpriseMomentDTO?
      get() = _builder.momentOrNull

    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val EvaluateSurpriseResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponse.copy(block: `com.solra.apis.avt.v1`.EvaluateSurpriseResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponse =
  `com.solra.apis.avt.v1`.EvaluateSurpriseResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponseOrBuilder.momentOrNull: com.solra.apis.avt.v1.Avt.SurpriseMomentDTO?
  get() = if (hasMoment()) getMoment() else null

public val com.solra.apis.avt.v1.Avt.EvaluateSurpriseResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

