// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializegetAvatarExpressionRequest")
public inline fun getAvatarExpressionRequest(block: com.solra.apis.avt.v1.GetAvatarExpressionRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.GetAvatarExpressionRequest =
  com.solra.apis.avt.v1.GetAvatarExpressionRequestKt.Dsl._create(com.solra.apis.avt.v1.Avt.GetAvatarExpressionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.avt.v1.GetAvatarExpressionRequest`
 */
public object GetAvatarExpressionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.GetAvatarExpressionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.GetAvatarExpressionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.GetAvatarExpressionRequest = _builder.build()

    /**
     * `string avatar_id = 1 [json_name = "avatarId"];`
     */
    public var avatarId: kotlin.String
      @kotlin.jvm.JvmName("getAvatarId")
        get() = _builder.avatarId
      @kotlin.jvm.JvmName("setAvatarId")
        set(value) {
        _builder.avatarId = value
      }
    /**
     * `string avatar_id = 1 [json_name = "avatarId"];`
     */
    public fun clearAvatarId() {
      _builder.clearAvatarId()
    }

    /**
     * ```
     * optional: specific type override
     * ```
     *
     * `string expression_type = 2 [json_name = "expressionType"];`
     */
    public var expressionType: kotlin.String
      @kotlin.jvm.JvmName("getExpressionType")
        get() = _builder.expressionType
      @kotlin.jvm.JvmName("setExpressionType")
        set(value) {
        _builder.expressionType = value
      }
    /**
     * ```
     * optional: specific type override
     * ```
     *
     * `string expression_type = 2 [json_name = "expressionType"];`
     */
    public fun clearExpressionType() {
      _builder.clearExpressionType()
    }

    /**
     * ```
     * optional: specific intensity override
     * ```
     *
     * `float intensity = 3 [json_name = "intensity"];`
     */
    public var intensity: kotlin.Float
      @kotlin.jvm.JvmName("getIntensity")
        get() = _builder.intensity
      @kotlin.jvm.JvmName("setIntensity")
        set(value) {
        _builder.intensity = value
      }
    /**
     * ```
     * optional: specific intensity override
     * ```
     *
     * `float intensity = 3 [json_name = "intensity"];`
     */
    public fun clearIntensity() {
      _builder.clearIntensity()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.GetAvatarExpressionRequest.copy(block: `com.solra.apis.avt.v1`.GetAvatarExpressionRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.GetAvatarExpressionRequest =
  `com.solra.apis.avt.v1`.GetAvatarExpressionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

