// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializegetAvatarStateRequest")
public inline fun getAvatarStateRequest(block: com.solra.apis.avt.v1.GetAvatarStateRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.GetAvatarStateRequest =
  com.solra.apis.avt.v1.GetAvatarStateRequestKt.Dsl._create(com.solra.apis.avt.v1.Avt.GetAvatarStateRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * GetAvatarState
 * ```
 *
 * Protobuf type `solra.avt.v1.GetAvatarStateRequest`
 */
public object GetAvatarStateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.GetAvatarStateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.GetAvatarStateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.GetAvatarStateRequest = _builder.build()

    /**
     * `string avatar_id = 1 [json_name = "avatarId"];`
     */
    public var avatarId: kotlin.String
      @kotlin.jvm.JvmName("getAvatarId")
        get() = _builder.avatarId
      @kotlin.jvm.JvmName("setAvatarId")
        set(value) {
        _builder.avatarId = value
      }
    /**
     * `string avatar_id = 1 [json_name = "avatarId"];`
     */
    public fun clearAvatarId() {
      _builder.clearAvatarId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.GetAvatarStateRequest.copy(block: `com.solra.apis.avt.v1`.GetAvatarStateRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.GetAvatarStateRequest =
  `com.solra.apis.avt.v1`.GetAvatarStateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

