// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializegetLongTermMemoryRequest")
public inline fun getLongTermMemoryRequest(block: com.solra.apis.avt.v1.GetLongTermMemoryRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.GetLongTermMemoryRequest =
  com.solra.apis.avt.v1.GetLongTermMemoryRequestKt.Dsl._create(com.solra.apis.avt.v1.Avt.GetLongTermMemoryRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.avt.v1.GetLongTermMemoryRequest`
 */
public object GetLongTermMemoryRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.GetLongTermMemoryRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.GetLongTermMemoryRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.GetLongTermMemoryRequest = _builder.build()

    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val GetLongTermMemoryRequestKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `string avatar_id = 2 [json_name = "avatarId"];`
     */
    public var avatarId: kotlin.String
      @kotlin.jvm.JvmName("getAvatarId")
        get() = _builder.avatarId
      @kotlin.jvm.JvmName("setAvatarId")
        set(value) {
        _builder.avatarId = value
      }
    /**
     * `string avatar_id = 2 [json_name = "avatarId"];`
     */
    public fun clearAvatarId() {
      _builder.clearAvatarId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.GetLongTermMemoryRequest.copy(block: `com.solra.apis.avt.v1`.GetLongTermMemoryRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.GetLongTermMemoryRequest =
  `com.solra.apis.avt.v1`.GetLongTermMemoryRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.avt.v1.Avt.GetLongTermMemoryRequestOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

