// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializememorySummaryDTO")
public inline fun memorySummaryDTO(block: com.solra.apis.avt.v1.MemorySummaryDTOKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.MemorySummaryDTO =
  com.solra.apis.avt.v1.MemorySummaryDTOKt.Dsl._create(com.solra.apis.avt.v1.Avt.MemorySummaryDTO.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.avt.v1.MemorySummaryDTO`
 */
public object MemorySummaryDTOKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.MemorySummaryDTO.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.MemorySummaryDTO.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.MemorySummaryDTO = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class KnownFactsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string known_facts = 1 [json_name = "knownFacts"];`
     * @return A list containing the knownFacts.
     */
    public val knownFacts: com.google.protobuf.kotlin.DslList<kotlin.String, KnownFactsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.knownFactsList
      )
    /**
     * `repeated string known_facts = 1 [json_name = "knownFacts"];`
     * @param value The knownFacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addKnownFacts")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, KnownFactsProxy>.add(value: kotlin.String) {
      _builder.addKnownFacts(value)
    }
    /**
     * `repeated string known_facts = 1 [json_name = "knownFacts"];`
     * @param value The knownFacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignKnownFacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, KnownFactsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string known_facts = 1 [json_name = "knownFacts"];`
     * @param values The knownFacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllKnownFacts")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, KnownFactsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllKnownFacts(values)
    }
    /**
     * `repeated string known_facts = 1 [json_name = "knownFacts"];`
     * @param values The knownFacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllKnownFacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, KnownFactsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string known_facts = 1 [json_name = "knownFacts"];`
     * @param index The index to set the value at.
     * @param value The knownFacts to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setKnownFacts")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, KnownFactsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setKnownFacts(index, value)
    }/**
     * `repeated string known_facts = 1 [json_name = "knownFacts"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setKnownFacts")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, KnownFactsProxy>.clear() {
      _builder.clearKnownFacts()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PreferencesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string preferences = 2 [json_name = "preferences"];`
     * @return A list containing the preferences.
     */
    public val preferences: com.google.protobuf.kotlin.DslList<kotlin.String, PreferencesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.preferencesList
      )
    /**
     * `repeated string preferences = 2 [json_name = "preferences"];`
     * @param value The preferences to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPreferences")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PreferencesProxy>.add(value: kotlin.String) {
      _builder.addPreferences(value)
    }
    /**
     * `repeated string preferences = 2 [json_name = "preferences"];`
     * @param value The preferences to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPreferences")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PreferencesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string preferences = 2 [json_name = "preferences"];`
     * @param values The preferences to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPreferences")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PreferencesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPreferences(values)
    }
    /**
     * `repeated string preferences = 2 [json_name = "preferences"];`
     * @param values The preferences to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPreferences")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PreferencesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string preferences = 2 [json_name = "preferences"];`
     * @param index The index to set the value at.
     * @param value The preferences to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPreferences")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PreferencesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setPreferences(index, value)
    }/**
     * `repeated string preferences = 2 [json_name = "preferences"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPreferences")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PreferencesProxy>.clear() {
      _builder.clearPreferences()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TopicsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string topics = 3 [json_name = "topics"];`
     * @return A list containing the topics.
     */
    public val topics: com.google.protobuf.kotlin.DslList<kotlin.String, TopicsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.topicsList
      )
    /**
     * `repeated string topics = 3 [json_name = "topics"];`
     * @param value The topics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TopicsProxy>.add(value: kotlin.String) {
      _builder.addTopics(value)
    }
    /**
     * `repeated string topics = 3 [json_name = "topics"];`
     * @param value The topics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignTopics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TopicsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string topics = 3 [json_name = "topics"];`
     * @param values The topics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TopicsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTopics(values)
    }
    /**
     * `repeated string topics = 3 [json_name = "topics"];`
     * @param values The topics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllTopics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TopicsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string topics = 3 [json_name = "topics"];`
     * @param index The index to set the value at.
     * @param value The topics to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setTopics")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TopicsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTopics(index, value)
    }/**
     * `repeated string topics = 3 [json_name = "topics"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TopicsProxy>.clear() {
      _builder.clearTopics()
    }
    /**
     * `string relationship_stage = 4 [json_name = "relationshipStage"];`
     */
    public var relationshipStage: kotlin.String
      @kotlin.jvm.JvmName("getRelationshipStage")
        get() = _builder.relationshipStage
      @kotlin.jvm.JvmName("setRelationshipStage")
        set(value) {
        _builder.relationshipStage = value
      }
    /**
     * `string relationship_stage = 4 [json_name = "relationshipStage"];`
     */
    public fun clearRelationshipStage() {
      _builder.clearRelationshipStage()
    }

    /**
     * `int32 total_interactions = 5 [json_name = "totalInteractions"];`
     */
    public var totalInteractions: kotlin.Int
      @kotlin.jvm.JvmName("getTotalInteractions")
        get() = _builder.totalInteractions
      @kotlin.jvm.JvmName("setTotalInteractions")
        set(value) {
        _builder.totalInteractions = value
      }
    /**
     * `int32 total_interactions = 5 [json_name = "totalInteractions"];`
     */
    public fun clearTotalInteractions() {
      _builder.clearTotalInteractions()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.MemorySummaryDTO.copy(block: `com.solra.apis.avt.v1`.MemorySummaryDTOKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.MemorySummaryDTO =
  `com.solra.apis.avt.v1`.MemorySummaryDTOKt.Dsl._create(this.toBuilder()).apply { block() }._build()

