// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializemessageAttachment")
public inline fun messageAttachment(block: com.solra.apis.avt.v1.MessageAttachmentKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.MessageAttachment =
  com.solra.apis.avt.v1.MessageAttachmentKt.Dsl._create(com.solra.apis.avt.v1.Avt.MessageAttachment.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.avt.v1.MessageAttachment`
 */
public object MessageAttachmentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.MessageAttachment.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.MessageAttachment.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.MessageAttachment = _builder.build()

    /**
     * ```
     * image / audio / file
     * ```
     *
     * `string attachment_type = 1 [json_name = "attachmentType"];`
     */
    public var attachmentType: kotlin.String
      @kotlin.jvm.JvmName("getAttachmentType")
        get() = _builder.attachmentType
      @kotlin.jvm.JvmName("setAttachmentType")
        set(value) {
        _builder.attachmentType = value
      }
    /**
     * ```
     * image / audio / file
     * ```
     *
     * `string attachment_type = 1 [json_name = "attachmentType"];`
     */
    public fun clearAttachmentType() {
      _builder.clearAttachmentType()
    }

    /**
     * `string url = 2 [json_name = "url"];`
     */
    public var url: kotlin.String
      @kotlin.jvm.JvmName("getUrl")
        get() = _builder.url
      @kotlin.jvm.JvmName("setUrl")
        set(value) {
        _builder.url = value
      }
    /**
     * `string url = 2 [json_name = "url"];`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * `string mime_type = 3 [json_name = "mimeType"];`
     */
    public var mimeType: kotlin.String
      @kotlin.jvm.JvmName("getMimeType")
        get() = _builder.mimeType
      @kotlin.jvm.JvmName("setMimeType")
        set(value) {
        _builder.mimeType = value
      }
    /**
     * `string mime_type = 3 [json_name = "mimeType"];`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }

    /**
     * `int64 size_bytes = 4 [json_name = "sizeBytes"];`
     */
    public var sizeBytes: kotlin.Long
      @kotlin.jvm.JvmName("getSizeBytes")
        get() = _builder.sizeBytes
      @kotlin.jvm.JvmName("setSizeBytes")
        set(value) {
        _builder.sizeBytes = value
      }
    /**
     * `int64 size_bytes = 4 [json_name = "sizeBytes"];`
     */
    public fun clearSizeBytes() {
      _builder.clearSizeBytes()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.MessageAttachment.copy(block: `com.solra.apis.avt.v1`.MessageAttachmentKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.MessageAttachment =
  `com.solra.apis.avt.v1`.MessageAttachmentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

