// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: avt/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializequeryMemoryRequest")
public inline fun queryMemoryRequest(block: com.solra.apis.avt.v1.QueryMemoryRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.QueryMemoryRequest =
  com.solra.apis.avt.v1.QueryMemoryRequestKt.Dsl._create(com.solra.apis.avt.v1.Avt.QueryMemoryRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * QueryMemory
 * ```
 *
 * Protobuf type `solra.avt.v1.QueryMemoryRequest`
 */
public object QueryMemoryRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.QueryMemoryRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.QueryMemoryRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.QueryMemoryRequest = _builder.build()

    /**
     * `.solra.avt.v1.MemoryQuery query = 1 [json_name = "query"];`
     */
    public var query: com.solra.apis.avt.v1.Avt.MemoryQuery
      @kotlin.jvm.JvmName("getQuery")
        get() = _builder.query
      @kotlin.jvm.JvmName("setQuery")
        set(value) {
        _builder.query = value
      }
    /**
     * `.solra.avt.v1.MemoryQuery query = 1 [json_name = "query"];`
     */
    public fun clearQuery() {
      _builder.clearQuery()
    }
    /**
     * `.solra.avt.v1.MemoryQuery query = 1 [json_name = "query"];`
     * @return Whether the query field is set.
     */
    public fun hasQuery(): kotlin.Boolean {
      return _builder.hasQuery()
    }

    public val QueryMemoryRequestKt.Dsl.queryOrNull: com.solra.apis.avt.v1.Avt.MemoryQuery?
      get() = _builder.queryOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.QueryMemoryRequest.copy(block: `com.solra.apis.avt.v1`.QueryMemoryRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.QueryMemoryRequest =
  `com.solra.apis.avt.v1`.QueryMemoryRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.avt.v1.Avt.QueryMemoryRequestOrBuilder.queryOrNull: com.solra.apis.avt.v1.Avt.MemoryQuery?
  get() = if (hasQuery()) getQuery() else null

