// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializesendMessageRequest")
public inline fun sendMessageRequest(block: com.solra.apis.avt.v1.SendMessageRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.SendMessageRequest =
  com.solra.apis.avt.v1.SendMessageRequestKt.Dsl._create(com.solra.apis.avt.v1.Avt.SendMessageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * SendMessage
 * ```
 *
 * Protobuf type `solra.avt.v1.SendMessageRequest`
 */
public object SendMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.SendMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.SendMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.SendMessageRequest = _builder.build()

    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val SendMessageRequestKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `.solra.common.SpaceId space_id = 2 [json_name = "spaceId"];`
     */
    public var spaceId: com.solra.apis.common.Common.SpaceId
      @kotlin.jvm.JvmName("getSpaceId")
        get() = _builder.spaceId
      @kotlin.jvm.JvmName("setSpaceId")
        set(value) {
        _builder.spaceId = value
      }
    /**
     * `.solra.common.SpaceId space_id = 2 [json_name = "spaceId"];`
     */
    public fun clearSpaceId() {
      _builder.clearSpaceId()
    }
    /**
     * `.solra.common.SpaceId space_id = 2 [json_name = "spaceId"];`
     * @return Whether the spaceId field is set.
     */
    public fun hasSpaceId(): kotlin.Boolean {
      return _builder.hasSpaceId()
    }

    public val SendMessageRequestKt.Dsl.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
      get() = _builder.spaceIdOrNull

    /**
     * `string conversation_id = 3 [json_name = "conversationId"];`
     */
    public var conversationId: kotlin.String
      @kotlin.jvm.JvmName("getConversationId")
        get() = _builder.conversationId
      @kotlin.jvm.JvmName("setConversationId")
        set(value) {
        _builder.conversationId = value
      }
    /**
     * `string conversation_id = 3 [json_name = "conversationId"];`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }

    /**
     * `string content = 4 [json_name = "content"];`
     */
    public var content: kotlin.String
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `string content = 4 [json_name = "content"];`
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AttachmentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.avt.v1.MessageAttachment attachments = 5 [json_name = "attachments"];`
     */
     public val attachments: com.google.protobuf.kotlin.DslList<com.solra.apis.avt.v1.Avt.MessageAttachment, AttachmentsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.attachmentsList
      )
    /**
     * `repeated .solra.avt.v1.MessageAttachment attachments = 5 [json_name = "attachments"];`
     * @param value The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.avt.v1.Avt.MessageAttachment, AttachmentsProxy>.add(value: com.solra.apis.avt.v1.Avt.MessageAttachment) {
      _builder.addAttachments(value)
    }
    /**
     * `repeated .solra.avt.v1.MessageAttachment attachments = 5 [json_name = "attachments"];`
     * @param value The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAttachments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.avt.v1.Avt.MessageAttachment, AttachmentsProxy>.plusAssign(value: com.solra.apis.avt.v1.Avt.MessageAttachment) {
      add(value)
    }
    /**
     * `repeated .solra.avt.v1.MessageAttachment attachments = 5 [json_name = "attachments"];`
     * @param values The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.avt.v1.Avt.MessageAttachment, AttachmentsProxy>.addAll(values: kotlin.collections.Iterable<com.solra.apis.avt.v1.Avt.MessageAttachment>) {
      _builder.addAllAttachments(values)
    }
    /**
     * `repeated .solra.avt.v1.MessageAttachment attachments = 5 [json_name = "attachments"];`
     * @param values The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAttachments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.avt.v1.Avt.MessageAttachment, AttachmentsProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.apis.avt.v1.Avt.MessageAttachment>) {
      addAll(values)
    }
    /**
     * `repeated .solra.avt.v1.MessageAttachment attachments = 5 [json_name = "attachments"];`
     * @param index The index to set the value at.
     * @param value The attachments to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAttachments")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.apis.avt.v1.Avt.MessageAttachment, AttachmentsProxy>.set(index: kotlin.Int, value: com.solra.apis.avt.v1.Avt.MessageAttachment) {
      _builder.setAttachments(index, value)
    }
    /**
     * `repeated .solra.avt.v1.MessageAttachment attachments = 5 [json_name = "attachments"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.solra.apis.avt.v1.Avt.MessageAttachment, AttachmentsProxy>.clear() {
      _builder.clearAttachments()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ContextProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 上下文信息
     * ```
     *
     * `map<string, string> context = 6 [json_name = "context"];`
     */
     public val context: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ContextProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getContextMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.contextMap
      )
    /**
     * ```
     * 上下文信息
     * ```
     *
     * `map<string, string> context = 6 [json_name = "context"];`
     */
    @kotlin.jvm.JvmName("putContext")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ContextProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putContext(key, value)
       }
    /**
     * ```
     * 上下文信息
     * ```
     *
     * `map<string, string> context = 6 [json_name = "context"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setContext")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ContextProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * ```
     * 上下文信息
     * ```
     *
     * `map<string, string> context = 6 [json_name = "context"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeContext")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ContextProxy>
      .remove(key: kotlin.String) {
         _builder.removeContext(key)
       }
    /**
     * ```
     * 上下文信息
     * ```
     *
     * `map<string, string> context = 6 [json_name = "context"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllContext")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ContextProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllContext(map)
       }
    /**
     * ```
     * 上下文信息
     * ```
     *
     * `map<string, string> context = 6 [json_name = "context"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearContext")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ContextProxy>
      .clear() {
         _builder.clearContext()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.SendMessageRequest.copy(block: `com.solra.apis.avt.v1`.SendMessageRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.SendMessageRequest =
  `com.solra.apis.avt.v1`.SendMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.avt.v1.Avt.SendMessageRequestOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

public val com.solra.apis.avt.v1.Avt.SendMessageRequestOrBuilder.spaceIdOrNull: com.solra.apis.common.Common.SpaceId?
  get() = if (hasSpaceId()) getSpaceId() else null

