// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializesurpriseMomentDTO")
public inline fun surpriseMomentDTO(block: com.solra.apis.avt.v1.SurpriseMomentDTOKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.SurpriseMomentDTO =
  com.solra.apis.avt.v1.SurpriseMomentDTOKt.Dsl._create(com.solra.apis.avt.v1.Avt.SurpriseMomentDTO.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.avt.v1.SurpriseMomentDTO`
 */
public object SurpriseMomentDTOKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.SurpriseMomentDTO.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.SurpriseMomentDTO.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.SurpriseMomentDTO = _builder.build()

    /**
     * `string surprise_id = 1 [json_name = "surpriseId"];`
     */
    public var surpriseId: kotlin.String
      @kotlin.jvm.JvmName("getSurpriseId")
        get() = _builder.surpriseId
      @kotlin.jvm.JvmName("setSurpriseId")
        set(value) {
        _builder.surpriseId = value
      }
    /**
     * `string surprise_id = 1 [json_name = "surpriseId"];`
     */
    public fun clearSurpriseId() {
      _builder.clearSurpriseId()
    }

    /**
     * `string user_id = 2 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 2 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string conversation_id = 3 [json_name = "conversationId"];`
     */
    public var conversationId: kotlin.String
      @kotlin.jvm.JvmName("getConversationId")
        get() = _builder.conversationId
      @kotlin.jvm.JvmName("setConversationId")
        set(value) {
        _builder.conversationId = value
      }
    /**
     * `string conversation_id = 3 [json_name = "conversationId"];`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }

    /**
     * ```
     * MEMORY_RECALL/EMOTIONAL_EXPRESSION/PERSONALIZED_INTERACTION/RANDOM_SURPRISE
     * ```
     *
     * `string surprise_type = 4 [json_name = "surpriseType"];`
     */
    public var surpriseType: kotlin.String
      @kotlin.jvm.JvmName("getSurpriseType")
        get() = _builder.surpriseType
      @kotlin.jvm.JvmName("setSurpriseType")
        set(value) {
        _builder.surpriseType = value
      }
    /**
     * ```
     * MEMORY_RECALL/EMOTIONAL_EXPRESSION/PERSONALIZED_INTERACTION/RANDOM_SURPRISE
     * ```
     *
     * `string surprise_type = 4 [json_name = "surpriseType"];`
     */
    public fun clearSurpriseType() {
      _builder.clearSurpriseType()
    }

    /**
     * `string message = 5 [json_name = "message"];`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 5 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `.solra.avt.v1.AvatarExpressionDTO expression = 6 [json_name = "expression"];`
     */
    public var expression: com.solra.apis.avt.v1.Avt.AvatarExpressionDTO
      @kotlin.jvm.JvmName("getExpression")
        get() = _builder.expression
      @kotlin.jvm.JvmName("setExpression")
        set(value) {
        _builder.expression = value
      }
    /**
     * `.solra.avt.v1.AvatarExpressionDTO expression = 6 [json_name = "expression"];`
     */
    public fun clearExpression() {
      _builder.clearExpression()
    }
    /**
     * `.solra.avt.v1.AvatarExpressionDTO expression = 6 [json_name = "expression"];`
     * @return Whether the expression field is set.
     */
    public fun hasExpression(): kotlin.Boolean {
      return _builder.hasExpression()
    }

    public val SurpriseMomentDTOKt.Dsl.expressionOrNull: com.solra.apis.avt.v1.Avt.AvatarExpressionDTO?
      get() = _builder.expressionOrNull

    /**
     * `.solra.common.SolraTimestamp generated_at = 7 [json_name = "generatedAt"];`
     */
    public var generatedAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getGeneratedAt")
        get() = _builder.generatedAt
      @kotlin.jvm.JvmName("setGeneratedAt")
        set(value) {
        _builder.generatedAt = value
      }
    /**
     * `.solra.common.SolraTimestamp generated_at = 7 [json_name = "generatedAt"];`
     */
    public fun clearGeneratedAt() {
      _builder.clearGeneratedAt()
    }
    /**
     * `.solra.common.SolraTimestamp generated_at = 7 [json_name = "generatedAt"];`
     * @return Whether the generatedAt field is set.
     */
    public fun hasGeneratedAt(): kotlin.Boolean {
      return _builder.hasGeneratedAt()
    }

    public val SurpriseMomentDTOKt.Dsl.generatedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.generatedAtOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.SurpriseMomentDTO.copy(block: `com.solra.apis.avt.v1`.SurpriseMomentDTOKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.SurpriseMomentDTO =
  `com.solra.apis.avt.v1`.SurpriseMomentDTOKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.avt.v1.Avt.SurpriseMomentDTOOrBuilder.expressionOrNull: com.solra.apis.avt.v1.Avt.AvatarExpressionDTO?
  get() = if (hasExpression()) getExpression() else null

public val com.solra.apis.avt.v1.Avt.SurpriseMomentDTOOrBuilder.generatedAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasGeneratedAt()) getGeneratedAt() else null

