// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/avt/v1/avt.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.avt.v1;

@kotlin.jvm.JvmName("-initializeupdateEmotionStateRequest")
public inline fun updateEmotionStateRequest(block: com.solra.apis.avt.v1.UpdateEmotionStateRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.UpdateEmotionStateRequest =
  com.solra.apis.avt.v1.UpdateEmotionStateRequestKt.Dsl._create(com.solra.apis.avt.v1.Avt.UpdateEmotionStateRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * UpdateEmotionState
 * ```
 *
 * Protobuf type `solra.avt.v1.UpdateEmotionStateRequest`
 */
public object UpdateEmotionStateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.avt.v1.Avt.UpdateEmotionStateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.avt.v1.Avt.UpdateEmotionStateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.avt.v1.Avt.UpdateEmotionStateRequest = _builder.build()

    /**
     * `string avatar_id = 1 [json_name = "avatarId"];`
     */
    public var avatarId: kotlin.String
      @kotlin.jvm.JvmName("getAvatarId")
        get() = _builder.avatarId
      @kotlin.jvm.JvmName("setAvatarId")
        set(value) {
        _builder.avatarId = value
      }
    /**
     * `string avatar_id = 1 [json_name = "avatarId"];`
     */
    public fun clearAvatarId() {
      _builder.clearAvatarId()
    }

    /**
     * `.solra.avt.v1.EmotionState emotion = 2 [json_name = "emotion"];`
     */
    public var emotion: com.solra.apis.avt.v1.Avt.EmotionState
      @kotlin.jvm.JvmName("getEmotion")
        get() = _builder.emotion
      @kotlin.jvm.JvmName("setEmotion")
        set(value) {
        _builder.emotion = value
      }
    /**
     * `.solra.avt.v1.EmotionState emotion = 2 [json_name = "emotion"];`
     */
    public fun clearEmotion() {
      _builder.clearEmotion()
    }
    /**
     * `.solra.avt.v1.EmotionState emotion = 2 [json_name = "emotion"];`
     * @return Whether the emotion field is set.
     */
    public fun hasEmotion(): kotlin.Boolean {
      return _builder.hasEmotion()
    }

    public val UpdateEmotionStateRequestKt.Dsl.emotionOrNull: com.solra.apis.avt.v1.Avt.EmotionState?
      get() = _builder.emotionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.avt.v1.Avt.UpdateEmotionStateRequest.copy(block: `com.solra.apis.avt.v1`.UpdateEmotionStateRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.avt.v1.Avt.UpdateEmotionStateRequest =
  `com.solra.apis.avt.v1`.UpdateEmotionStateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.avt.v1.Avt.UpdateEmotionStateRequestOrBuilder.emotionOrNull: com.solra.apis.avt.v1.Avt.EmotionState?
  get() = if (hasEmotion()) getEmotion() else null

