// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/auth/v1/auth.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.auth.v1;

@kotlin.jvm.JvmName("-initializegetCurrentUserRequest")
public inline fun getCurrentUserRequest(block: com.solra.apis.auth.v1.GetCurrentUserRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.GetCurrentUserRequest =
  com.solra.apis.auth.v1.GetCurrentUserRequestKt.Dsl._create(com.solra.apis.auth.v1.Auth.GetCurrentUserRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * GetCurrentUser
 * ```
 *
 * Protobuf type `solra.auth.v1.GetCurrentUserRequest`
 */
public object GetCurrentUserRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.auth.v1.Auth.GetCurrentUserRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.auth.v1.Auth.GetCurrentUserRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.auth.v1.Auth.GetCurrentUserRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.auth.v1.Auth.GetCurrentUserRequest.copy(block: `com.solra.apis.auth.v1`.GetCurrentUserRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.GetCurrentUserRequest =
  `com.solra.apis.auth.v1`.GetCurrentUserRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

