// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.auth.v1;

@kotlin.jvm.JvmName("-initializeloginSession")
public inline fun loginSession(block: com.solra.apis.auth.v1.LoginSessionKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.LoginSession =
  com.solra.apis.auth.v1.LoginSessionKt.Dsl._create(com.solra.apis.auth.v1.Auth.LoginSession.newBuilder()).apply { block() }._build()
/**
 * ```
 * LoginSession 登录会话
 * ```
 *
 * Protobuf type `solra.auth.v1.LoginSession`
 */
public object LoginSessionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.auth.v1.Auth.LoginSession.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.auth.v1.Auth.LoginSession.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.auth.v1.Auth.LoginSession = _builder.build()

    /**
     * `.solra.common.SessionId session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: com.solra.apis.common.Common.SessionId
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `.solra.common.SessionId session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }
    /**
     * `.solra.common.SessionId session_id = 1 [json_name = "sessionId"];`
     * @return Whether the sessionId field is set.
     */
    public fun hasSessionId(): kotlin.Boolean {
      return _builder.hasSessionId()
    }

    public val LoginSessionKt.Dsl.sessionIdOrNull: com.solra.apis.common.Common.SessionId?
      get() = _builder.sessionIdOrNull

    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 2 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val LoginSessionKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `.solra.auth.v1.LoginMethod method = 3 [json_name = "method"];`
     */
    public var method: com.solra.apis.auth.v1.Auth.LoginMethod
      @kotlin.jvm.JvmName("getMethod")
        get() = _builder.method
      @kotlin.jvm.JvmName("setMethod")
        set(value) {
        _builder.method = value
      }
    public var methodValue: kotlin.Int
      @kotlin.jvm.JvmName("getMethodValue")
        get() = _builder.methodValue
      @kotlin.jvm.JvmName("setMethodValue")
        set(value) {
        _builder.methodValue = value
      }
    /**
     * `.solra.auth.v1.LoginMethod method = 3 [json_name = "method"];`
     */
    public fun clearMethod() {
      _builder.clearMethod()
    }

    /**
     * ```
     * 设备信息
     * ```
     *
     * `string device_info = 4 [json_name = "deviceInfo"];`
     */
    public var deviceInfo: kotlin.String
      @kotlin.jvm.JvmName("getDeviceInfo")
        get() = _builder.deviceInfo
      @kotlin.jvm.JvmName("setDeviceInfo")
        set(value) {
        _builder.deviceInfo = value
      }
    /**
     * ```
     * 设备信息
     * ```
     *
     * `string device_info = 4 [json_name = "deviceInfo"];`
     */
    public fun clearDeviceInfo() {
      _builder.clearDeviceInfo()
    }

    /**
     * ```
     * 登录IP
     * ```
     *
     * `string ip_address = 5 [json_name = "ipAddress"];`
     */
    public var ipAddress: kotlin.String
      @kotlin.jvm.JvmName("getIpAddress")
        get() = _builder.ipAddress
      @kotlin.jvm.JvmName("setIpAddress")
        set(value) {
        _builder.ipAddress = value
      }
    /**
     * ```
     * 登录IP
     * ```
     *
     * `string ip_address = 5 [json_name = "ipAddress"];`
     */
    public fun clearIpAddress() {
      _builder.clearIpAddress()
    }

    /**
     * ```
     * 登录位置
     * ```
     *
     * `.solra.common.GeoPoint location = 6 [json_name = "location"];`
     */
    public var location: com.solra.apis.common.Common.GeoPoint
      @kotlin.jvm.JvmName("getLocation")
        get() = _builder.location
      @kotlin.jvm.JvmName("setLocation")
        set(value) {
        _builder.location = value
      }
    /**
     * ```
     * 登录位置
     * ```
     *
     * `.solra.common.GeoPoint location = 6 [json_name = "location"];`
     */
    public fun clearLocation() {
      _builder.clearLocation()
    }
    /**
     * ```
     * 登录位置
     * ```
     *
     * `.solra.common.GeoPoint location = 6 [json_name = "location"];`
     * @return Whether the location field is set.
     */
    public fun hasLocation(): kotlin.Boolean {
      return _builder.hasLocation()
    }

    public val LoginSessionKt.Dsl.locationOrNull: com.solra.apis.common.Common.GeoPoint?
      get() = _builder.locationOrNull

    /**
     * `string access_token = 7 [json_name = "accessToken"];`
     */
    public var accessToken: kotlin.String
      @kotlin.jvm.JvmName("getAccessToken")
        get() = _builder.accessToken
      @kotlin.jvm.JvmName("setAccessToken")
        set(value) {
        _builder.accessToken = value
      }
    /**
     * `string access_token = 7 [json_name = "accessToken"];`
     */
    public fun clearAccessToken() {
      _builder.clearAccessToken()
    }

    /**
     * `string refresh_token = 8 [json_name = "refreshToken"];`
     */
    public var refreshToken: kotlin.String
      @kotlin.jvm.JvmName("getRefreshToken")
        get() = _builder.refreshToken
      @kotlin.jvm.JvmName("setRefreshToken")
        set(value) {
        _builder.refreshToken = value
      }
    /**
     * `string refresh_token = 8 [json_name = "refreshToken"];`
     */
    public fun clearRefreshToken() {
      _builder.clearRefreshToken()
    }

    /**
     * `.solra.auth.v1.TokenType token_type = 9 [json_name = "tokenType"];`
     */
    public var tokenType: com.solra.apis.auth.v1.Auth.TokenType
      @kotlin.jvm.JvmName("getTokenType")
        get() = _builder.tokenType
      @kotlin.jvm.JvmName("setTokenType")
        set(value) {
        _builder.tokenType = value
      }
    public var tokenTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTokenTypeValue")
        get() = _builder.tokenTypeValue
      @kotlin.jvm.JvmName("setTokenTypeValue")
        set(value) {
        _builder.tokenTypeValue = value
      }
    /**
     * `.solra.auth.v1.TokenType token_type = 9 [json_name = "tokenType"];`
     */
    public fun clearTokenType() {
      _builder.clearTokenType()
    }

    /**
     * `.solra.common.SolraTimestamp expires_at = 10 [json_name = "expiresAt"];`
     */
    public var expiresAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getExpiresAt")
        get() = _builder.expiresAt
      @kotlin.jvm.JvmName("setExpiresAt")
        set(value) {
        _builder.expiresAt = value
      }
    /**
     * `.solra.common.SolraTimestamp expires_at = 10 [json_name = "expiresAt"];`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }
    /**
     * `.solra.common.SolraTimestamp expires_at = 10 [json_name = "expiresAt"];`
     * @return Whether the expiresAt field is set.
     */
    public fun hasExpiresAt(): kotlin.Boolean {
      return _builder.hasExpiresAt()
    }

    public val LoginSessionKt.Dsl.expiresAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.expiresAtOrNull

    /**
     * `.solra.common.SolraTimestamp created_at = 11 [json_name = "createdAt"];`
     */
    public var createdAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `.solra.common.SolraTimestamp created_at = 11 [json_name = "createdAt"];`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * `.solra.common.SolraTimestamp created_at = 11 [json_name = "createdAt"];`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    public val LoginSessionKt.Dsl.createdAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.createdAtOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.auth.v1.Auth.LoginSession.copy(block: `com.solra.apis.auth.v1`.LoginSessionKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.LoginSession =
  `com.solra.apis.auth.v1`.LoginSessionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.auth.v1.Auth.LoginSessionOrBuilder.sessionIdOrNull: com.solra.apis.common.Common.SessionId?
  get() = if (hasSessionId()) getSessionId() else null

public val com.solra.apis.auth.v1.Auth.LoginSessionOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

public val com.solra.apis.auth.v1.Auth.LoginSessionOrBuilder.locationOrNull: com.solra.apis.common.Common.GeoPoint?
  get() = if (hasLocation()) getLocation() else null

public val com.solra.apis.auth.v1.Auth.LoginSessionOrBuilder.expiresAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasExpiresAt()) getExpiresAt() else null

public val com.solra.apis.auth.v1.Auth.LoginSessionOrBuilder.createdAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

