// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/auth/v1/auth.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.auth.v1;

@kotlin.jvm.JvmName("-initializelogoutResponse")
public inline fun logoutResponse(block: com.solra.apis.auth.v1.LogoutResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.LogoutResponse =
  com.solra.apis.auth.v1.LogoutResponseKt.Dsl._create(com.solra.apis.auth.v1.Auth.LogoutResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.auth.v1.LogoutResponse`
 */
public object LogoutResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.auth.v1.Auth.LogoutResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.auth.v1.Auth.LogoutResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.auth.v1.Auth.LogoutResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val LogoutResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.auth.v1.Auth.LogoutResponse.copy(block: `com.solra.apis.auth.v1`.LogoutResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.LogoutResponse =
  `com.solra.apis.auth.v1`.LogoutResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.auth.v1.Auth.LogoutResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

