// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/auth/v1/auth.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.auth.v1;

@kotlin.jvm.JvmName("-initializeoAuthLoginResponse")
public inline fun oAuthLoginResponse(block: com.solra.apis.auth.v1.OAuthLoginResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.OAuthLoginResponse =
  com.solra.apis.auth.v1.OAuthLoginResponseKt.Dsl._create(com.solra.apis.auth.v1.Auth.OAuthLoginResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.auth.v1.OAuthLoginResponse`
 */
public object OAuthLoginResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.auth.v1.Auth.OAuthLoginResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.auth.v1.Auth.OAuthLoginResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.auth.v1.Auth.OAuthLoginResponse = _builder.build()

    /**
     * `.solra.auth.v1.LoginSession session = 1 [json_name = "session"];`
     */
    public var session: com.solra.apis.auth.v1.Auth.LoginSession
      @kotlin.jvm.JvmName("getSession")
        get() = _builder.session
      @kotlin.jvm.JvmName("setSession")
        set(value) {
        _builder.session = value
      }
    /**
     * `.solra.auth.v1.LoginSession session = 1 [json_name = "session"];`
     */
    public fun clearSession() {
      _builder.clearSession()
    }
    /**
     * `.solra.auth.v1.LoginSession session = 1 [json_name = "session"];`
     * @return Whether the session field is set.
     */
    public fun hasSession(): kotlin.Boolean {
      return _builder.hasSession()
    }

    public val OAuthLoginResponseKt.Dsl.sessionOrNull: com.solra.apis.auth.v1.Auth.LoginSession?
      get() = _builder.sessionOrNull

    /**
     * `.solra.auth.v1.UserAccount account = 2 [json_name = "account"];`
     */
    public var account: com.solra.apis.auth.v1.Auth.UserAccount
      @kotlin.jvm.JvmName("getAccount")
        get() = _builder.account
      @kotlin.jvm.JvmName("setAccount")
        set(value) {
        _builder.account = value
      }
    /**
     * `.solra.auth.v1.UserAccount account = 2 [json_name = "account"];`
     */
    public fun clearAccount() {
      _builder.clearAccount()
    }
    /**
     * `.solra.auth.v1.UserAccount account = 2 [json_name = "account"];`
     * @return Whether the account field is set.
     */
    public fun hasAccount(): kotlin.Boolean {
      return _builder.hasAccount()
    }

    public val OAuthLoginResponseKt.Dsl.accountOrNull: com.solra.apis.auth.v1.Auth.UserAccount?
      get() = _builder.accountOrNull

    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 3 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val OAuthLoginResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.auth.v1.Auth.OAuthLoginResponse.copy(block: `com.solra.apis.auth.v1`.OAuthLoginResponseKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.OAuthLoginResponse =
  `com.solra.apis.auth.v1`.OAuthLoginResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.auth.v1.Auth.OAuthLoginResponseOrBuilder.sessionOrNull: com.solra.apis.auth.v1.Auth.LoginSession?
  get() = if (hasSession()) getSession() else null

public val com.solra.apis.auth.v1.Auth.OAuthLoginResponseOrBuilder.accountOrNull: com.solra.apis.auth.v1.Auth.UserAccount?
  get() = if (hasAccount()) getAccount() else null

public val com.solra.apis.auth.v1.Auth.OAuthLoginResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

