// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/auth/v1/auth.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.auth.v1;

@kotlin.jvm.JvmName("-initializepermission")
public inline fun permission(block: com.solra.apis.auth.v1.PermissionKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.Permission =
  com.solra.apis.auth.v1.PermissionKt.Dsl._create(com.solra.apis.auth.v1.Auth.Permission.newBuilder()).apply { block() }._build()
/**
 * ```
 * Permission 权限
 * ```
 *
 * Protobuf type `solra.auth.v1.Permission`
 */
public object PermissionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.auth.v1.Auth.Permission.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.auth.v1.Auth.Permission.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.auth.v1.Auth.Permission = _builder.build()

    /**
     * `string permission_id = 1 [json_name = "permissionId"];`
     */
    public var permissionId: kotlin.String
      @kotlin.jvm.JvmName("getPermissionId")
        get() = _builder.permissionId
      @kotlin.jvm.JvmName("setPermissionId")
        set(value) {
        _builder.permissionId = value
      }
    /**
     * `string permission_id = 1 [json_name = "permissionId"];`
     */
    public fun clearPermissionId() {
      _builder.clearPermissionId()
    }

    /**
     * ```
     * 资源标识
     * ```
     *
     * `string resource = 2 [json_name = "resource"];`
     */
    public var resource: kotlin.String
      @kotlin.jvm.JvmName("getResource")
        get() = _builder.resource
      @kotlin.jvm.JvmName("setResource")
        set(value) {
        _builder.resource = value
      }
    /**
     * ```
     * 资源标识
     * ```
     *
     * `string resource = 2 [json_name = "resource"];`
     */
    public fun clearResource() {
      _builder.clearResource()
    }

    /**
     * ```
     * 操作：read/write/delete/admin
     * ```
     *
     * `string action = 3 [json_name = "action"];`
     */
    public var action: kotlin.String
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * ```
     * 操作：read/write/delete/admin
     * ```
     *
     * `string action = 3 [json_name = "action"];`
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * `string description = 4 [json_name = "description"];`
     */
    public var description: kotlin.String
      @kotlin.jvm.JvmName("getDescription")
        get() = _builder.description
      @kotlin.jvm.JvmName("setDescription")
        set(value) {
        _builder.description = value
      }
    /**
     * `string description = 4 [json_name = "description"];`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.auth.v1.Auth.Permission.copy(block: `com.solra.apis.auth.v1`.PermissionKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.Permission =
  `com.solra.apis.auth.v1`.PermissionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

