// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/auth/v1/auth.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.auth.v1;

@kotlin.jvm.JvmName("-initializepolicy")
public inline fun policy(block: com.solra.apis.auth.v1.PolicyKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.Policy =
  com.solra.apis.auth.v1.PolicyKt.Dsl._create(com.solra.apis.auth.v1.Auth.Policy.newBuilder()).apply { block() }._build()
/**
 * ```
 * Policy 访问策略
 * ```
 *
 * Protobuf type `solra.auth.v1.Policy`
 */
public object PolicyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.auth.v1.Auth.Policy.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.auth.v1.Auth.Policy.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.auth.v1.Auth.Policy = _builder.build()

    /**
     * `string policy_id = 1 [json_name = "policyId"];`
     */
    public var policyId: kotlin.String
      @kotlin.jvm.JvmName("getPolicyId")
        get() = _builder.policyId
      @kotlin.jvm.JvmName("setPolicyId")
        set(value) {
        _builder.policyId = value
      }
    /**
     * `string policy_id = 1 [json_name = "policyId"];`
     */
    public fun clearPolicyId() {
      _builder.clearPolicyId()
    }

    /**
     * ```
     * allow / deny
     * ```
     *
     * `string effect = 2 [json_name = "effect"];`
     */
    public var effect: kotlin.String
      @kotlin.jvm.JvmName("getEffect")
        get() = _builder.effect
      @kotlin.jvm.JvmName("setEffect")
        set(value) {
        _builder.effect = value
      }
    /**
     * ```
     * allow / deny
     * ```
     *
     * `string effect = 2 [json_name = "effect"];`
     */
    public fun clearEffect() {
      _builder.clearEffect()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PrincipalsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 用户/角色/组标识
     * ```
     *
     * `repeated string principals = 3 [json_name = "principals"];`
     * @return A list containing the principals.
     */
    public val principals: com.google.protobuf.kotlin.DslList<kotlin.String, PrincipalsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.principalsList
      )
    /**
     * ```
     * 用户/角色/组标识
     * ```
     *
     * `repeated string principals = 3 [json_name = "principals"];`
     * @param value The principals to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPrincipals")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PrincipalsProxy>.add(value: kotlin.String) {
      _builder.addPrincipals(value)
    }
    /**
     * ```
     * 用户/角色/组标识
     * ```
     *
     * `repeated string principals = 3 [json_name = "principals"];`
     * @param value The principals to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPrincipals")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PrincipalsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * 用户/角色/组标识
     * ```
     *
     * `repeated string principals = 3 [json_name = "principals"];`
     * @param values The principals to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPrincipals")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PrincipalsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPrincipals(values)
    }
    /**
     * ```
     * 用户/角色/组标识
     * ```
     *
     * `repeated string principals = 3 [json_name = "principals"];`
     * @param values The principals to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPrincipals")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PrincipalsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * 用户/角色/组标识
     * ```
     *
     * `repeated string principals = 3 [json_name = "principals"];`
     * @param index The index to set the value at.
     * @param value The principals to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPrincipals")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PrincipalsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setPrincipals(index, value)
    }/**
     * ```
     * 用户/角色/组标识
     * ```
     *
     * `repeated string principals = 3 [json_name = "principals"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPrincipals")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PrincipalsProxy>.clear() {
      _builder.clearPrincipals()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ResourcesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 资源标识
     * ```
     *
     * `repeated string resources = 4 [json_name = "resources"];`
     * @return A list containing the resources.
     */
    public val resources: com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.resourcesList
      )
    /**
     * ```
     * 资源标识
     * ```
     *
     * `repeated string resources = 4 [json_name = "resources"];`
     * @param value The resources to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addResources")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.add(value: kotlin.String) {
      _builder.addResources(value)
    }
    /**
     * ```
     * 资源标识
     * ```
     *
     * `repeated string resources = 4 [json_name = "resources"];`
     * @param value The resources to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignResources")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * 资源标识
     * ```
     *
     * `repeated string resources = 4 [json_name = "resources"];`
     * @param values The resources to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllResources")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllResources(values)
    }
    /**
     * ```
     * 资源标识
     * ```
     *
     * `repeated string resources = 4 [json_name = "resources"];`
     * @param values The resources to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllResources")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * 资源标识
     * ```
     *
     * `repeated string resources = 4 [json_name = "resources"];`
     * @param index The index to set the value at.
     * @param value The resources to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setResources")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setResources(index, value)
    }/**
     * ```
     * 资源标识
     * ```
     *
     * `repeated string resources = 4 [json_name = "resources"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setResources")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.clear() {
      _builder.clearResources()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ActionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 操作
     * ```
     *
     * `repeated string actions = 5 [json_name = "actions"];`
     * @return A list containing the actions.
     */
    public val actions: com.google.protobuf.kotlin.DslList<kotlin.String, ActionsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.actionsList
      )
    /**
     * ```
     * 操作
     * ```
     *
     * `repeated string actions = 5 [json_name = "actions"];`
     * @param value The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addActions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ActionsProxy>.add(value: kotlin.String) {
      _builder.addActions(value)
    }
    /**
     * ```
     * 操作
     * ```
     *
     * `repeated string actions = 5 [json_name = "actions"];`
     * @param value The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignActions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ActionsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * 操作
     * ```
     *
     * `repeated string actions = 5 [json_name = "actions"];`
     * @param values The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllActions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ActionsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllActions(values)
    }
    /**
     * ```
     * 操作
     * ```
     *
     * `repeated string actions = 5 [json_name = "actions"];`
     * @param values The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllActions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ActionsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * 操作
     * ```
     *
     * `repeated string actions = 5 [json_name = "actions"];`
     * @param index The index to set the value at.
     * @param value The actions to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setActions")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ActionsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setActions(index, value)
    }/**
     * ```
     * 操作
     * ```
     *
     * `repeated string actions = 5 [json_name = "actions"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setActions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ActionsProxy>.clear() {
      _builder.clearActions()
    }
    /**
     * ```
     * 条件（可选）
     * ```
     *
     * `.solra.auth.v1.Condition condition = 6 [json_name = "condition"];`
     */
    public var condition: com.solra.apis.auth.v1.Auth.Condition
      @kotlin.jvm.JvmName("getCondition")
        get() = _builder.condition
      @kotlin.jvm.JvmName("setCondition")
        set(value) {
        _builder.condition = value
      }
    /**
     * ```
     * 条件（可选）
     * ```
     *
     * `.solra.auth.v1.Condition condition = 6 [json_name = "condition"];`
     */
    public fun clearCondition() {
      _builder.clearCondition()
    }
    /**
     * ```
     * 条件（可选）
     * ```
     *
     * `.solra.auth.v1.Condition condition = 6 [json_name = "condition"];`
     * @return Whether the condition field is set.
     */
    public fun hasCondition(): kotlin.Boolean {
      return _builder.hasCondition()
    }

    public val PolicyKt.Dsl.conditionOrNull: com.solra.apis.auth.v1.Auth.Condition?
      get() = _builder.conditionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.auth.v1.Auth.Policy.copy(block: `com.solra.apis.auth.v1`.PolicyKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.Policy =
  `com.solra.apis.auth.v1`.PolicyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.apis.auth.v1.Auth.PolicyOrBuilder.conditionOrNull: com.solra.apis.auth.v1.Auth.Condition?
  get() = if (hasCondition()) getCondition() else null

