// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.auth.v1;

@kotlin.jvm.JvmName("-initializerefreshTokenRequest")
public inline fun refreshTokenRequest(block: com.solra.apis.auth.v1.RefreshTokenRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.RefreshTokenRequest =
  com.solra.apis.auth.v1.RefreshTokenRequestKt.Dsl._create(com.solra.apis.auth.v1.Auth.RefreshTokenRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * RefreshToken
 * ```
 *
 * Protobuf type `solra.auth.v1.RefreshTokenRequest`
 */
public object RefreshTokenRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.auth.v1.Auth.RefreshTokenRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.auth.v1.Auth.RefreshTokenRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.auth.v1.Auth.RefreshTokenRequest = _builder.build()

    /**
     * `string refresh_token = 1 [json_name = "refreshToken"];`
     */
    public var refreshToken: kotlin.String
      @kotlin.jvm.JvmName("getRefreshToken")
        get() = _builder.refreshToken
      @kotlin.jvm.JvmName("setRefreshToken")
        set(value) {
        _builder.refreshToken = value
      }
    /**
     * `string refresh_token = 1 [json_name = "refreshToken"];`
     */
    public fun clearRefreshToken() {
      _builder.clearRefreshToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.auth.v1.Auth.RefreshTokenRequest.copy(block: `com.solra.apis.auth.v1`.RefreshTokenRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.RefreshTokenRequest =
  `com.solra.apis.auth.v1`.RefreshTokenRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

