// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.apis.auth.v1;

@kotlin.jvm.JvmName("-initializeregisterRequest")
public inline fun registerRequest(block: com.solra.apis.auth.v1.RegisterRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.RegisterRequest =
  com.solra.apis.auth.v1.RegisterRequestKt.Dsl._create(com.solra.apis.auth.v1.Auth.RegisterRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Register
 * ```
 *
 * Protobuf type `solra.auth.v1.RegisterRequest`
 */
public object RegisterRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.apis.auth.v1.Auth.RegisterRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.apis.auth.v1.Auth.RegisterRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.apis.auth.v1.Auth.RegisterRequest = _builder.build()

    /**
     * `string username = 1 [json_name = "username"];`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 1 [json_name = "username"];`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * ```
     * 加密后
     * ```
     *
     * `string password = 2 [json_name = "password"];`
     */
    public var password: kotlin.String
      @kotlin.jvm.JvmName("getPassword")
        get() = _builder.password
      @kotlin.jvm.JvmName("setPassword")
        set(value) {
        _builder.password = value
      }
    /**
     * ```
     * 加密后
     * ```
     *
     * `string password = 2 [json_name = "password"];`
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }

    /**
     * `string email = 3 [json_name = "email"];`
     */
    public var email: kotlin.String
      @kotlin.jvm.JvmName("getEmail")
        get() = _builder.email
      @kotlin.jvm.JvmName("setEmail")
        set(value) {
        _builder.email = value
      }
    /**
     * `string email = 3 [json_name = "email"];`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `string phone = 4 [json_name = "phone"];`
     */
    public var phone: kotlin.String
      @kotlin.jvm.JvmName("getPhone")
        get() = _builder.phone
      @kotlin.jvm.JvmName("setPhone")
        set(value) {
        _builder.phone = value
      }
    /**
     * `string phone = 4 [json_name = "phone"];`
     */
    public fun clearPhone() {
      _builder.clearPhone()
    }

    /**
     * `string display_name = 5 [json_name = "displayName"];`
     */
    public var displayName: kotlin.String
      @kotlin.jvm.JvmName("getDisplayName")
        get() = _builder.displayName
      @kotlin.jvm.JvmName("setDisplayName")
        set(value) {
        _builder.displayName = value
      }
    /**
     * `string display_name = 5 [json_name = "displayName"];`
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }

    /**
     * ```
     * 邀请码（可选）
     * ```
     *
     * `string invite_code = 6 [json_name = "inviteCode"];`
     */
    public var inviteCode: kotlin.String
      @kotlin.jvm.JvmName("getInviteCode")
        get() = _builder.inviteCode
      @kotlin.jvm.JvmName("setInviteCode")
        set(value) {
        _builder.inviteCode = value
      }
    /**
     * ```
     * 邀请码（可选）
     * ```
     *
     * `string invite_code = 6 [json_name = "inviteCode"];`
     */
    public fun clearInviteCode() {
      _builder.clearInviteCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.apis.auth.v1.Auth.RegisterRequest.copy(block: `com.solra.apis.auth.v1`.RegisterRequestKt.Dsl.() -> kotlin.Unit): com.solra.apis.auth.v1.Auth.RegisterRequest =
  `com.solra.apis.auth.v1`.RegisterRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

