// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: not/not.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.not;

@kotlin.jvm.JvmName("-initializeinboxMessage")
public inline fun inboxMessage(block: com.solra.proto.not.InboxMessageKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.InboxMessage =
  com.solra.proto.not.InboxMessageKt.Dsl._create(com.solra.proto.not.Not.InboxMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.not.InboxMessage`
 */
public object InboxMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.not.Not.InboxMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.not.Not.InboxMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.not.Not.InboxMessage = _builder.build()

    /**
     * `string message_id = 1 [json_name = "messageId"];`
     */
    public var messageId: kotlin.String
      @kotlin.jvm.JvmName("getMessageId")
        get() = _builder.messageId
      @kotlin.jvm.JvmName("setMessageId")
        set(value) {
        _builder.messageId = value
      }
    /**
     * `string message_id = 1 [json_name = "messageId"];`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * `.solra.common.UserId sender_id = 2 [json_name = "senderId"];`
     */
    public var senderId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getSenderId")
        get() = _builder.senderId
      @kotlin.jvm.JvmName("setSenderId")
        set(value) {
        _builder.senderId = value
      }
    /**
     * `.solra.common.UserId sender_id = 2 [json_name = "senderId"];`
     */
    public fun clearSenderId() {
      _builder.clearSenderId()
    }
    /**
     * `.solra.common.UserId sender_id = 2 [json_name = "senderId"];`
     * @return Whether the senderId field is set.
     */
    public fun hasSenderId(): kotlin.Boolean {
      return _builder.hasSenderId()
    }

    public val InboxMessageKt.Dsl.senderIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.senderIdOrNull

    /**
     * `.solra.common.UserId recipient_id = 3 [json_name = "recipientId"];`
     */
    public var recipientId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getRecipientId")
        get() = _builder.recipientId
      @kotlin.jvm.JvmName("setRecipientId")
        set(value) {
        _builder.recipientId = value
      }
    /**
     * `.solra.common.UserId recipient_id = 3 [json_name = "recipientId"];`
     */
    public fun clearRecipientId() {
      _builder.clearRecipientId()
    }
    /**
     * `.solra.common.UserId recipient_id = 3 [json_name = "recipientId"];`
     * @return Whether the recipientId field is set.
     */
    public fun hasRecipientId(): kotlin.Boolean {
      return _builder.hasRecipientId()
    }

    public val InboxMessageKt.Dsl.recipientIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.recipientIdOrNull

    /**
     * `.solra.not.MessageType type = 4 [json_name = "type"];`
     */
    public var type: com.solra.proto.not.Not.MessageType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * `.solra.not.MessageType type = 4 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `string content = 5 [json_name = "content"];`
     */
    public var content: kotlin.String
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `string content = 5 [json_name = "content"];`
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * `string attachment_url = 6 [json_name = "attachmentUrl"];`
     */
    public var attachmentUrl: kotlin.String
      @kotlin.jvm.JvmName("getAttachmentUrl")
        get() = _builder.attachmentUrl
      @kotlin.jvm.JvmName("setAttachmentUrl")
        set(value) {
        _builder.attachmentUrl = value
      }
    /**
     * `string attachment_url = 6 [json_name = "attachmentUrl"];`
     */
    public fun clearAttachmentUrl() {
      _builder.clearAttachmentUrl()
    }

    /**
     * `.solra.not.MessageStatus status = 7 [json_name = "status"];`
     */
    public var status: com.solra.proto.not.Not.MessageStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.solra.not.MessageStatus status = 7 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.solra.common.SolraTimestamp sent_at = 8 [json_name = "sentAt"];`
     */
    public var sentAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getSentAt")
        get() = _builder.sentAt
      @kotlin.jvm.JvmName("setSentAt")
        set(value) {
        _builder.sentAt = value
      }
    /**
     * `.solra.common.SolraTimestamp sent_at = 8 [json_name = "sentAt"];`
     */
    public fun clearSentAt() {
      _builder.clearSentAt()
    }
    /**
     * `.solra.common.SolraTimestamp sent_at = 8 [json_name = "sentAt"];`
     * @return Whether the sentAt field is set.
     */
    public fun hasSentAt(): kotlin.Boolean {
      return _builder.hasSentAt()
    }

    public val InboxMessageKt.Dsl.sentAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.sentAtOrNull

    /**
     * `.solra.common.SolraTimestamp read_at = 9 [json_name = "readAt"];`
     */
    public var readAt: com.solra.apis.common.Common.SolraTimestamp
      @kotlin.jvm.JvmName("getReadAt")
        get() = _builder.readAt
      @kotlin.jvm.JvmName("setReadAt")
        set(value) {
        _builder.readAt = value
      }
    /**
     * `.solra.common.SolraTimestamp read_at = 9 [json_name = "readAt"];`
     */
    public fun clearReadAt() {
      _builder.clearReadAt()
    }
    /**
     * `.solra.common.SolraTimestamp read_at = 9 [json_name = "readAt"];`
     * @return Whether the readAt field is set.
     */
    public fun hasReadAt(): kotlin.Boolean {
      return _builder.hasReadAt()
    }

    public val InboxMessageKt.Dsl.readAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
      get() = _builder.readAtOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.not.Not.InboxMessage.copy(block: `com.solra.proto.not`.InboxMessageKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.InboxMessage =
  `com.solra.proto.not`.InboxMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.not.Not.InboxMessageOrBuilder.senderIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasSenderId()) getSenderId() else null

public val com.solra.proto.not.Not.InboxMessageOrBuilder.recipientIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasRecipientId()) getRecipientId() else null

public val com.solra.proto.not.Not.InboxMessageOrBuilder.sentAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasSentAt()) getSentAt() else null

public val com.solra.proto.not.Not.InboxMessageOrBuilder.readAtOrNull: com.solra.apis.common.Common.SolraTimestamp?
  get() = if (hasReadAt()) getReadAt() else null

