// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: not/not.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.not;

@kotlin.jvm.JvmName("-initializelistNotificationsRequest")
public inline fun listNotificationsRequest(block: com.solra.proto.not.ListNotificationsRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.ListNotificationsRequest =
  com.solra.proto.not.ListNotificationsRequestKt.Dsl._create(com.solra.proto.not.Not.ListNotificationsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.not.ListNotificationsRequest`
 */
public object ListNotificationsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.not.Not.ListNotificationsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.not.Not.ListNotificationsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.not.Not.ListNotificationsRequest = _builder.build()

    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public var userId: com.solra.apis.common.Common.UserId
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `.solra.common.UserId user_id = 1 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    public val ListNotificationsRequestKt.Dsl.userIdOrNull: com.solra.apis.common.Common.UserId?
      get() = _builder.userIdOrNull

    /**
     * `.solra.common.PageRequest page = 2 [json_name = "page"];`
     */
    public var page: com.solra.apis.common.Common.PageRequest
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * `.solra.common.PageRequest page = 2 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * `.solra.common.PageRequest page = 2 [json_name = "page"];`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }

    public val ListNotificationsRequestKt.Dsl.pageOrNull: com.solra.apis.common.Common.PageRequest?
      get() = _builder.pageOrNull

    /**
     * `.solra.not.NotificationType type_filter = 3 [json_name = "typeFilter"];`
     */
    public var typeFilter: com.solra.proto.not.Not.NotificationType
      @kotlin.jvm.JvmName("getTypeFilter")
        get() = _builder.typeFilter
      @kotlin.jvm.JvmName("setTypeFilter")
        set(value) {
        _builder.typeFilter = value
      }
    public var typeFilterValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeFilterValue")
        get() = _builder.typeFilterValue
      @kotlin.jvm.JvmName("setTypeFilterValue")
        set(value) {
        _builder.typeFilterValue = value
      }
    /**
     * `.solra.not.NotificationType type_filter = 3 [json_name = "typeFilter"];`
     */
    public fun clearTypeFilter() {
      _builder.clearTypeFilter()
    }

    /**
     * `.solra.not.NotificationStatus status_filter = 4 [json_name = "statusFilter"];`
     */
    public var statusFilter: com.solra.proto.not.Not.NotificationStatus
      @kotlin.jvm.JvmName("getStatusFilter")
        get() = _builder.statusFilter
      @kotlin.jvm.JvmName("setStatusFilter")
        set(value) {
        _builder.statusFilter = value
      }
    public var statusFilterValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusFilterValue")
        get() = _builder.statusFilterValue
      @kotlin.jvm.JvmName("setStatusFilterValue")
        set(value) {
        _builder.statusFilterValue = value
      }
    /**
     * `.solra.not.NotificationStatus status_filter = 4 [json_name = "statusFilter"];`
     */
    public fun clearStatusFilter() {
      _builder.clearStatusFilter()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.not.Not.ListNotificationsRequest.copy(block: `com.solra.proto.not`.ListNotificationsRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.ListNotificationsRequest =
  `com.solra.proto.not`.ListNotificationsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.not.Not.ListNotificationsRequestOrBuilder.userIdOrNull: com.solra.apis.common.Common.UserId?
  get() = if (hasUserId()) getUserId() else null

public val com.solra.proto.not.Not.ListNotificationsRequestOrBuilder.pageOrNull: com.solra.apis.common.Common.PageRequest?
  get() = if (hasPage()) getPage() else null

