// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: solra/not/not.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.not;

@kotlin.jvm.JvmName("-initializemarkAllAsReadResponse")
public inline fun markAllAsReadResponse(block: com.solra.proto.not.MarkAllAsReadResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.MarkAllAsReadResponse =
  com.solra.proto.not.MarkAllAsReadResponseKt.Dsl._create(com.solra.proto.not.Not.MarkAllAsReadResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.not.MarkAllAsReadResponse`
 */
public object MarkAllAsReadResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.not.Not.MarkAllAsReadResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.not.Not.MarkAllAsReadResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.not.Not.MarkAllAsReadResponse = _builder.build()

    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public var error: com.solra.apis.common.Common.SolraError
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.solra.common.SolraError error = 1 [json_name = "error"];`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    public val MarkAllAsReadResponseKt.Dsl.errorOrNull: com.solra.apis.common.Common.SolraError?
      get() = _builder.errorOrNull

    /**
     * `int32 count_marked = 2 [json_name = "countMarked"];`
     */
    public var countMarked: kotlin.Int
      @kotlin.jvm.JvmName("getCountMarked")
        get() = _builder.countMarked
      @kotlin.jvm.JvmName("setCountMarked")
        set(value) {
        _builder.countMarked = value
      }
    /**
     * `int32 count_marked = 2 [json_name = "countMarked"];`
     */
    public fun clearCountMarked() {
      _builder.clearCountMarked()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.not.Not.MarkAllAsReadResponse.copy(block: `com.solra.proto.not`.MarkAllAsReadResponseKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.MarkAllAsReadResponse =
  `com.solra.proto.not`.MarkAllAsReadResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.not.Not.MarkAllAsReadResponseOrBuilder.errorOrNull: com.solra.apis.common.Common.SolraError?
  get() = if (hasError()) getError() else null

