// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: not/not.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.not;

@kotlin.jvm.JvmName("-initializemarkAsReadRequest")
public inline fun markAsReadRequest(block: com.solra.proto.not.MarkAsReadRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.MarkAsReadRequest =
  com.solra.proto.not.MarkAsReadRequestKt.Dsl._create(com.solra.proto.not.Not.MarkAsReadRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.not.MarkAsReadRequest`
 */
public object MarkAsReadRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.not.Not.MarkAsReadRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.not.Not.MarkAsReadRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.not.Not.MarkAsReadRequest = _builder.build()

    /**
     * `string notification_id = 1 [json_name = "notificationId"];`
     */
    public var notificationId: kotlin.String
      @kotlin.jvm.JvmName("getNotificationId")
        get() = _builder.notificationId
      @kotlin.jvm.JvmName("setNotificationId")
        set(value) {
        _builder.notificationId = value
      }
    /**
     * `string notification_id = 1 [json_name = "notificationId"];`
     */
    public fun clearNotificationId() {
      _builder.clearNotificationId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.not.Not.MarkAsReadRequest.copy(block: `com.solra.proto.not`.MarkAsReadRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.MarkAsReadRequest =
  `com.solra.proto.not`.MarkAsReadRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

