// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: not/not.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.not;

@kotlin.jvm.JvmName("-initializepushBody")
public inline fun pushBody(block: com.solra.proto.not.PushBodyKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.PushBody =
  com.solra.proto.not.PushBodyKt.Dsl._create(com.solra.proto.not.Not.PushBody.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.not.PushBody`
 */
public object PushBodyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.not.Not.PushBody.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.not.Not.PushBody.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.not.Not.PushBody = _builder.build()

    /**
     * `string default = 1 [json_name = "default"];`
     */
    public var default: kotlin.String
      @kotlin.jvm.JvmName("getDefault")
        get() = _builder.default
      @kotlin.jvm.JvmName("setDefault")
        set(value) {
        _builder.default = value
      }
    /**
     * `string default = 1 [json_name = "default"];`
     */
    public fun clearDefault() {
      _builder.clearDefault()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LocalizedProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> localized = 2 [json_name = "localized"];`
     */
     public val localized: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, LocalizedProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getLocalizedMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.localizedMap
      )
    /**
     * `map<string, string> localized = 2 [json_name = "localized"];`
     */
    @kotlin.jvm.JvmName("putLocalized")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, LocalizedProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putLocalized(key, value)
       }
    /**
     * `map<string, string> localized = 2 [json_name = "localized"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setLocalized")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, LocalizedProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> localized = 2 [json_name = "localized"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeLocalized")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, LocalizedProxy>
      .remove(key: kotlin.String) {
         _builder.removeLocalized(key)
       }
    /**
     * `map<string, string> localized = 2 [json_name = "localized"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllLocalized")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, LocalizedProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllLocalized(map)
       }
    /**
     * `map<string, string> localized = 2 [json_name = "localized"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearLocalized")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, LocalizedProxy>
      .clear() {
         _builder.clearLocalized()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.not.Not.PushBody.copy(block: `com.solra.proto.not`.PushBodyKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.PushBody =
  `com.solra.proto.not`.PushBodyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

