// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: not/not.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.not;

@kotlin.jvm.JvmName("-initializequietHours")
public inline fun quietHours(block: com.solra.proto.not.QuietHoursKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.QuietHours =
  com.solra.proto.not.QuietHoursKt.Dsl._create(com.solra.proto.not.Not.QuietHours.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.not.QuietHours`
 */
public object QuietHoursKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.not.Not.QuietHours.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.not.Not.QuietHours.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.not.Not.QuietHours = _builder.build()

    /**
     * `bool enabled = 1 [json_name = "enabled"];`
     */
    public var enabled: kotlin.Boolean
      @kotlin.jvm.JvmName("getEnabled")
        get() = _builder.enabled
      @kotlin.jvm.JvmName("setEnabled")
        set(value) {
        _builder.enabled = value
      }
    /**
     * `bool enabled = 1 [json_name = "enabled"];`
     */
    public fun clearEnabled() {
      _builder.clearEnabled()
    }

    /**
     * ```
     * "22:00"
     * ```
     *
     * `string start_time = 2 [json_name = "startTime"];`
     */
    public var startTime: kotlin.String
      @kotlin.jvm.JvmName("getStartTime")
        get() = _builder.startTime
      @kotlin.jvm.JvmName("setStartTime")
        set(value) {
        _builder.startTime = value
      }
    /**
     * ```
     * "22:00"
     * ```
     *
     * `string start_time = 2 [json_name = "startTime"];`
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }

    /**
     * ```
     * "08:00"
     * ```
     *
     * `string end_time = 3 [json_name = "endTime"];`
     */
    public var endTime: kotlin.String
      @kotlin.jvm.JvmName("getEndTime")
        get() = _builder.endTime
      @kotlin.jvm.JvmName("setEndTime")
        set(value) {
        _builder.endTime = value
      }
    /**
     * ```
     * "08:00"
     * ```
     *
     * `string end_time = 3 [json_name = "endTime"];`
     */
    public fun clearEndTime() {
      _builder.clearEndTime()
    }

    /**
     * ```
     * IANA timezone
     * ```
     *
     * `string timezone = 4 [json_name = "timezone"];`
     */
    public var timezone: kotlin.String
      @kotlin.jvm.JvmName("getTimezone")
        get() = _builder.timezone
      @kotlin.jvm.JvmName("setTimezone")
        set(value) {
        _builder.timezone = value
      }
    /**
     * ```
     * IANA timezone
     * ```
     *
     * `string timezone = 4 [json_name = "timezone"];`
     */
    public fun clearTimezone() {
      _builder.clearTimezone()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.not.Not.QuietHours.copy(block: `com.solra.proto.not`.QuietHoursKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.QuietHours =
  `com.solra.proto.not`.QuietHoursKt.Dsl._create(this.toBuilder()).apply { block() }._build()

