// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: not/not.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.solra.proto.not;

@kotlin.jvm.JvmName("-initializeupdateNotificationPreferenceRequest")
public inline fun updateNotificationPreferenceRequest(block: com.solra.proto.not.UpdateNotificationPreferenceRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.UpdateNotificationPreferenceRequest =
  com.solra.proto.not.UpdateNotificationPreferenceRequestKt.Dsl._create(com.solra.proto.not.Not.UpdateNotificationPreferenceRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `solra.not.UpdateNotificationPreferenceRequest`
 */
public object UpdateNotificationPreferenceRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.solra.proto.not.Not.UpdateNotificationPreferenceRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.solra.proto.not.Not.UpdateNotificationPreferenceRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.solra.proto.not.Not.UpdateNotificationPreferenceRequest = _builder.build()

    /**
     * `bool push_enabled = 1 [json_name = "pushEnabled"];`
     */
    public var pushEnabled: kotlin.Boolean
      @kotlin.jvm.JvmName("getPushEnabled")
        get() = _builder.pushEnabled
      @kotlin.jvm.JvmName("setPushEnabled")
        set(value) {
        _builder.pushEnabled = value
      }
    /**
     * `bool push_enabled = 1 [json_name = "pushEnabled"];`
     */
    public fun clearPushEnabled() {
      _builder.clearPushEnabled()
    }

    /**
     * `bool email_enabled = 2 [json_name = "emailEnabled"];`
     */
    public var emailEnabled: kotlin.Boolean
      @kotlin.jvm.JvmName("getEmailEnabled")
        get() = _builder.emailEnabled
      @kotlin.jvm.JvmName("setEmailEnabled")
        set(value) {
        _builder.emailEnabled = value
      }
    /**
     * `bool email_enabled = 2 [json_name = "emailEnabled"];`
     */
    public fun clearEmailEnabled() {
      _builder.clearEmailEnabled()
    }

    /**
     * `bool sms_enabled = 3 [json_name = "smsEnabled"];`
     */
    public var smsEnabled: kotlin.Boolean
      @kotlin.jvm.JvmName("getSmsEnabled")
        get() = _builder.smsEnabled
      @kotlin.jvm.JvmName("setSmsEnabled")
        set(value) {
        _builder.smsEnabled = value
      }
    /**
     * `bool sms_enabled = 3 [json_name = "smsEnabled"];`
     */
    public fun clearSmsEnabled() {
      _builder.clearSmsEnabled()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MutedTypesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .solra.not.NotificationType muted_types = 4 [json_name = "mutedTypes"];`
     */
     public val mutedTypes: com.google.protobuf.kotlin.DslList<com.solra.proto.not.Not.NotificationType, MutedTypesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.mutedTypesList
      )
    /**
     * `repeated .solra.not.NotificationType muted_types = 4 [json_name = "mutedTypes"];`
     * @param value The mutedTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addMutedTypes")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.not.Not.NotificationType, MutedTypesProxy>.add(value: com.solra.proto.not.Not.NotificationType) {
      _builder.addMutedTypes(value)
    }/**
     * `repeated .solra.not.NotificationType muted_types = 4 [json_name = "mutedTypes"];`
     * @param value The mutedTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignMutedTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.not.Not.NotificationType, MutedTypesProxy>.plusAssign(value: com.solra.proto.not.Not.NotificationType) {
      add(value)
    }/**
     * `repeated .solra.not.NotificationType muted_types = 4 [json_name = "mutedTypes"];`
     * @param values The mutedTypes to add.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllMutedTypes")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.not.Not.NotificationType, MutedTypesProxy>.addAll(values: kotlin.collections.Iterable<com.solra.proto.not.Not.NotificationType>) {
      _builder.addAllMutedTypes(values)
    }/**
     * `repeated .solra.not.NotificationType muted_types = 4 [json_name = "mutedTypes"];`
     * @param values The mutedTypes to add.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllMutedTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.not.Not.NotificationType, MutedTypesProxy>.plusAssign(values: kotlin.collections.Iterable<com.solra.proto.not.Not.NotificationType>) {
      addAll(values)
    }/**
     * `repeated .solra.not.NotificationType muted_types = 4 [json_name = "mutedTypes"];`
     * @param index The index to set the value at.
     * @param value The mutedTypes to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMutedTypes")
    public operator fun com.google.protobuf.kotlin.DslList<com.solra.proto.not.Not.NotificationType, MutedTypesProxy>.set(index: kotlin.Int, value: com.solra.proto.not.Not.NotificationType) {
      _builder.setMutedTypes(index, value)
    }/**
     * `repeated .solra.not.NotificationType muted_types = 4 [json_name = "mutedTypes"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMutedTypes")
    public fun com.google.protobuf.kotlin.DslList<com.solra.proto.not.Not.NotificationType, MutedTypesProxy>.clear() {
      _builder.clearMutedTypes()
    }
    /**
     * `.solra.not.QuietHours quiet_hours = 5 [json_name = "quietHours"];`
     */
    public var quietHours: com.solra.proto.not.Not.QuietHours
      @kotlin.jvm.JvmName("getQuietHours")
        get() = _builder.quietHours
      @kotlin.jvm.JvmName("setQuietHours")
        set(value) {
        _builder.quietHours = value
      }
    /**
     * `.solra.not.QuietHours quiet_hours = 5 [json_name = "quietHours"];`
     */
    public fun clearQuietHours() {
      _builder.clearQuietHours()
    }
    /**
     * `.solra.not.QuietHours quiet_hours = 5 [json_name = "quietHours"];`
     * @return Whether the quietHours field is set.
     */
    public fun hasQuietHours(): kotlin.Boolean {
      return _builder.hasQuietHours()
    }

    public val UpdateNotificationPreferenceRequestKt.Dsl.quietHoursOrNull: com.solra.proto.not.Not.QuietHours?
      get() = _builder.quietHoursOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.solra.proto.not.Not.UpdateNotificationPreferenceRequest.copy(block: `com.solra.proto.not`.UpdateNotificationPreferenceRequestKt.Dsl.() -> kotlin.Unit): com.solra.proto.not.Not.UpdateNotificationPreferenceRequest =
  `com.solra.proto.not`.UpdateNotificationPreferenceRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.solra.proto.not.Not.UpdateNotificationPreferenceRequestOrBuilder.quietHoursOrNull: com.solra.proto.not.Not.QuietHours?
  get() = if (hasQuietHours()) getQuietHours() else null

